### ISSUE TITLE
Getting "Signature validation failed. SAML Response rejected"

### ISSUE THREAD

**Issue by clane-axial** [onelogin/python-saml#101]
I'm getting the following error when trying to process a IdP-initiated SAML2 response using python-saml and flask:

    Signature validation failed. SAML Response rejected

I'm following the example [here](https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py). My code is:

    url_data = urlparse(request.url)
    req = {
        "https": "on",
        "http_host": request.host,
        "server_port": url_data.port,
        "script_name": request.path,
        "get_data": request.args.copy(),
        "post_data": request.form.copy()
    }
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
    auth.process_response()

In SAML_PATH, I have the following in my `settings.json` file:

    {
        "strict": false,
        "debug": true,
        "sp": {
            "entityId": "[spEntityId]",
            "assertionConsumerService": {
                "url": "[acsUrl]",
                "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
            },
            "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified",
            "x509cert": "[x509cert]",
            "privateKey": "[privateKey]"
        },
        "idp": {
            "entityId": "[idpEntityId]",
            "singleSignOnService": {
                "url": "http://dummy.com/saml2",
                "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
            },
            "singleLogoutService": {
                "url": "http://dummy.com/saml2",
                "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
            },
            "x509cert": "[x509cert]"
        },
        "security": {
            "nameIdEncrypted": false,
            "authnRequestsSigned": false,
            "logoutRequestSigned": false,
            "logoutResponseSigned": false,
            "signMetadata": false,
            "wantMessagesSigned": true,
            "wantAssertionsSigned": true,
            "wantNameIdEncrypted": false,
            "requestedAuthnContext": false
        }
    }

As you can see, I'm using dummy values for the IdP singleSignOnService and singleLogoutService URLs. I don't think I need them in my case as I just need to process the SAML Response, but I'm not completely sure about that. The response has a signed message and encrypted assertion:

        <?xml version="1.0" encoding="UTF-8"?>
    <saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="[Destination]" ID="[ID]" IssueInstant="2015-11-30T15:35:02.702Z" Version="2.0">
        <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            [Issuer]
        </saml2:Issuer>
        <saml2p:Status>
            <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
        </saml2p:Status>
        <saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="[ID]" Type="http://www.w3.org/2001/04/xmlenc#Element">
                <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" />
                <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                    <xenc:EncryptedKey Id="[ID]" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                        <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" />
                        <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                            <xenc:CipherValue>
                                [CipherValue]
                            </xenc:CipherValue>
                        </xenc:CipherData>
                    </xenc:EncryptedKey>
                </ds:KeyInfo>
                <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
                    <xenc:CipherValue>
                        [CipherValue]
                    </xenc:CipherValue>
                </xenc:CipherData>
            </xenc:EncryptedData>
        </saml2:EncryptedAssertion>
    </saml2p:Response>

I've verified that the x509cert and privateKey are correct. I'm new to SAML2, so I'm hoping it's something simple :) Thank you in advance and please let me know if you need more information.

**Comment by pitbulk** [comment]
@clane-axial, Can you check if the SAMLResponse is also invalidated at this tool?
https://www.samltool.com/validate_response.php

Signature validation is something complex, a simple extra space can invalidate your XML.

**Comment by clane-axial** [comment]
Ah, okay... Let me try those things this afternoon and I'll report back on!

**Comment by clane-axial** [comment]
Okay, I decrypted the XML successfully using:

https://www.samltool.com/decrypt.php

I then tried to validate the decrypted XML using:

https://www.samltool.com/validate_response.php

And I get the following:

    Invalid issuer in the Assertion/Response
    Signature validation failed. SAML Response rejected

I noticed that the Issuer sent over by the IdP isn't a validate URL. Is there a way to ignore that particular check in SAML2? (I'm not sure how much, if any, control I have over what the IdP uses from the Issuer!)

**Comment by pitbulk** [comment]
You got the Issuer error because the value you set on the validator was incorrect (does not match the value in the SAMLResponse):
https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L149

The main problem is the Signature Validation failed. Can you paste the Decrypted Assertion?

**Comment by clane-axial** [comment]
Okay, if I fix the values for the IdP EntityId, then I get the same error I was getting from my code:

    Signature validation failed. SAML Response rejected

Here is the Decrypted Assertion:

    <saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="[Destination]" ID="xr01k8il7469unanedng5sa371u" IssueInstant="2015-11-30T15:35:02.702Z" Version="2.0">
        <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            [Issuer]
        </saml2:Issuer>
        <saml2p:Status>
            <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
        </saml2p:Status>
        <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ID="xmts6qiv7lev8pinipkkla5ucvf" IssueInstant="2015-11-30T15:35:02.857Z" Version="2.0">
            <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
                [Issuer]
            </saml2:Issuer>
            <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:SignedInfo>
                    <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                    <ds:Reference URI="#xmts6qiv7lev8pinipkkla5ucvf">
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs" />
                            </ds:Transform>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                        <ds:DigestValue>
                            [DigestValue]
                        </ds:DigestValue>
                    </ds:Reference>
                </ds:SignedInfo>
                <ds:SignatureValue>
                    [SignatureValue]
                </ds:SignatureValue>
            </ds:Signature>
            <saml2:Subject>
                <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">
                    epasubjecttest
                </saml2:NameID>
                <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                    <saml2:SubjectConfirmationData NotOnOrAfter="2015-11-30T15:37:02.857Z" Recipient="[Recipient]" />
                </saml2:SubjectConfirmation>
            </saml2:Subject>
            <saml2:Conditions NotBefore="2015-11-30T15:34:02.857Z" NotOnOrAfter="2015-11-30T16:35:02.857Z">
                <saml2:AudienceRestriction>
                    <saml2:Audience>
                        [Audience]
                    </saml2:Audience>
                </saml2:AudienceRestriction>
            </saml2:Conditions>
            <saml2:AuthnStatement AuthnInstant="2015-11-30T15:35:02.857Z">
                <saml2:AuthnContext>
                    <saml2:AuthnContextClassRef>
                        urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified
                    </saml2:AuthnContextClassRef>
                </saml2:AuthnContext>
            </saml2:AuthnStatement>
            <saml2:AttributeStatement>
                <saml2:Attribute Name="userid">
                    <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
                        testuserid
                    </saml2:AttributeValue>
                </saml2:Attribute>
            </saml2:AttributeStatement>
        </saml2:Assertion>
    </saml2p:Response>

(I removed all the actual values from the assertion... Not sure let if you need those.)

**Comment by pitbulk** [comment]
The Signature element does not include a KeyInfo element , currently required by the Toolkit:
https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L927

In the ruby-saml toolkit I removed this requirement:
https://github.com/onelogin/ruby-saml/commit/3c9dd5eec80da8cb805fb41a059913f718211908

so I plan to avoid this requirement on the rest of toolkits, but can't say to you how long it will take.

**Comment by clane-axial** [comment]
Okay, I think I understand! It seems like the critical piece is the ds:Signature/ds:KeyInfo/ds:X509Data/ds:X509Certificate element, right? If I know the cert that is being used by the IdP, can I just add the missing elements into the original response?

**Comment by pitbulk** [comment]
Complex issue since your original assertion was encrypted.

**Comment by clane-axial** [comment]
Got it... Okay, thank you very much! I will work with IdP get missing elements add to response.

**Comment by pitbulk** [comment]
If you want to work on a PR, following what I did on [ruby](https://github.com/onelogin/ruby-saml/commit/3c9dd5eec80da8cb805fb41a059913f718211908). I will be able to review it and merge.

**Comment by clane-axial** [comment]
@pitbulk -- I'd be happy to! I'm pretty busy until the holidays, but I should have some time to work on a PR over the break. I'm actually excited to learn more about this topic!

**Comment by ksshetty** [comment]
Hi, I was successful in integrating with the onelogin IdP without any issues. However, after a little effort in attempting to add support to another Idp, I encountered the following error message "Signature validation failed. SAML Response rejected", which led to me this thread. Upon following @pitbulk 's instructions above to use the SAML developer tool to validate the response, I see the following error message "Signature validation failed. Reference validation failed". Can someone please tell me what I might be doing wrong ? Any pointers appreciated. Thanks!

**Comment by AlexandrPy** [comment]
Hi. I am getting the same error. Is there any way to determine what exactly is wrong in the validation? Would be nice to have more informative error messages.

**Comment by AlienBull250** [comment]
I get the exact same error but I have the appropriate <KeyInfo>, <X509> tags in the assertion.  Below is the response being sent.   Anyone have suggestions of things to look at?  Also, I am using the cert fingerprint to validate the signature which I pulled directly from the cert.  Thanks in advance:

<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="s207ee657ac4b80a037add5560c6dfcce02cb028cf" Version="2.0" IssueInstant="2017-08-24T22:44:35Z" Destination="[DESTINATION]"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">[ISSUER]</saml:Issuer><samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
<samlp:StatusCode xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Value="urn:oasis:names:tc:SAML:2.0:status:Success">
</samlp:StatusCode>
</samlp:Status><saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="s283d875d9fac7418ecc4f57ad12049b7f75235052" IssueInstant="2017-08-24T22:44:35Z" Version="2.0">
<saml:Issuer>[ISSUER]</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="#s283d875d9fac7418ecc4f57ad12049b7f75235052">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>Ffy2IhE1PgBfMoPiwTY/B674mHc=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
qocTK7hyMCdtDGGpG5wlmiiQEtzOOdXZBVLGV7tkP2N7dgDex+oa6PwXRYsd7QpAb5ZvPRPXMzQH
WloMyhXE5o/7nm7s3M22NP7nNYxrF3WPvEbYUAnMiwT6V5tWDCCgEons0IY3f0RdGfRK+JEkrkGX
k0NkdbiSY5KKEzTog8cq6KZf4TK3yci0BuuYnhrfde4lwrvN5e8suiOHKoqzdoV354X2bBjJ8HBQ
hGUM+uNFpUpDSefpPaKm04xmWoIadlLRAIpaUR6+2yrFbOXpOPWKRrGuFDDJDFsnBQo+bjuN6eI2
x1fLCqoPIhf044msJXqif2tktyfW/DDVMcZZ/w==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIEFzCCAv+gAwIBAgIBAjANBgkqhkiG9w0BAQsFADCBkzELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
AkZMMRQwEgYDVQQHEwtDb2NvYSBCZWFjaDEMMAoGA1UEChMDSUFNMRwwGgYDVQQLExNQcm9kdWN0
IERldmVsb3BtZW50MRQwEgYDVQQDEwtURlMgRGVtbyBDQTEfMB0GCSqGSIb3DQEJARYQY2RpbGJl
Y2tAZHhjLmNvbTAeFw0xNzA4MjMxMjU2MDBaFw0yMDA4MjMxMjU2MDBaMIGYMQswCQYDVQQGEwJV
UzELMAkGA1UECBMCRkwxFDASBgNVBAcTC0NvY29hIEJlYWNoMQwwCgYDVQQKEwNJQU0xHDAaBgNV
BAsTE1Byb2R1Y3QgRGV2ZWxvcG1lbnQxGTAXBgNVBAMTEFRGUyBEZW1vIFNpZ25pbmcxHzAdBgkq
hkiG9w0BCQEWEGNkaWxiZWNrQGR4Yy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDLH9dL/iHPCnElXKQOyDruW69UIb+CVpLDiq+mrJfdcDiM4MghcOJCg86XXhp439b4V64yDD1r
oOH97EPvoO1POThZtrtVXdtILd6x0t+MBW3XAzfmwqaknHTO2s6GA07KDa5cc0Qg79gV8t2vEIqu
5UUOk/6hQjBMktWBZJCP0Mr/HcgC8qmW8g3XQGudkUwa296Tl2B+MdU1ixoDNfjAr3p/1j0AWC3q
ycZxgdUP0Hv1VxGniRR+1CR/whyUeCMaU+UkOFy9XBY3T9NxONlnFcBYLmixba3pTtSaKqFpweqm
iHBU22jSNHM2sdgSwJ8fRRRjnPxGY6n//IGpcZvpAgMBAAGjbzBtMAwGA1UdEwEB/wQCMAAwHQYD
VR0OBBYEFN/A/l9+lzibbfIeaggiQ0kBOUXmMAsGA1UdDwQEAwIEsDARBglghkgBhvhCAQEEBAMC
BaAwHgYJYIZIAYb4QgENBBEWD3hjYSBjZXJ0aWZpY2F0ZTANBgkqhkiG9w0BAQsFAAOCAQEAl20o
g8ZqJMPlF4zSYty23AKZoGT81LMX9s6gEqefoUL3pDUIa83mLUK/qbo2pnlpqLHd6ZcFqUCcJICG
uY9G33U1wORVBLLJSWn7a3IXKk3pquHeeQ6VZEAsQCtRELYtJvFdR+Ekz9DorIPT+TFLAnHD9J4x
M+BNfZmTgbr4+9Eh9fhnsO3BXj7K9ionqMwXvpmXR8qdaV8I3sWZcBUkkXP8ZbvoHVLhBf7Lv1Pz
8YlgcuNkxVrVIQfFkYGDUFIdkEDOl/im2NWg0yS3cQ6+Azb6TEi75jI8ga5QxYmymmaVTLLsayR1
R9UBDR0LkZ9ylKkBjvScb9L/wufWcARO/g==
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature><saml:Subject>
<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" NameQualifier="[ISSUER]" SPNameQualifier="[SPNameQualifier]">username</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
<saml:SubjectConfirmationData NotOnOrAfter="2017-08-24T22:54:35Z" Recipient="[RECIPIENT]"/></saml:SubjectConfirmation>
</saml:Subject><saml:Conditions NotBefore="2017-08-24T22:34:35Z" NotOnOrAfter="2017-08-24T22:54:35Z">
<saml:AudienceRestriction>
<saml:Audience>[AUDIENCE]</saml:Audience>
</saml:AudienceRestriction>
</saml:Conditions>
<saml:AuthnStatement AuthnInstant="2017-08-24T22:22:14Z" SessionIndex="s2a325021e1c843a4a7327582177fdbc5cea11e101"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement></saml:Assertion></samlp:Response>

**Comment by AlienBull250** [comment]
Nevermind.  Putting the whole x509 string in "onelogin.saml2.idp.x509cert" (has to be all one line no wrap) worked.  Just doing fingerprint didn't work.

**Comment by platipusica** [comment]
I can report that the "Signature validation failed. SAML Response rejected" error was a Certificate problem on a Client with the CA Siteminder SAML.

Successfully connected to a CA Single Sign-On - 12.7

**Comment by poojated** [comment]
my response is validated on Samltool.com still after sending i got the error Signature validation issue.
can anyone tell me what could be the issue
