### ISSUE TITLE
Certificate choice for signing and validation

### ISSUE THREAD

**Issue by sidprak** [onelogin/python-saml#102]
We currently use this library on our SP and integrate with a wide array of IDPs including ADFS. We noticed that the library makes an explicit choice about whether to use the SP or IDP cert for certain cases, for example:
* AuthN request signing - SP cert
* ACS request validation - IDP cert
* Logout request signing - SP cert
* Logout response validation - IDP cert

Just browsing, it seems like the pattern is to use the certificate from the system where the request originates. Is that true? If so, we're curious why these certificate choices are made and if we can make this configurable? We are experiencing an issue integrating with ADFS because it seems like ADFS only supports using one certificate pair for validating both the logout request and response.

**Comment by pitbulk** [comment]
At SAML, an entity signs a SAML Message with its private key, later the other entity validates that SAML Message with the public cert of the entity that signed the message.

Notice that this toolkit manage LogoutRequest and LogoutResponse sent by the IdP, so:
* AuthN request signing - with SP private key
* SAML Response (ACS request) validation - with IDP public cert
* Logout request signing - with SP private key
* Logout request validation - with IDP public cert
* Logout response signing - with SP private key 
* Logout response validation - with IDP cert

So let me know exactly what ADFS error you got, sure we can solve it.

**Comment by sidprak** [comment]
@pitbulk thanks for the quick reply.

> At SAML, an entity signs a SAML Message with its private key, later the other entity validates that SAML Message with the public cert of the entity that signed the message.

Is this something from the SAML spec or an assumption that was made when the library was developed?

It's not really an error that we get with ADFS but we're just unable to integrate. We're told that ADFS only supports the configuration of one certificate for both logout request validation and logout response signing (i.e. one certificate will be used to validate the logout request from the SP to the IDP, and the same cert will be used to sign the logout response going back to the SP). This doesn't work with our SP because the SP private key is used for one case and the IDP public cert is used for the other. Does that make sense?

**Comment by pitbulk** [comment]
```
Is this something from the SAML spec or an assumption that
was made when the library was developed?
```
SAML spec

```
One certificate will be used to validate the logout request from the SP to
the IDP, and the same cert will be used to sign the logout response going back to the SP
```
No:
* To validate the logout request from the SP to the IDP, you need the SP certificate.
* To sign the logout response going back to the SP, you need the IdP private key.

Me and many developers were able to link this toolkit with ADFS, you may misunderstood something.

http://www.xml.com/pub/a/2001/08/08/xmldsig.html

**Comment by pmonks** [comment]
Thanks @pitbulk.  Where do you see that in the SAML spec?

FWIW this ADFS instance is not under our control, so we're somewhat at the mercy of the administrator who manages it.

**Comment by pitbulk** [comment]
Is [how digital signature works for asure the integrty](https://technet.microsoft.com/en-us/library/cc700808.aspx), is not just for SAML.

IdP and SP entities exchange metadata that used to contain the public certificate (that is related to a private key) used for signing and encrypting.
