### ISSUE TITLE
ALOWED or ALLOWED? Misspell？

### ISSUE THREAD

**Issue by WangErGou** [onelogin/python-saml#103]
Code in [python-saml/src/onelogin/saml2/constants.py](python-saml/src/onelogin/saml2/constants.py) line 22: `ALOWED_CLOCK_DRIFT = 300`. Maybe `ALLOWED_CLOCK_DRIFT = 300` ?

**Comment by pitbulk** [comment]
you are right, should be ALLOWED_CLOCK_DRIFT
