### ISSUE TITLE
Support for NameID nested AttributeValue

### ISSUE THREAD

**Issue by Fizzadar** [onelogin/python-saml#104]
I'm currently using `python-saml` to integrate a number of SAML/Shibboleth based University IDPs with our SP. Unfortunately, for one of these IDPs, we are receiving `AttributeValue` results nested inside `NameID` elements:

```xml
<saml2:Attribute FriendlyName="eduPersonTargetedID" Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
   <saml2:AttributeValue>
      <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="https://idpID" SPNameQualifier="https://spID">ACTUAL_RANDOM_VALUE</saml2:NameID>
   </saml2:AttributeValue>
</saml2:Attribute>
```

Would there be interest in supporting this?

**Comment by pitbulk** [comment]
The Assertions and Protocols for the OASIS Security Assertion Markup Language (SAML) V2.0 says
```
<element name="Attribute" type="saml:AttributeType"/>
    <complexType name="AttributeType">
    <sequence>
        <element ref="saml:AttributeValue" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="Name" type="string" use="required"/>
    <attribute name="NameFormat" type="anyURI" use="optional"/>
    <attribute name="FriendlyName" type="string" use="optional"/>
    <anyAttribute namespace="##other" processContents="lax"/>
</complexType>
```
and AttributeValue is of the xs:anyType type, which allows any well-formed XML to appear as the content of the element, so I assume that "nested AttributeValue" are allowed, but we never required it.

If you want to contribute with a PR, you are welcome.

**Comment by Fizzadar** [comment]
@pitbulk thanks for the update - I'm going to look into implementing this next week. As for the data - do you think it would be best to return the XML Element as the attribute contents or the XML string?

I'm assuming it's acceptable to nest _any_ XML under the element, so don't want to build anything specific to `NameID`.

**Comment by pitbulk** [comment]
```
<saml2:AttributeStatement>
    <saml2:Attribute Name="mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <sam2l:AttributeValue xsi:type="xs:string">test@example.com</sam2l:AttributeValue>
    </saml2:Attribute>
    <saml2:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml2:AttributeValue xsi:type="xs:string">users</saml2:AttributeValue>
        <saml2:AttributeValue xsi:type="xs:string">examplerole1</saml2:AttributeValue>
    </saml2:Attribute>
    <saml2:Attribute FriendlyName="eduPersonTargetedID" Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
        <saml2:AttributeValue>
            <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="https://idpID" SPNameQualifier="https://spID">ACTUAL_RANDOM_VALUE</saml2:NameID>
        </saml2:AttributeValue>
    </saml2:Attribute>
</saml:AttributeStatement>
```
After process that. I expect something like:

{
    "mail": ['test@example.com'],
    "eduPersonAffiliation": ["users", 'examplerole1'],
    "eduPersonTargetedID":['<saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" NameQualifier="https://idpID" SPNameQualifier="https://spID">ACTUAL_RANDOM_VALUE</saml2:NameID>']
}

so you can process later the XML content (SP knows what to expect so can handle that XML).
If eduPersonTargetedID used to have this type of value, maybe we can parse for this specific case and return something like:

 {
    "mail": ['test@example.com'],
    "eduPersonAffiliation": ["users", 'examplerole1'],
    "eduPersonTargetedID":[{
          "NameID": {
             "Format": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
             "NameQualifier". "https://spID",
             "Value": "ACTUAL_RANDOM_VALUE"
         }
    }]
}

**Comment by Fizzadar** [comment]
Closing as this is now merged, thanks @pitbulk!
