### ISSUE TITLE
ENH: ability to validate SAML assertions independent of response wrapper?

### ISSUE THREAD

**Issue by dbiollo** [onelogin/python-saml#107]
I like the design of the OneLogin SAML library and have used it for SSO & SLO. Now I'm looking at implementing OAuth2 + SAML Bearer assertions and would like to be able to use this same library to take care of the assertion processing and validation. Currently I can do this with a bit of hacking but with some refactoring this could be more easily and directly supported.

Would like to request an enhancement to split out a separate instantiable Assertion class out of the OneLogin_Saml2_Response, including the assertion validation functionality.

Currently I am working around this by taking a saml:Assertion and wrapping it into a samlp:Response, in order to call "is_valid", and also access the nameId & attributes. Note that *encoded_assertion* is the Base64 encoded saml:Assertion XML string:

```python
  fake_assertion = OneLogin_Saml2_Response(settings, encoded_assertion)
  new_root = etree.Element("{" + OneLogin_Saml2_Constants.NS_SAMLP + "}" + 'Response',
                                 attrib=self.fake_assertion.attrib,
                                 nsmap=OneLogin_Saml2_Constants.NSMAP)
  issuer = deepcopy(OneLogin_Saml2_Utils.query(fake_assertion, "/saml:Assertion/saml:Issuer")[0])
  status = etree.XML('<samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>')
  new_root.append(issuer)
  new_root.append(status)
  new_root.append(fake_assertion)
  fake_assertion = new_root   # now wrapped in a Response

  if fake_assertion.is_valid(request):
    # do some authorization
```

It would be much nicer to be able to directly work with the Assertion, say via a new class:
```python
  assertion = OneLogin_Saml2_Assertion(settings, encoded_assertion)
  if assertion.is_valid(request):
    # do some authorization
```

**Comment by pitbulk** [comment]
Hi dbiollo,

Its not a bad idea, but this implies a lot of work:
* redo the response validation
* redo unit test
* review security

I think is easier for you, if at your OAuth project that has python-saml as dependence, you add Assertion class that use the utils of the Toolkit, not very hard to take from the response.py what you need and remove the rest. If you need help, I can review your code.

**Comment by dbiollo** [comment]
Was wondering if you guys have any plans to support SAML2 Bearer Assertion Profile for OAuth2? Technically it's not the assertion validation that I need but rather the whole workflow. Currently using the OneLogin library for the assertion validation (with hack described above) plus another OAuth2 library. 

I understand it could be quite an effort to refactor out the assertion validation; thanks for your consideration.
