### ISSUE TITLE
Ensure getting assertion when signature reference URI is empty

### ISSUE THREAD

**Issue by toopy** [onelogin/python-saml#108]
Getting an assertion requires a reference URI, cf.:

- https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L406
- https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L412

But when we validate a signature, we can deduce it from the parent ID, cf.:

- https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L940

In some cases, if reference URI parameter is empty, a fallback to the parent ID as in the signature validation method can help.

At the first sight, it does not look insecure according all the checks preformed in the `process_response` method.

Il would like to submit soon a PR that implement this behavior or is it useless ?

**Comment by pitbulk** [comment]
Submit tthe PR and let's review it
