### ISSUE TITLE
AttributeConsumingService tag in SP metadata

### ISSUE THREAD

**Issue by jimmyislive** [onelogin/python-saml#110]
Is it possible to support the AttributeConsumingService tag in the initial SSO AuthnRequest?

From the spec: "The <AttributeConsumingService> element defines a particular service offered by the service provider in terms of the attributes the service requires or desires."

It is an optional element in the metadata.

**Comment by pitbulk** [comment]
Why you need that endpoint and why AssertionConsumingService is not enough?

**Comment by jimmyislive** [comment]
There can be zero or more AttributeConsumingService tag in the AuthnRequest as per the spec.

This can contain:
   <ServiceName>
   <ServiceDescription>
   <RequestedAttribute>

The ServiceName/ServiceDescription tells the IdP more info about the service requesting the data. The RequestedAttribute can be used by the IdP as a hint as to what attributes the IdP needs to send back along with the assertions in it's response.

This would help in better inter-operatability between SP/IdP. 

I don't think there is anything called AssertionConsumingService. I'm guessing you meant AssertionConsumerServiceURL (?), which is what I am using now.

I was asking about the AttributeConsumingService so as to give IdP hints as to what attributes I want back in the response.

thx...

**Comment by pitbulk** [comment]
@jimmyislive got it.

[md:AssertionConsumerService](http://www.datypic.com/sc/saml2/e-md_AssertionConsumerService.html) defines endpoint where the Service Provider expects the SAMLResponse with the Assertion.

I see that you want support for RequestedAttribute defined at [AttributeConsumingService](http://www.datypic.com/sc/saml2/e-md_AttributeConsumingService.html).

This is an improvement that we will consider.

Extend the SP settings with a new attribute RequiredAttributes (array). If defined, Metadata and AuthNRFRequest will include that AttributeConsumingService tag.

Are you interested on contribe this feature with a PR?

**Comment by jimmyislive** [comment]
Sure, i'll send in a PR.

**Comment by jimmyislive** [comment]
Do I need some kind of permissions to push to a feature branch?

```
Jimmy-Johns-Mac:python-saml jjohn$ git push origin feature/requested_attrib_support
ERROR: Permission to onelogin/python-saml.git denied to jimmyislive.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Jimmy-Johns-Mac:python-saml jjohn$
```

**Comment by pitbulk** [comment]
Yes, you may fork the project, create there the brunch and send us the PR.

**Comment by jimmyislive** [comment]
@pitbulk https://github.com/onelogin/python-saml/pull/115

#review

**Comment by pitbulk** [comment]
[Fixed](https://github.com/onelogin/python-saml/commit/b44e7fb5576716ec2fc20d2fef15ddcb5a9b0aad)
