### ISSUE TITLE
xmlsec.initialize() in validate_sign hangs

### ISSUE THREAD

**Issue by kgodey** [onelogin/python-saml#120]
I've set up a SAML SP using the SAML backend provided by `python-social-auth` (which uses `python-saml`), and I'm trying to test logging in using TestShib. It all works properly, but it hangs when it TestShib redirects to the auth completed URL. By adding logs, I've managed to track it down to the `xmlsec.initialize()` call in the `validate_sign` function (line 914 in `onelogin/saml2/utils.py`). When I comment out all the `xmlsec` related code, it works fine. Also, calling `xmlsec.initialize()` through the Python shell works fine.

Any help would be much appreciated.

**Comment by pitbulk** [comment]
validate_sign is a very important method that verifies the signature of the SAMLResponse.

What error have you experienced? Can you paste the trace?

Also, try to validate the SAMLResponse here:
https://www.samltool.com/validate_response.php

**Comment by kgodey** [comment]
@pitbulk there's no error, it just stalls out. I have no intention of skipping `validate_sign` in my final code, I was only commenting out lines to try and figure out what line of code was causing the stalling.

Validating the SAMLResponse is giving me an "unable to parse XML" error, and I can clearly see that the XML seems cut off. This is the response I get from TestShib, though – why would TestShib be returning invalid XML? Have I misconfigured something?

Also, here's the response in case that helps:

```
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9rcml0aS5yaWRlY2VsbC5jb20vY29tcGxldGUvc2FtbC8iIElEPSJfZGMzNThkMmY0NGNmNWViM2NhMTViZWM0MzRmZjE2NjEiIEluUmVzcG9uc2VUbz0iT05FTE9HSU5fOTdkMjQ5NTk3NTE2NTMzNTVhZGYzNDY3Mzg0MzIwYWFjYzZlY2NmNiIgSXNzdWVJbnN0YW50PSIyMDE2LTAzLTA5VDIwOjUxOjU2LjU0NFoiIFZlcnNpb249IjIuMCI+PHNhbWwyOklzc3VlciB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDplbnRpdHkiPmh0dHBzOi8vaWRwLnRlc3RzaGliLm9yZy9pZHAvc2hpYmJvbGV0aDwvc2FtbDI6SXNzdWVyPjxzYW1sMnA6U3RhdHVzPjxzYW1sMnA6U3RhdHVzQ29kZSBWYWx1ZT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnN0YXR1czpTdWNjZXNzIi8+PC9zYW1sMnA6U3RhdHVzPjxzYW1sMjpFbmNyeXB0ZWRBc3NlcnRpb24geG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPjx4ZW5jOkVuY3J5cHRlZERhdGEgeG1sbnM6eGVuYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjIiBJZD0iX2Y2MTIzYzAyM2UyY2RlZTU5NjRiYTVlZDI5Mzg3N2RlIiBUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNFbGVtZW50Ij48eGVuYzpFbmNyeXB0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjYWVzMTI4LWNiYyIgeG1sbnM6eGVuYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjIi8+PGRzOktleUluZm8geG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPjx4ZW5jOkVuY3J5cHRlZEtleSBJZD0iXzY5ZGM0MjMyMjViNDgwNTQ3Yjk2OWQxNWZjNDU5YjQwIiB4bWxuczp4ZW5jPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyMiPjx4ZW5jOkVuY3J5cHRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNyc2Etb2FlcC1tZ2YxcCIgeG1sbnM6eGVuYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjIj48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3NoYTEiIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIi8+PC94ZW5jOkVuY3J5cHRpb25NZXRob2Q+PGRzOktleUluZm8+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q2VydGlmaWNhdGU+TUlJQ2dEQ0NBZW1nQXdJQkFnSUpBT2lEd0pJRHhYbjRNQTBHQ1NxR1NJYjNEUUVCQlFVQU1EVXhDekFKQmdOVkJBWVRBbFZUTVJNdwpFUVlEVlFRSUV3cFRiMjFsTFZOMFlYUmxNUkV3RHdZRFZRUUtFd2hTYVdSbFEyVnNiREFlRncweE5qQXpNRFF5TXpBeE16bGFGdzB5Ck5qQXpNRFF5TXpBeE16bGFNRFV4Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cFRiMjFsTFZOMFlYUmxNUkV3RHdZRFZRUUsKRXdoU2FXUmxRMlZzYkRDQm56QU5CZ2txaGtpRzl3MEJBUUVGQUFPQmpRQXdnWWtDZ1lFQXJhc0VtenpLazdoUjREUnRha1owaU0vSgovV0JkRExxY1lVbUV4TnF5bGN5dlgyRGhEV01JR0d3UnRaVFJaZWlFZnNQV1cydFBjdyt0dGpadHlwbCtNQ29UMzRJV1JXK2svM1RjCmVhZHBob2pZRzA0Q284dW1rOFdRQXdkWjM5b2RUWHRwVEYwTnZsdjBQUnJiKzBPYk5qQklwc0dpdUxpWHV5T0pTSXIxMDM4Q0F3RUEKQWFPQmx6Q0JsREFkQmdOVkhRNEVGZ1FVaGpYZU5BL1RnNExnY1cwYUhweFVJejdXWmFvd1pRWURWUjBqQkY0d1hJQVVoalhlTkEvVApnNExnY1cwYUhweFVJejdXWmFxaE9hUTNNRFV4Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cFRiMjFsTFZOMFlYUmxNUkV3CkR3WURWUVFLRXdoU2FXUmxRMlZzYklJSkFPaUR3SklEeFhuNE1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFRkJRQUQKZ1lFQUtwdmpNVnhoTEltNHFtZWU2eG1rdThWQndSVkFOQlRWWC9VUzZzRWRJTDlMSksrSHBtMmRDRHMxdWhiNWdOSmVsekRtai9ORgpWeXRab3VMR0VIMGRURXBFdVYvNlZWVHFoTFZwNzA3RjFVVTZoSlR0S2E1bkJoOUVkV1hzTnVBaVBmaXo4UitLTHdTVzU5dG9sTFRhCnBwWWQ5aGpPQ3ZtdUFZZkowZnVzUWZJPTwvZHM6WDUwOUNlcnRpZmljYXRlPjwvZHM6WDUwOURhdGE+PC9kczpLZXlJbmZvPjx4ZW5jOkNpcGhlckRhdGEgeG1sbnM6eGVuYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjIj48eGVuYzpDaXBoZXJWYWx1ZT5GQmtQZTdWeVhDV0tXbHpBKzkwQ3BkSjZlRG1BV2N2eFlsU2xsODJ0eWpWL2pnSUxTb0VrU01aV2xMbmpLcDNTNFY3WU44enNCYmlqUjlpS2xMVmx0WC9hL1VXbXlkdjgwQ2JsTjMyMVQyTE5wOVF1ZjR6bVRjQzNUUnR4eTIvdXdYMjZaK2N5Umx0K1NrcHNNTkhxcDQ1VnZVVkp0UWJEdGxKS2JaQ2NEWEU9PC94ZW5jOkNpcGhlclZhbHVlPjwveGVuYzpDaXBoZXJEYXRhPjwveGVuYzpFbmNyeXB0ZWRLZXk+PC9kczpLZXlJbmZvPjx4ZW5jOkNpcGhlckRhdGEgeG1sbnM6eGVuYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjIj48eGVuYzpDaXBoZXJWYWx1ZT40dFAyTEx3QXhFYjc5RzhSWHArRW5HUzUwSlAvR3NwdlJ2aFhJTTFIVjhkNE04ejUwQzlibWVMQk9UbDJXSlg4c3c2SlBPWUt2VkpIbzZnVlhHRVAvV2dMZEQ3S1hNN0xhNjd5M0lNbWp4NFZDcENxTndocHZHTGJrc1JqWDM0NXdOV2ZFOE81Q0RiLzFRQWxlOHJLWVNZSXowcFUvRWF2MUh2RGtQQStDeEp1Z1BkRVhYR3BDanNEQkJhaHNTYUZJVlVGcjMxZ21FVXh4aGR0T3ZOczZVVE1YNXY3UWJGbFlmMnpZZjJIcklrYU9CVGl3eXpWbWpidWc0aWp6eS94eXNya0lmaHFveFRjR2s5TERTQnk1WVJ0c3ZJMzZ4QlRWWHJ1VHRzZzlUd1g4ZGdocUQydTRwR3dLdm5hQmJ6clhKUkNlQ3FrTnZGTUpvMUZLdEtuaGVjV0NyU29WeTRiSWYyNkQvUmV6VEE1STRzY0dMLzJncEJBNUxFdkJmYkNJdStLMU96NEhYTGlRd2lRNGRpb0JqNDk1M01aWGpDbnpLSHBiNFBIdTUveXMxc0Q4M0lyMWRLWnVJUVpMQ0x2MGMreWV0WE1Yc0pud0lURXlLVG5YTHNYY2Y4VVQzN2x6bkJDZXNqMmwyYWlrZkFJbEdrbC9VL1UwV3RyRGxPbjlCM0NoU3c4a1NWWUlIUGJOdERzR3FpNmZST3k1Tm9UbnpBdVlNa3MxZER2eXhSemZGRnpkZk5yQjAzbDdNZFV4UG5NNXhkV1dZNzFyVURLK21vN2I1NytmZEYwSjl1TVQyenZPWWlNTHhTQ0YwOE1UeUdiRTVQUmJjM1RqMGM5NjFNNElaRmNKN3ozTFZidVBCaTRjbnE4VGNrdXQ2eGE4d09MVXJTdFBOWjNjbnE5UlNmdjVOR3RzeDQ0MHBDdk5jbm9uWUNhbDFibCtkMlBzRjREWVZkUy9LdlBwdkZpcjU1b1VPTC9LUHVFOGJvNXlhZEgvZUZQZDZVMW9HOTA0VjFsbFUxQnRTMDRwNStDZUM1eVU0ZEJNVjl2OVJmNXVTemFpeW5FeVJTNytXZExBd2NHeFZ3MG9tTjZWNHhOS3FJRWR3YnMxVXlid2hYMExITWR1dDU4WnpZYnZSS2JwSjFTU2w0bTc5TTJiUkZIU0wxQ1JDcmFtL2lwSTNJMUlrbzlka21iak5qc3poR1RsRTRjR3h1ekpYb1JpREVGNXEzTUlwTVFJMnVacldDcElIU1BBOEZEdTFValFSaHhFNkJNMjNNMU41REhvWUIreWhOMmowbHRGeHlQR0grTGo2Ukk5dVV0SHZIWTYzZDJTaGJFN0wxU3ZoZ2tYQkovMFE1L3FFUFNVRGZuWTdkQWNYZkFuVklaaEhDNEhtbzBMVWpLSnFWWXRITXZLTy83VTV0Wk1PWll4YU9SbkRoS29NVERKNmpKeXhIc2xwaVRaQ1BpOEs2ZytrVFBhL2k1R2lSd0hKT1U5M2s0UDcwcUhZWEh2cjdOVXJBbkJJVWpCVXFiR1VabHNxcTIzUGJqeVVqbVlSaGszakhtK0UzOFV5ZUFqOWN6WHFzYk1XbDlyeHVTVnpRVk5uRm84ZWRZc3VVQlhSOXd4aEF0Q3JtT2RnOVpnb1ZPeklITEVHUEFpNWZScGFtS1RzSlF5M3NCdVlpdkNtNUNxN0N3RUttV09DUEtEakR4ZFNsMzBuMUdmcjBDODFJZ1BqSFRqditnNXNrc0VPTVR6cm92Vm4yb2k3UnVlZTUya1h2aVFveHZrMndxdTVzcFJJRzl4YTVPMW5wR3FOWURBUlpHVU9iN0RvUVZSRTFKNjZsZTBhS25hdERnVk41VC9XMERjNE1BdFgzaXhNVkdVVUROTnRSdm82ZVVtZzJxTHpkKzJHN1p3NUNqSEFyUTlBUk1iWWNWRUtBdEVKNVo2aXl4ZGdaMnAzS3I1eGdtdndKQTJPdk45R055a0psMG5LYnlTa0cybGZOTStGdWZCMXhaaHZBQ0lPOXhSckxmS0o2cjQ3N3ljVXlYTjJ0bTA2REZpY0JwZDZUMnhNYURVZ1ViSk1jVlRaNVVDR1lxZ1dLOGduUHVOZUNiY2xYbDVualoxcllwT0Q5cjdsOEdmV1RLOWFOaGpJNmNRTGZZMXhCa1htQjMyZTJkUHRlZjR5OEdsRWw3eTlrNFJBMlM0U1hwL0JEdTBBUmE3ZFFkYWt0dGpycmJBT0hacGFFQm13MGYvaDdoRnZKRUJGT2FhcVNoYUtDRHlZT0lvdmNEd3JBRVdYSUtZdHpQNzdPREZsNW4xS3p0SzNGOUhNRTRKVFNUYTJxR2E4QUJWU0crOE81ckthZFE4cTVDdFE1TWcxNXpYS1l2RVdJS01paHRiYkt0RFlUZmJTOUV4NW1CeWs1TmdITVJDRkhJMHl2UTV0emxveTNhUHl5L0YxdDEvUkF1T2ZHQm1tNUp1aGpkMXBERkhSazRwTi9DekxFTWZaR2lxc3lFdG1ZRS9RS1dvbG1GTGhyLzkxektNTDNBTTl3aVMrQ25KcVJZSEdsc3RZcWtublM5SmRJWGZiUGNtUDlLeHh1ZjNib2w4a3RGWk52YWNWc0xsMjRKbXNXNXNYV3d0NTRJQUNoRy95ZXZnUDZsYnZ1WG8xSDF5ZE1jRC9YZzhLL3JmcWlwQ0M4dnVvdTF4dXpHanY5SkRPa3JZV3JGYWIzcndlVDJDQzZlMWJSNndKb2dBbUoxSFlaUm5PMER0Z2Y5R3R5UmxYYXhwajhhNmJUZGwvTnJHY3JzS1VmWHlYQzU3V2VTL2lLYW9kNzhyYzlBNkZvaWUvcExGUkZ1eVZFWjVFTE5XbjhIL2kxVy80UCt1eXFxdk9SM0c3dEZ0eHNxSDFzcnZ0bkQ1Wll1NERtOVRuWWtqRHdtU2pZUDdndWVYOXMxSEladEI3U0YwRmVoWC9VRWVCSDJ6SWNKcDd4eWNzNlpOcCtHSElnUEU1SVJ5bzIxdDZ1LzJqMERQUUxTalBHNFp5MnpMR0JLcGRLNG91V2Q3dHRTQ2RydWI4SE5oNjF1NHA0WWw3NEEwVlpvaWdXUENUc2VjUDNlcGhyQXkyZnlzSVRiRTRQRzZwbWhXTE82WFRxcDlTNEx3MkNpdFNLNXZLNkF1TGEzRTVYNnRsTG1oZkJQNWltR2NHM0lJbVcyNU1IYXE1aHBwM2d6REpnUGhkcGhBQkkxUDhGK1czaFdrU3I4eW9KaHB1ZnM2UW9hN0VJZjhlbXNvN1RCT1pMa2pyMUo5Tkx3Ukdqekl3eHgxNW5Id3BST3NxdlBXVU9HYzZnaWROWE84azA1aUJqVDNubmlDdk1KRHVpL1U5eTBwWUhZMEZkcDhTWU90WXVXN00ySWVyYUZ6djJTYnNEbGluYjdoRE56ZTJaQ00rWmZaY1hLUWU3emEyTnU4NXVUK1BiRXVYdkNFQ0EyWGdOVDVEUG9QQ3l0aS9LVEtMUGFHWDJXS08xcWQ1bTIwVndRZm5Ib3hTb1FrcUhrZ2RSUzFsLzJJWGtDdFRoYzJ5dkZWUlNhcTVqUE8rakIzV1pJTVlEcnkvMnZQUEl2MUo0d2lBMThZZlN6TGppcVM2aXpsckpRQ2hwNVQ2UTRidmppSWUzY21ZbHVmWC9UZDNZV0oyOUFWKzY0UGUwNG9kTmlDdkd0Rk5BWmtQb3QySnRITENkTTJqc09aeHpNNFpCenovT0ZCY0x4WHBNdTlPSXhmVktwVGNUQ0xBVVN1UStxSS9NM2h0aGxFYlU4TDRtWkJsR3M5dmNSajEvaEZHN2R3RitCdXBIR3czTnR6NG1xR21FbFR0MlBma2JFbGpHUnE2YzFuM3NlbVJFOEZUUldEaytsanlWNVlCdTZuRW9FNTk4b1RCeFcyQzR4ZjY5MC9yWjdSN3VVWFJ1TzdFSDd6YzRCUEtlUkNOdWJWRWlyejMxWWxsL2lOWUxkcTQ5M0lWMzJBcEVvWFNsT1B2WXVnR0N4ZlMvTDlsS210b1BpVytvc2p4OExhWDM1QTl1TDhPaW14dklMejNZcjZkbXpTQmNyMzJneWsxWEF2Ui9HRVBaQmhObzJaZW9odk9leDExdUtCdHZGNGpkcVVZSU5HZ0VyQ1FPdXlTaDh0UWs0dHkvK3M0a1p6ZTNpY2VZWGF0bWNWQWV4SVVBYzVyMXI1VVRGbFpLdmFGM2N2SWxmMmtla21Oa3FnOE9SajRhckdsVEp2ajZWR1NwRGJrQS9zbDZKWFgyUjZiV0diNWNMcXhtanhydU9UR2dIUmo3VFRLL1FFUXBwOUxLMGtUc042OXBaNUFHb3RPVGtVWHpyNVFuTDFXUWd1MWF3ZnZ0S0dKZHhqYXJUTmtZK1dibXFmYzBndWl3UDdWRFkrLzMrbU5jcW1TVVQ
```
Thanks!

**Comment by kgodey** [comment]
Here's a gist of the XML response: https://gist.github.com/kgodey/63d23dc3ff2e5e959df5

**Comment by pitbulk** [comment]
You may decode it before paste on the online validator

**Comment by kgodey** [comment]
@pitbulk please ignore my last two comments, it turns out that there was a length limitation on the logging. the XML response is not actually truncated.

**Comment by kgodey** [comment]
@pitbulk the validator says:

The SAML Response is invalid.

The response was received at https://kriti.ridecell.com/accounts/profile/ instead of https://kriti.ridecell.com/complete/saml/
A valid SubjectConfirmation was not found on this Response

**Comment by kgodey** [comment]
I've tried two more requests, both of them say that the SAML response is valid. I'm still running into the error where the `xmlsec.initialize()` line just stalls out though.

**Comment by pitbulk** [comment]
Maybe there is some problem with the xmlsec instalation.

Can you install test dependences
```
pip install -e ".[test]"
```
and execute the test?
```
python setup.py test
```

**Comment by kgodey** [comment]
The tests pass:

```
----------------------------------------------------------------------
Ran 169 tests in 1.608s

OK
```

When I run `xmlsec.initialize()` in the Python shell, it works fine with no stalling.

**Comment by pitbulk** [comment]
weird :(

**Comment by kgodey** [comment]
@pitbulk so is this a bug with python-saml?

**Comment by kgodey** [comment]
Thanks! The previous response I posted had those two validation errors I mentioned, but but I've also uploaded a SAMLResponse that was validating correctly here: https://gist.github.com/kgodey/f55effa3ab3852f2653c 

I hope that helps with the debugging.

**Comment by pitbulk** [comment]
Can you provide the SAMLResponse encoded?

**Comment by kgodey** [comment]
@pitbulk Here's the private key (it's a development key and not used for anything else)

```
MIICXgIBAAKBgQCXM75B84nKjooRgRQKJNFlNTNBeZd9LkWH0e4zvhSf9KxEAsYI
0nvWoEiU8vD2o72mz8Vy0KpWeP09oyjdQ7tnSq/h7Ee0ds0vOGe8HMClXChTZ3bl
gSlqqlF+y+hZFuq3wfBWyM/C4GOLNxRi2w5aVHTzIDvLrPlTNegHtf/JowIDAQAB
AoGBAItN5NAmbKDuSk5uOeROn407QonkWKnAY9cKlwec7KuiZMQUOhgOtIG9EqII
YfEaUrTJYAS0MvuQZODQ3eldad4J7dYNs6OGq0jGRw9FZ5J1kBHj8+/QU7q2hMZv
QI80kClRVijHosGs91w4IXq/IIe54yUgvpNzsN8vM9O/CO6hAkEAxWBZWIbPWUl3
e4NO5gX2jj2wEc7i9GYaYc194JCIqikHCmLpMZCDwit2aAQZelXLHYIUF1ZswuYk
tbrN2lFeRwJBAMQcgM/Q5jmNn9GVUnM6UZvB3sstG3HmwzTlXNafgeppEfjUsumj
GNvwGeYWS4MZtPkAV09uSDJAjWvdGRSpW8UCQHM61c6GHcWdy4CzXzuRXakbQJCU
/RD8DwjsREH3f6IAA9k/d671FMcmQqFlS06NieB3Ua1ySlraq7HhFk8P0/8CQQCB
Tz4MSXUUq/KekjQccG7RIiNSmvqGvx8l6LqvdduHAiLsjOsvrPA+TXH2SeselbvD
l9r6MACAyhm17sKT4hv1AkEAll3xuT4vgUGb2EOLfqZ6LVNgezqfx88wVDZsMSju
XS/bRr/Xg6T7phWMXUxv9XJ9IEVn3m+tPIJ/0O3mocVXHw==
```

**Comment by kgodey** [comment]
And here's a second SAML response too, in case that helps: https://gist.github.com/kgodey/2557b3018710868348b2

**Comment by kgodey** [comment]
@pitbulk did that help at all?

**Comment by pitbulk** [comment]
I tried to decrypt that SAMLResponse https://gist.github.com/kgodey/2557b3018710868348b2 with the private key you posted. I was able to decrypt online, but got an error trying to decrypt using the python code.

**Comment by pitbulk** [comment]
I reported the issue here: https://github.com/mehcode/python-xmlsec/issues/22

**Comment by kgodey** [comment]
Thanks @pitbulk

**Comment by LarsMichelsen** [comment]
I also experience this issue. I tried to debug this within onelogin/saml2/utils.py starting with validate_sign(). The xmlsec.initialize() was fine, but once reached the second xmlsec.initialize() call which was in my case the request was stuck. After removing the second one, it was working as expected.

**Comment by alexlorenzi** [comment]
Hi @pitbulk - has there been any resolution of this issue? I'm experiencing the same problem ( xmlsec.initialize() hanging in validate_sign() ) ... Strangely this works fine if I run the site using the manage.py script. I only see the error when hosting the site in Apache.

My solution was to comment out the initialize call on lines 919 (in validate_sign) and 1037 (in validate_node_sign). 

Wondered if you could see any side-effects to doing this?

Thanks
Alex

**Comment by pitbulk** [comment]
Maybe a possible solution is to initiate it once when loading the utils.py file.

I never experience this issue.

**Comment by alexlorenzi** [comment]
I thought of that too. I don't know too much about the xmlsec lib, and don't know how it needs to be initialised. Or is there a method to check it's state and initialise if it hasn't been already. 
The fix I posted works for me, but is a hack. I'd prefer a real solution. If I find some time I'll try and implement a better one.
Thanks 
On 30 Jun 2016 6:29 p.m., Sixto Martin <notifications@github.com> wrote:Maybe a possible solution is to initiate it once when loading the utils.py file.

I never experience this issue.

**Comment by pitbulk** [comment]
Based on this file:
https://github.com/tachang/dm.xmlsec.binding/blob/cd63c63e51cfd08a05248bb62e4ac6b5e9044f94/dm/xmlsec/binding/tests.txt#L12

maybe we should just initialize after import it. Please if you have time test it and let me know if worked.

**Comment by alexlorenzi** [comment]
I updated the code to initialize after the import, but this didn't stop it hanging (although it hung at a different stage). I'm not really a python-dev, but after a quick Google, it seemed people use decorators to implement an execute-once behaviour. Therefore I wrapped the initialize call a method that used an execute once decorator. This seemed to solve the problem (all the tests still pass too)

```python
def run_once(f):
    def wrapper(*args, **kwargs):
        if not wrapper.has_run:
            wrapper.has_run = True
            return f(*args, **kwargs)
    wrapper.has_run = False
    return wrapper

@run_once
def xmlsec_initialize():
    xmlsec.initialize()

...

def validate_sign():
    ...
    xmlsec_initalize()
    ...
```

I'm happy to create a pull request for this code, but I'm sure you'd rather implement it in a neater way (like I said I'm not really a python-dev), either way, I've attached the patch so you can test it yourself.

[xmlsec.initialize.patch.txt](https://github.com/onelogin/python-saml/files/343216/xmlsec.initialize.patch.txt)

**Comment by pitbulk** [comment]
What do you think @lorenzogil ?

**Comment by lorenzogil** [comment]
@pitbulk it makes a lot of sense to avoid calling that initialize function twice. I think @alexlorenzi 's patch is worth to merge.

**Comment by pitbulk** [comment]
Finally solved with [149](https://github.com/onelogin/python-saml/pull/149) instead decorators
