### ISSUE TITLE
cert in authn request?

### ISSUE THREAD

**Issue by jimmyislive** [onelogin/python-saml#125]
Is it possible to include the x509 cert in the authn saml request ?

Right now it contains the parms SAMLRequest, Signature, RelayState

In the response from the IdP, the cert is included in the response so I was wondering if the same can be done for the request.

This would make life easier if we cycle SP certs on client end.

**Comment by pitbulk** [comment]
I think that the SAML protocol does not support it.

In SAML entities (IdPs and SPs) publish their metadata, accessing those xml, is how entities discover endpoints and certs.

**Comment by jimmyislive** [comment]
Would u have a reference?

Do IdPs typically access this metadata dynamically  and get the x509 cert on the fly? I guess that would also work for me. Though if the IdP downloads this metadata once, then they would not know when I cycle the certs.

**Comment by pitbulk** [comment]
In federations, each entities used to know where the trusted entities publish their metadata, so they are able to update this data time to time.
Take a look for example how the [EduGAIN federation works](http://www.ukfederation.org.uk/content/Documents/EduGAINParticipation#mdx)
