### ISSUE TITLE
User defined variables

### ISSUE THREAD

**Issue by sandeep048** [onelogin/python-saml#127]
Can we use user defined variables either created manually or sourced from environment in the settings file. This setting will be very useful to dynamically assign variables like <sp_domain> based on staging, production, dev environments etc.
Example from Packer Documentation: https://www.packer.io/docs/templates/user-variables.html

**Comment by pitbulk** [comment]
Yes, you should be able to add to the settings any parameter or extend the provided classes.

**Comment by sandeep048** [comment]
Can you kindly give me an example.

**Comment by pitbulk** [comment]
The settings var is a dict (json), so you can add any parameter that you need and retrieve then later, directly reading the array or extend the OneLogin_Saml2_Settings class and modify the [__load_settings_from_dict](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/settings.py#L185) method to support the extra parameter that you require.

**Comment by sandeep048** [comment]
Perfect makes sense, thank you.
It would be nice if you guys can support env parameter directly from the JSON file itself.
