### ISSUE TITLE
Changes to SAML settings to support WS-Federation/ Active Directory

### ISSUE THREAD

**Issue by sandeep048** [onelogin/python-saml#130]
I would like to find out if python-saml library works out of the box without any changes with the Microsoft STS(Security Token Service).

I propose the following patch to this library which uses additional flags to the SAML settings file.
Pull Request: https://github.com/onelogin/python-saml/pull/129. Kindly review this diff. Also if there is a simpler/better way of doing it please let us know.

Thanks & Regards,
Sandeep

**Comment by pitbulk** [comment]
I already closed the [PR 126](https://github.com/onelogin/python-saml/pull/126) where I commented to you that python-saml is able to work out of the box, with the right settings with ADFS.
