### ISSUE TITLE
The default NameID settings in the demo applications seem to be incorrect

### ISSUE THREAD

**Issue by nickrmc83** [onelogin/python-saml#134]
The default NameID settings in the demo applications seem to be incorrect. They are set by default to be:
"NameIDFormat" : "urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"

urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified is not defined in section 8 of http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf. Perhaps the default should be urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified?

The result of the above is that some IdP service fail. An example of this is Shibboleth.

**Comment by pitbulk** [comment]
Hi, Thanks for contributing.

In line 2134 appears urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified and maybe that confused me.

This was defined in the  errata:
https://docs.oasis-open.org/security/saml/v2.0/sstc-saml-errata-2.0-cd-04.html

I will fix it asap ;)

**Comment by pitbulk** [comment]
Fixed: 431e50475875dcdfe4833911dbff15c7b71c9b34
