### ISSUE TITLE
Proccess locks when use OneLogin_Saml2_Response.get_nameid()

### ISSUE THREAD

**Issue by sariogonfer** [onelogin/python-saml#140]
Hi everyone, 

First, i would like to apologise for my english. My application use this library to authenticate the users. Sometimes, OneLogin_Saml2_Response.get_nameid() function is blocked and doesn't return anything. Its strange because if i debug with pdb, and run this function with the same parameters, usually the function works good, but sometimes not. In order to avoid this situation, i use a timeout of 3 seconds. If function doesn't respond, i run it again. Its strage becouse if first running fail, the second one works. There is some reason for this??

P.D.: I use Django framework too.

Thanks,

**Comment by pitbulk** [comment]
I don't see any reason.

Can you remove the timeout and instead set 2 new logs entries?:
1. To record the SAMLResponse to be processed (in order to check that a NameId element exists
2. In order to see when method succeeded or not

**Comment by pitbulk** [comment]
@sariogonfer, any progress with the debug process?
