### ISSUE TITLE
Support to configure the DigestMethod attribute of a signed AuthnRequest

### ISSUE THREAD

**Issue by gsvitak** [onelogin/python-saml#147]
Hello,

Does the toolkit currently support the ability to configure the DigestMethod of a signed request? I am trying to use the library with an HTTP-Post SSO binding for an SP initiated flow.  

It appears that the only current support is sha1 and it is hard coded.

`<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>`

I would love to be able to configure the security settings json for DigestMethod similar to the Signature settings so we could allow for the following

`<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>`

Any ideas on how to make this work? I am willing to work on PR but not sure how much work it would be or if the PR would be useful to others.

Thanks
Greg

**Comment by pitbulk** [comment]
As mentioned on [146](https://github.com/onelogin/python-saml/issues/146) there is no support for HTTP-Post SSO binding for an SP initiated flow. 

Currently the HTTP-Redirect method supports DSA_SHA1, RSA_SHA1, RSA_SHA256, RSA_SHA384 and RSA_SHA512 configured with the [signatureAlgorithm parameter](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/settings.py#L280)
