### ISSUE TITLE
Support for embedded signatures in LogoutRequest

### ISSUE THREAD

**Issue by sbc100** [onelogin/python-saml#153]
As far as I can tell there is no support for embedded signature.

In the ruby-saml library there is an `embed_sign` option that does this.

**Comment by pitbulk** [comment]
There is no official support for LogoutRequest on HTTP-POST binding

You can extend the classes on the toolkit and implement it using the [add_sign](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L768) method on the generated Logoutrequest retrieved from the [get_request](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/logout_request.py#L119) and executing a 
POST instead a [redirect](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L356)

**Comment by sbc100** [comment]
Thanks for the response.   I will try using add_sign to implement this. 

As you you saying the embedding signatures is related to the POST vs redirect?  From my brief inspection of ruby-saml it looks like `embed_sign` can be used with either redirect or POST.  i.e. are you sure these two choices are not orthogonal?

In my particular case I'm trying to write a python SP that talks to an IdP based on https://github.com/sportngin/saml_idp which seems to require embedded signatures even when logout is sent via redirect.

**Comment by pitbulk** [comment]
When using the Redirect binding you put the signature in the URL query parameters

```
3.4.4.1 DEFLATE Encoding

SAML protocol messages can be encoded into a URL via the DEFLATE compression method 
(see[RFC1951]). In such an encoding, the following procedure should be applied to the original SAML protocol message's XML serialization:
1.
Any signature on the SAML protocol message, including the <ds:Signature> XML element itself,
MUST be removed. Note that if the content of the message includes another signature, such as a
signed SAML assertion, this embedded signature is not removed. However, the length of such a
message after encoding essentially precludes using this mechanism. Thus SAML protocol messages that contain signed content SHOULD NOT be encoded using this mechanism.
```

Reference:
http://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf

**Comment by pitbulk** [comment]
I'm also the current maintainer of the ruby-saml gem, but the ``embed_sign`` was something implemented before I arrived and is only a trick to let the developers to support the HTTP-POST binding.
