### ISSUE TITLE
isodate dep

### ISSUE THREAD

**Issue by papachoco** [onelogin/python-saml#154]
Hi,

Is there any way we can relax the dependency on isodate. Perhaps to isodate >=0.5.0

Thanks

Carlos

**Comment by papachoco** [comment]
FWIW isodate 0.5.0 is from 2014-02-23

**Comment by pitbulk** [comment]
Sure

**Comment by pitbulk** [comment]
https://github.com/onelogin/python-saml/commit/b1d20e7f855c567be37408478c5cc25ffa0717d2

**Comment by papachoco** [comment]
Thanks a lot. Would there be an ETA for a new release?

**Comment by pitbulk** [comment]
not yet, but I think in a couple of weeks I can do a new release.

**Comment by papachoco** [comment]
Thanks
