### ISSUE TITLE
RequestedAttribute settings not processed correctly in metadata 

### ISSUE THREAD

**Issue by rahmanoof** [onelogin/python-saml#157]
HI ,
I am trying to generate metadata file with attributeConsumingService settings :

"attributeConsumingService": {
      "serviceName": "user type",
      "requestedAttributes": [
        {
          "name": "userType",
          "isRequired": false,
          "nameFormat": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
          "attributeValue": ["userType","admin"]
        }
      ]
    },

I get the following error:
Exception Value:	
unsupported format character '<' (0x3c) at index 104
Exception Location:	/usr/local/lib/python2.7/dist-packages/onelogin/saml2/metadata.py in builder, line 103

and if I set 
"attributeValue": "admin"

I get the following error:

Invalid dict settings at the file: sp_attributeConsumingService_requestedAttributes_attributeValue_type_invalid
Django Version:	1.8.6
Exception Type:	OneLogin_Saml2_Error
Exception Value:	
Invalid dict settings at the file: sp_attributeConsumingService_requestedAttributes_attributeValue_type_invalid

Is this issue on my settings ? 
thanks for y our time.

**Comment by pitbulk** [comment]
There is a bug. As you can see on the standard, the [md:RequestedAttribute](http://www.datypic.com/sc/saml2/e-md_RequestedAttribute.html) is able to contain multiple saml:AttributeValue.

So in the validator, we check that the "attributeValue" of the settings to be a list.

The problem is that the [README/Setting file](https://github.com/onelogin/python-saml#settings) describes the possible value of the attributeValue as a string. Also the metadata [builder consider the attributeValue as a string](https://github.com/onelogin/python-saml/blob/e473deadbdfff5c6edbece35485a166f27269f23/src/onelogin/saml2/metadata.py#L103)

Can you set that setting:
```
        "attributeConsumingService": {
                "ServiceName": "SP test",
                "serviceDescription": "Test Service",
                "requestedAttributes": [
                    {
                        "name": "userType",
                        "isRequired": false,
                        "nameFormat": "urn:oasis:names:tc:SAML:2.0:attrname-format:basic",
                        "attributeValue": ["admin"]
                    }
                ]
        },
```

and edit the src/onelogin/saml2/metadata.py file on line [Line98](https://github.com/onelogin/python-saml/blob/e473deadbdfff5c6edbece35485a166f27269f23/src/onelogin/saml2/metadata.py#L98)

```
            requested_attribute_data = []
            for req_attribs in sp['attributeConsumingService']['requestedAttributes']:
                req_attr_nameformat_str = req_attr_friendlyname_str = req_attr_isrequired_str = ''
                req_attr_aux_str = ' \>'

                if 'nameFormat' in req_attribs.keys() and req_attribs['nameFormat']:
                    req_attr_nameformat_str = " NameFormat=\"%s\"" % req_attribs['nameFormat']
                if 'friendlyName' in req_attribs.keys() and req_attribs['friendlyName']:
                    req_attr_nameformat_str = " FriendlyName=\"%s\"" % req_attribs['friendlyName']
                if 'isRequired' in req_attribs.keys() and req_attribs['isRequired']:
                    req_attr_isrequired_str = " isRequired=\"%s\"" % req_attribs['isRequired']

                if 'attributeValue' in req_attribs.keys() and req_attribs['attributeValue']:
                    req_attr_aux_str = ""
                    for attrValue in req_attribs['attributeValue']:
                        req_attr_aux_str += """
            <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion>%(attributeValue)</saml:AttributeValue>""" % \
                            {
                                'attributeValue': attrValue
                            }

                requested_attribute = """            <md:RequestedAttribute Name="%(req_attr_name)s"%(req_attr_nameformat_str)s%(req_attr_isrequired_str)s%>(req_attr_aux_str)s</md:RequestedAttribute>""" % \
                    {
                        'req_attr_name': req_attribs['name'],
                        'req_attr_nameformat_str': req_attr_nameformat_str,
                        'req_attr_friendlyname_str': req_attr_friendlyname_str,
                        'req_attr_isrequired_str': req_attr_isrequired_str,
                        'req_attr_aux_str': req_attr_aux_str
                    }
```

Here is the final file:  https://gist.github.com/pitbulk/a79774069283b0dc060a22104c7b9ebe

**Comment by pitbulk** [comment]
Fixed https://github.com/onelogin/python-saml/commit/9289d2632dbcadcefa25bda9c981e39a67f28b2c
