### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by scottwoodall** [onelogin/python-saml#161]
When there are multiple X509 certificates in the IdP the following exception gets thrown:

`Signature validation failed. SAML Response rejected`

If I change the index value from 0 to 1, it works: `idp_x509_cert = cert_nodes[0].text` [1]

Even if the parsing of the IdP XML handled multiple `cert_nodes`, I don't think the validation of the certificates in `def is_valid()` [2] handles this use case.

While I am new to SAML; it's my understanding that multiple X509 certificates is valid so one can deprecate old certificates while simultaneously include the new certificate.

Thoughts?

[1] https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/idp_metadata_parser.py#L141

[2] https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L215

**Comment by pitbulk** [comment]
idp_metadata_parser.py is used in order to parse IdP metadata, With the extracted data you can try to set up the toolkit settings.

Currently the python toolkit only allow to define 1 unique certificate for the Identity Provider.
Support certificate-rollover in in the roadmap.

**Comment by scottwoodall** [comment]
Was this resolved or is it being marked as "won't fix"?

**Comment by pitbulk** [comment]
I will implement a similar solution than the one recently implemented on php-saml:
https://github.com/onelogin/php-saml/pull/206
