### ISSUE TITLE
attribute 'isRequired': 'True' is not a valid value of the atomic type 'xs:boolean'

### ISSUE THREAD

**Issue by pwh88** [onelogin/python-saml#167]
Original issue #136 

In v2.2.0 I'm receiving this error when specifying the `isRequired` the issue was fixed in v2.1.9 but somehow seems that it got lost.

 `attribute 'isRequired': 'True' is not a valid value of the atomic type 'xs:boolean'`

**Comment by pitbulk** [comment]
It seems I accidentally reverted #136 change, applied it again.
