### ISSUE TITLE
Signatures are not verified by default, even in 'strict' mode.

### ISSUE THREAD

**Issue by jgehrcke** [onelogin/python-saml#168]
That is what the README says about "security":

> **Security warning**
In production, the strict parameter MUST be set as "true". Otherwise your environment is not secure and will be exposed to attacks.

That _strongly_ suggests that you are good by setting `strict` to True.

Digging further in the README:

```
    // If strict is True, then the Python Toolkit will reject unsigned
    // or unencrypted messages if it expects them to be signed or encrypted.
    // Also it will reject the messages if the SAML standard is not strictly
    // followed. Destination, NameId, Conditions ... are validated too.
```

The important part really is
> will reject unsigned [...] messages **if it expects** them to be signed or encrypted.

The non-obvious bit is now that by default python-saml does not expect them to be signed:

```
        self.__security.setdefault('wantAssertionsSigned', False)
```
(https://github.com/onelogin/python-saml/blob/54e5be1d8bb7f769c09e5de6b9f05ad6b6fe7e51/src/onelogin/saml2/settings.py#L271)

Effectively, it is very likely to happen that people read the documentation and assume that enabling strict mode is sufficient for a secure deployment. A the same time, their SAML SP will accept arbitrary assertions, i.e assertions can easily be forged.

I have seen python-saml deployments that do not verify assertion signatures, where they really better should have.

I think 
* the documentation must be _much_ more clear on the fact that the defaults are _insecure_ or
* the default should change

**Comment by pitbulk** [comment]
The [process_signed_elements](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L441) method is executed on the is_valid method independent of the value of the strict mode. This method checks that at least there is 1 signature on the response or in the assertion.

[Later](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L219) and also outside the strict mode logic, we check again if there is a signature on the response or in the assertion and we validate it.

So we don't consider valid an invalid SAMLResponse (with no signature).
Enabling strict mode is sufficient for a secure deployment

The wantAssertionsSigned or the wantMessagesSigned settings parameter are specific requirements to be set on the Service Provider to require from the IdP an Assertion signed, or a Message signed. 
In the same way a SP could require from the IdP an encrypted NameID with the wantNameIdEncrypted
And are useful to invalidate valid SAMLResponses that not pass the security requirements of the SP.
Those parameters are ignored if 'strict' mode is off. 

'strict' mode off not only ignore those extra security requirements, also skip SAML validations like
InResponseTo, Conditions, timestamps, destination, audience, issuers, session expiration, SubjectConfirmation...  that why MUST be enabled on production environments.

**Comment by jgehrcke** [comment]
Thanks for your response. What you describe sounds convincing. I should have raised my concerns much earlier, with the facts around my specific test case fresh on my mind. Background: did some thorough testing earlier the year with python3-saml 1.1.4 and coincidentally found a case with strict mode enabled where a SAMLResponse was validated which should not have, and explicitly setting `wantAssertionsSigned` to `True` properly invalidated the response -- which I have then done on the corresponding production systems. Now I don't have this test case readily available, and I know it is required before proceeding in this discussion makes sense.

I see that various relevant code paths have changed in the 1.2.0 release. I'll try looking into providing an MWE so that we can proceed, and of course I'd be happy to find that my observations from earlier in the year are invalid as of today.

**Comment by pitbulk** [comment]
On python3-saml 1.1.4 there was a [test](https://github.com/onelogin/python3-saml/blob/v1.1.4/tests/src/OneLogin/saml2_tests/response_test.py#L1036) to check that unsigned response (with rest of elements valid) were rejected, independent o the strict mode value.

On 1.2.0 we improved the process of validating signatures avoiding a specific signature wrapping attack as documented on the [warning section](https://github.com/onelogin/python3-saml#warning).

If you find a case where the toolkit fails, please share with us (maybe by mail or by [OL tool](https://www.onelogin.com/security) to prevent others to use any possible bug), as you can see our toolkits are alive and we keep improving them day by day.
