### ISSUE TITLE
Improper signature method

### ISSUE THREAD

**Issue by Heilage** [onelogin/python-saml#169]
I'm trying to set up a connection using this library, but for some reason I can't initiate or assert a login.

On the ACS endpoint, I only get the following error:
`Error: improper signature algorithm`

Which appears to be called by:
`File "/opt/dev/unicornis/unicore/unicore/saml/views.py", line 97, in authentication
    return HttpResponseRedirect(auth.login(return_to=return_to, force_authn=True))
  File "/opt/dev/virtualenv/unicore/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 304, in login
    parameters['Signature'] = self.build_request_signature(saml_request, parameters['RelayState'], security['signatureAlgorithm'])
  File "/opt/dev/virtualenv/unicore/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 394, in build_request_signature
    return self.__build_signature(saml_request, relay_state, 'SAMLRequest', sign_algorithm)
  File "/opt/dev/virtualenv/unicore/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 458, in __build_signature
    signature = dsig_ctx.signBinary(str(msg), sign_algorithm_transform)
  File "_xmlsec.pyx", line 383, in dm.xmlsec.binding._xmlsec.DSigCtx.signBinary (src/_xmlsec.c:5440)
    
  File "_xmlsec.pyx", line 413, in dm.xmlsec.binding._xmlsec.DSigCtx._binary (src/_xmlsec.c:5801)`

I have set up a connector and configured it, with help from the tutorial. The weird thing is, the last time I set this up, with the same settings, it worked just fine. I just moved my code to a different application and updated the URLs and associated settings. I have of course not changed anything regarding the signature settings, so I don't understand why this error is thrown.

**Comment by pitbulk** [comment]
What python-saml version are you using?

The call to the login method is not executed on the ACS endpoint, instead on the view that start the SP-initiated SSO flow.

Based on the trace, it seems that there is a problem with the value of signatureAlgorithm.
This is a [parameter from the advanced_settings.py](https://github.com/onelogin/python-saml/blob/master/demo-django/saml/advanced_settings.json#L13) and [by default set to 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/settings.py#L281) when not provided any value on settings.

Can you add a breakpoint in order to check what value contains the security['signatureAlgorithm'] parameter?

**Comment by Heilage** [comment]
> What python-saml version are you using?

2.2.0 according to PIP

> The call to the login method is not executed on the ACS endpoint, instead on the view that start the SP-initiated SSO flow.

You are of course correct, sorry about that. 

I added a breakpoint on auth.py:302, and security["signatureAlgorithm"] is set to the expected. 

`{u'wantNameIdEncrypted': False, u'authnRequestsSigned': True, u'logoutResponseSigned': False, u'wantMessagesSigned': False, 'metadataCacheDuration': None, 'requestedAuthnContext': True, u'logoutRequestSigned': True, 'wantAttributeStatement': True, u'signMetadata': False, 'metadataValidUntil': None, u'wantAssertionsSigned': True, u'wantNameId': True, 'wantAssertionsEncrypted': False, u'nameIdEncrypted': False, u'signatureAlgorithm': u'http://www.w3.org/2000/09/xmldsig#rsa-sha1'}`

**Comment by pitbulk** [comment]
'http://www.w3.org/2000/09/xmldsig#rsa-sha1' is a valid value.

Can you put another breakpoint at the [__build_signature]method(https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py) before the
```
signature = dsig_ctx.signBinary(str(msg), sign_algorithm_transform)
```
and check the value of sign_algorithm_transform?

**Comment by Heilage** [comment]
I have `sign_agorithm_transform_map`, I'm assuming that is what you are referring to. 

`{'http://www.w3.org/2000/09/xmldsig#rsa-sha1': <dm.xmlsec.binding._xmlsec.Transform object at 0x7f1d870e5060>, 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha512': <dm.xmlsec.binding._xmlsec.Transform object at 0x7f1d870e5288>, 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha384': <dm.xmlsec.binding._xmlsec.Transform object at 0x7f1d870e5030>, 'http://www.w3.org/2000/09/xmld/sig#dsa-sha1': <dm.xmlsec.binding._xmlsec.Transform object at 0x7f1d8c3a9db0>, 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256': <dm.xmlsec.binding._xmlsec.Transform object at 0x7f1d870e5438>}`

Interestingly, these Transform objects seem to coincide with a bug we've been having. When running python-saml stock, our application immidiately segfaults, due to some kind of bug in `dm.xmlsec.binding.__init.py__`. We have to comment out `transformByHref = dict((t.href, t) for t in transforms)` to get it to run at all. This has worked previously, but who knows what has changed since the last time I tested this. Does this sound familiar to you?

**Comment by pitbulk** [comment]
> We have to comment out transformByHref = dict((t.href, t) for t in transforms) to get it to run at all. 
Then you broke xmlsec.

I recommend you to install a fresh version of dm.xmlsec.binding.

And if you experience issues, review this thread:
https://github.com/onelogin/python-saml/issues/30

**Comment by Heilage** [comment]
Unfortunately, we are stuck on Python 2.7 for a while longer. 

However, reading that thread closely gave me a solution. I might write a comment in it to clear any confusion, because I had to piece together the solution from quite a few posts. 

I'm closing this issue, even though I'm having authentication problems. Those are a separate issue.

**Comment by pitbulk** [comment]
Glad you solved the issue with dm.xmlsec.binding

P.S Notice that python3-saml is compatible with Python 2.7 and Python 3.X
