### ISSUE TITLE
Error -3 while decompressing data: invalid code lengths set

### ISSUE THREAD

**Issue by tomalessi** [onelogin/python-saml#170]
I am seeing this error on logout using SLO while calling:

```
dscb = lambda: request.session.flush()
auth.process_slo(delete_session_cb=dscb)
```

Seems to be a problem with zlib but I've confirmed that the SAML Response from the IDP is correct when calling the SP single logout service.

Could this be a problem with base64 encoding, or signature?

**Comment by pitbulk** [comment]
Can you try to decode the Logout Response here:
https://www.samltool.com/decode.php

**Comment by tomalessi** [comment]
Thanks, that's helpful.  Looks like the SAML response is not being compressed before base64 encoding.  We're going to try adding that step to see if that resolves the problem.

**Comment by pitbulk** [comment]
any luck?
