### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by athal7** [onelogin/python-saml#174]
So that I can benefit from https://github.com/onelogin/python-saml/commit/54e5be1d8bb7f769c09e5de6b9f05ad6b6fe7e51

Thank you!

**Comment by pitbulk** [comment]
I will release a new version next week, I want to add some pending features.

**Comment by athal7** [comment]
Sounds good, thanks.

**Comment by athal7** [comment]
@pitbulk any update on a new release?
