### ISSUE TITLE
Cent os: segmentation fault Error

### ISSUE THREAD

**Issue by yesdeepakverma** [onelogin/python-saml#178]
from onelogin.saml2.utils import OneLogin_Saml2_Utils
above import is giving segmention fault error in cent os machine.
Please look into this ASAP.

**Comment by yesdeepakverma** [comment]
I am using above import to sign my saml xml.
OneLogin_Saml2_Utils.add_sign(response, open(key).read(), open(cert).read())

**Comment by pitbulk** [comment]
Can you provide versions and the error trace?

**Comment by yesdeepakverma** [comment]
https://github.com/4teamwork/ftw.saml2auth/issues/3, this patch solved my problem.
