### ISSUE TITLE
Issuer of the Response seems optional in the saml 2 spec

### ISSUE THREAD

**Issue by jthiard** [onelogin/python-saml#183]
Hi,

I am building a SP for an IDP wich provides no `<saml:Issuer>` in the response (but a valid `<Issuer>` is given in the assertion).

This seems to be valid according the saml core spec found here https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf section 3.2.2

> `<saml:Issuer>` **[Optional]**
> Identifies the entity that generated the response message. (For more information on this element, see Section  2.2.5.)

The `OneLogin_Saml2_Response` does not validate this response : https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L377

I dont know how to workaround that without monkeypatching or some copy pasta and proxy magic

So here my question: will a pull request for a new setting allowing no issuer in the response be accepted ? Or is there a better way to work around this issue ?

Thanks

**Comment by pitbulk** [comment]
You are right, the Issuer on Response is optional.
Fixed at: https://github.com/onelogin/python-saml/commit/7e4d502c4b64ac6075577197a0096de89fb1ad01

**Comment by jthiard** [comment]
Thanks!
I just made a pull request to backport this commit on the python3 version.
see https://github.com/onelogin/python3-saml/pull/49
