### ISSUE TITLE
Does python-saml support Service Discovery?

### ISSUE THREAD

**Issue by ddriddle** [onelogin/python-saml#192]
Does python-saml support the SAML Discovery Service Protocol? If not is it on the roadmap? Are there any modules that work with python-saml to support DS?

**Comment by pitbulk** [comment]
Hi,

is not supported and is not on the roadmap.

There is an [idp_metadata_parser](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/idp_metadata_parser.py) file where there are methods to retrieve metadata from urls and inject it in the settings.
