### ISSUE TITLE
Unsigned response rejected even when "strict" is false

### ISSUE THREAD

**Issue by zshauli** [onelogin/python-saml#193]
Unsigned SAML responses are rejected with the message "No Signature found. SAML Response rejected" even when setting "strict", "wantMessagesSigned" and "wantAssertionsSigned" to "false".

**Comment by pitbulk** [comment]
wantMessagesSigned and wantAssertionsSigned are specific flags when the SP expects an specific signed element.

SAML standard requires at least the Assertion or the whole message to be signed, otherwise, if there is no Signature, there is no way to verify that the IdP generated the message.
