### ISSUE TITLE
Saml an ADFS 3.0

### ISSUE THREAD

**Issue by CMLL** [onelogin/python-saml#198]
I built an SDP with using python-saml for and tested it correctly with Google and SimpleSAML without a problem but I'm having issues when integrating with ADFS 3.0. I'm using a single virtual machine as a dev/testing environment and got my site to send the login request succesfully, but am getting a general error message on the page. 
![image](https://cloud.githubusercontent.com/assets/3720126/26462489/a36e1720-4146-11e7-92d2-1869a0ca81f5.png)

Looking at the ADFS logs I see this event pop up as an error.
![image](https://cloud.githubusercontent.com/assets/3720126/26462513/bdcb7c5c-4146-11e7-8855-d23aa92c8caf.png)

Which leads me to believe that my relaying party is badly configured. What should be going in the relaying party identifiers in ADFS part? And should the SP configuration needs anything special to handle this field?
![image](https://cloud.githubusercontent.com/assets/3720126/26462573/f6bc444c-4146-11e7-864b-4ee7bfca74b2.png)

Thanks in advance for any help

**Comment by pitbulk** [comment]
I'm not an ADFS expert, sorry don't have a reply for you. That screenshot that you shared seems ok to me.

**Comment by CMLL** [comment]
Thanks anyway, I'm going to try looking for solutions and report back on what I found, in case somebody else runs into this issue.

**Comment by CMLL** [comment]
Well, found the solution to this case. Was a misconfiguration in my part. The identifier was different from that one that came with the request. Doesn't seem to be but I copy pasted the url as the identifier and it worked.
