### ISSUE TITLE
metadata for sp does not showup

### ISSUE THREAD

**Issue by aasifalam** [onelogin/python-saml#206]
New to using the saml toolkit. I just ran the demo-flask when I give this in my browser
http://localhost:8000/metadata/
I get "invalid_xml"

at the console where i have run the server I see this error:

Element '{http://www.w3.org/2000/09/xmldsig#}X509Certificate': 'sp.crt' is not a valid value of the atomic type 'xs:base64Binary'.
127.0.0.1 - - [26/Jul/2017 00:35:26] "GET /metadata/ HTTP/1.1" 500 -

I have created sp.crt and sp.key using openssl as given in the documentation.

Thanks
Asif

**Comment by pitbulk** [comment]
If you place it on the json setting file, you need to set the value, not the name of the file.

Otherwise, provide the sp.crt and sp.key on the [certs folder](https://github.com/onelogin/python-saml/tree/master/demo-flask/saml/certs) and set nothing on the json setting file.

**Comment by aasifalam** [comment]
Got it..missed it since I was only looking at the demo-flask. 
thanks a ton

Asif
