### ISSUE TITLE
Using get_last_request_id

### ISSUE THREAD

**Issue by aasifalam** [onelogin/python-saml#210]
I am bit confused as how to get this Id. 
I tried getting the value in demo-flash-index.py. I am see a None value
Each time I tried getting with sso and logout a new request 'auth' object is created.  Perhaps that is why the ID value is None ?

Also looking at your implementation the ID value is stored in  auth.login() call. 
But auth.login() we never return to in the client

So how the client should get the ID ?

Thanks
Asif

**Comment by pitbulk** [comment]
The [login method returns](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L319) the IdP SSO URL + SAMLRequest (+ RelayState)

If you check the flask demo, in the [SP-initiaited SSO section](https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L48-L49) instead
```
return redirect(auth.login())
```
you can execute:
```
target = auth.login()
request_id = auth.get_last_request_id()
# do whatever you want with the id (store in session, store in database)
return redirect(target)
```

**Comment by aasifalam** [comment]
thanks it worked.
I see we have 'is_valid()' for the Auth Response class which the takes the ID to validate. But is it possible to also get this ID out from Authentication Response ?  

What I am trying to solve:
I want to send a number(identifier) in the request and get it back from IDP in the response message. I am using this number for downstream processing after user is authenticated.

**Comment by pitbulk** [comment]
https://github.com/onelogin/python-saml/commit/e70d0cd8f3c772ebd0b4606fd7ce02b5d3cce97d
