### ISSUE TITLE
Getting Encrypted Attributes. 

### ISSUE THREAD

**Issue by aasifalam** [onelogin/python-saml#211]
I am getting NameId , session expiration and session index in encrypted text. 
For example for NameId using get_nameid(), I get
"_30f31bb53183fe38824ffeeff5ffffc0d5f584905c"
For getting the session using get_session_expiration(), i get : "1505323156"
I am not using an SP certificate. My session is over https and app behind nginx.

Any suggestion if I am missing any config, I am using simplesamlphp as my IDP for testing.

**Comment by pitbulk** [comment]
That is not encrypted data.

"_30f31bb53183fe38824ffeeff5ffffc0d5f584905c" is an opaque identifier sent by the IdP, if the IdP support NameIdFormat = EmailAddress, configure your SP settings with that NameId and you will retrieve user email instead the opaque value.

1505323156 is a valid datetime format value, is expressed as timestamp
You can
```
from datetime import datetime
datetime.fromtimestamp(1505323156)
```
to get a datetime object.
