### ISSUE TITLE
AzureAD authnmethodsreferences (WindowsIntegrated)

### ISSUE THREAD

**Issue by slecrenski** [onelogin/python-saml#212]
Is there a way to add additional authnmethodreferences besides Password, ProtectedTransport in the settings.yaml configuration file?

http://schemas.microsoft.com/claims/authnmethodsreferences 	
urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport

Authentication method 'WindowsIntegrated' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'

**Comment by pitbulk** [comment]
Yes, 

In the [advanced settings](https://github.com/onelogin/python-saml#settings), set:
` `` 
"requestedAuthnContext": [
    'urn:oasis:names:tc:SAML:2.0:ac:classes:Password',
    'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
    'urn:federation:authentication:windows'
]
```

**Comment by slecrenski** [comment]
When I add this configuration under security I'm getting "No JSON object could be decoded"

/usr/lib/python2.7/site-packages/onelogin/saml2/settings.py in __init__, line 102

"requestedAuthnContext": ['urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport','urn:federation:authentication:windows']


"requestedAuthnContext": "('','','')" results in a saml2 protocol error but it at least parses the json.

I see this in the advanced settings documentation.

 // Authentication context.
        // Set to false and no AuthContext will be sent in the AuthNRequest,
        // Set true or don't present this parameter and you will get an AuthContext 'exact' 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
        // Set an array with the possible auth context values: array ('urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:X509'),
        "requestedAuthnContext": true,
        // Allows the authn comparison parameter to be set, defaults to 'exact' if the setting is not present.
        "requestedAuthnContextComparison": "exact",

**Comment by slecrenski** [comment]
SSO works when I only set "requestedAuthnContext": false tho.

**Comment by pitbulk** [comment]
Maybe you missed the final comma...if you have more elements after the requestedAuthnContext.

"requestedAuthnContext": ['urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport','urn:federation:authentication:windows'],

**Comment by pitbulk** [comment]
Use a JSON online validator to verify your settings.

**Comment by slecrenski** [comment]
Putting it in double quotes seemed to work.  But now I get this when attempting the SSO

AADSTS90023: One AuthnContextClassRef or AuthnContextDeclRef entry is expected in RequestedAuthnContext.

**Comment by pitbulk** [comment]
Then set just one value..

```
"requestedAuthnContext": ["urn:federation:authentication:windows"]
```

**Comment by slecrenski** [comment]
That does seem to work.  Thanks.  I'll have to read up a bit on what the ramifications are.

Do you know offhand if it's possible to set a domain_hint/whr as described in this article?  

https://cloudblogs.microsoft.com/enterprisemobility/2015/02/11/using-azure-ad-to-land-users-on-their-custom-login-page-from-within-your-app/

**Comment by pitbulk** [comment]
Sorry, not an expert of ADFS..

I think it uses samlp:Scoping that is not supported by the toolkit.

**Comment by slecrenski** [comment]
I seemed to have figured out how to resolve it by simply adding a query string parameter to the end of the idp:singleSignOnService url.  aka ../.../saml2?whr={[domain}}.com
