### ISSUE TITLE
How do you pass in multiple NameID formats?

### ISSUE THREAD

**Issue by michaelperret** [onelogin/python-saml#213]
Our SP settings are currently as follows:

```
"sp": {
                "entityId": "%s/saml2/metadata" % team_host,
                "assertionConsumerService": {
                    "url": "%s/saml2/acs" % team_host,
                    "binding": constants.BINDING_HTTP_POST
                },
                "singleLogoutService": {
                    "url": "%s/saml2/sls" % team_host,
                    "binding": constants.BINDING_HTTP_REDIRECT
                },
                "NameIDFormat": [constants.NAMEID_PERSISTENT, constants.NAMEID_EMAIL_ADDRESS],
                "x509cert": SAML_SP_PUBLIC_KEY,
                "privateKey": SAML_SP_PRIVATE_KEY
            }
```

which for some reason, encodes like this:

`<md:NameIDFormat>['urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress']</md:NameIDFormat>`

causing the error 

```
Errors validating the metadata:

Element '{urn:oasis:names:tc:SAML:2.0:assertion}NameID', attribute 'Format': '['urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress']' is not a valid value of the atomic type 'xs:anyURI'.
Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd
```

According to https://stackoverflow.com/questions/25620820/saml-2-0-multiple-mdnameidformat-tag-in-service-provider-metadata passing multiple NameIDFormat fiedls should theoretically be valid from a protocol standpoint so I'm wondering if there is a different format for the settings dictionary which would cause this to parse correctly?

**Comment by pitbulk** [comment]
Is true that SPSSODescriptor accepts more than 1 NameIDFormat, but our settings only support 1 value.

The NameID Format of the serttings will be used on the [NameIDPolicy](http://www.datypic.com/sc/saml2/e-samlp_NameIDPolicy.html) of the [AuthnRequest](http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html), that only uses 1 Format.

**Comment by michaelperret** [comment]
I've managed to modify the saml2/metadata.py code to correctly parse the list format but it's still erroring with

```
Errors validating the metadata:

Element '{urn:oasis:names:tc:SAML:2.0:assertion}NameID', attribute 'Format': '['urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress']' is not a valid value of the atomic type 'xs:anyURI'.
Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd
```

even though the metadata now clearly lists both as individual fields:

```
         <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
         <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
```

Is there more I'd need to modify to get this working as expected?

Are there any plans to support this going forward? If not it'd be greatly appreciated if you could somehow list the limitations of the library as it took a few hours of trying and failing (which led to eventually opening this issue) somewhere in the documentation for the library.

**Comment by pitbulk** [comment]
why you don't simply use the NameId Format required by your app, or if you don't know or accept multiple, you set the unspecified value?

As I previously mentioned, settings only accept 1 NameID Format and there is no plan to accept multiple to be displayed on SP metadata.

**Comment by michaelperret** [comment]
> why you don't simply use the NameId Format required by your app, or if you don't know or accept multiple, you set the unspecified value?

While this would be ideal, we're dealing with a client's IDP setup which requires identifiers for _both_ persistent *and* email. 

I understand the weirdness of the request, but it's technically valid and as a library built around a specified protocol I'd expect that you're able to support the allowed variants of the protocol as well.

**Comment by michaelperret** [comment]
Trust me, I'm also not a fan of having to do this, but I've gone ahead and forked the branch and pushed up my code changes (can be seen here: https://github.com/onelogin/python-saml/compare/master...michaelperret:master ) but as I said before I'm still runinng into issues with the validation process. Could you possibly point me towards the validation process so I can make similar modifications to allow for this state please?

**Comment by pitbulk** [comment]
"we're dealing with a client's IDP setup which requires identifiers for both persistent and email."

That makes no sense. The IdP supports multiple NameId formats and you may choose one of them to be used on your SP.

If you want to offer more than 1 nameidformat on metadata, better create a new settings, because change that NameIdFormat from string to array will break toolkit since is used not only on the Metadata class.

Sorry but Im at mobile now, I will review your code and see what happening with your validation later.

**Comment by pitbulk** [comment]
You are validating the generated metadata with the wrong XSD.

You are using to validate "saml-schema-protocol-2.0.xsd" instead of "saml-schema-metadata-2.0.xsd".
But try to use the method that is designed to validate SP metadata: [validate_metadata](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/settings.py#L686)

Again, take in consideration the following:
```
The NameID Format value of the serttings right now is used to build the [NameIDPolicy](http://www.datypic.com/sc/saml2/e-samlp_NameIDPolicy.html) of the [AuthnRequest](http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html), that only uses 1 Format. In addition is used to build the SP Metadata.

If you plan to support multiple NameID Formats on your SP metadata, I recommend you to create a new setting parameter and use it instead the current NameIDFormat parameter, that will be only used to set what value will be used on the AuthNRequest parameter.
```

The main goal of the toolkit is to support a working SP implementation maintaining settings as simple as possible. If you want to use a SAML toolkit that cover all the possible scenarios, take a look at [pysaml2](https://github.com/rohe/pysaml2), otherwise, fork this current project and maintain it with the changes you need.

**Comment by michaelperret** [comment]
Thank you for the expanded response, I really appreciate the help here. I'm going to go ahead and close the ticket due to the lack of value for the rest of the open source community. Thanks again!
