### ISSUE TITLE
XML digital signature validation/verification using function "xmlSecDSigCtxVerify" on linux is failing

### ISSUE THREAD

**Issue by BhaskarShiv** [onelogin/python-saml#224]
XML digital signature validation/verification with function "xmlSecDSigCtxVerify" using a public key which is embedded in the xml license document on linux is failing. But validation is working absolutely fine on windows.

Below is the versions of libxml2 and xmlsec1 used

clprhel764-clpadmin > xmlsec1 --version
xmlsec1 1.2.19 (openssl)

clprhel764-clpadmin > rpm -qa | grep libxml2
libxml2-2.9.1-6.el7_2.3.x86_64
libxml2-python-2.9.1-6.el7_2.3.x86_64
clprhel764-clpadmin >

The validation is failing in the xmldsig.c at 
line : 680 with code "xmlSecAssert2(xmlSecPtrListGetSize(&(dsigCtx->signedInfoReferences)) == 0, -1);"
line : 547 and line 366 and so on

I have attached a piece of `code.`
[verify code.txt](https://github.com/onelogin/python-saml/files/1895188/verify.code.txt)

Below is the error I am getting during verification of the signature using public key.

clprhel764-clpadmin > ./ValidateLicenseFileSignature ../../data/signed.xml
func=xmlSecDSigCtxProcessSignedInfoNode:file=xmldsig.c:line=680:obj=unknown:subj=xmlSecPtrListGetSize(&(dsigCtx->signedInfoReferences)) == 0:error=100:assertion:
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=547:obj=unknown:subj=xmlSecDSigCtxProcessSignedInfoNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=366:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed:
func=xmlSecPtrListEmpty:file=list.c:line=150:obj=unknown:subj=list->data != NULL:error=100:assertion:
./ValidateLicenseFileSignature : elmlic_validate_signature() return status = -12.
./ValidateLicenseFileSignature : Invalid license keys - signature is not correct.
clprhel764-clpadmin >

Please help me fixing this issue which is lasting for many days. I'm facing the same problem on all Linux machines including suse, redhat and etc
Your help is highly appreciated

**Comment by BhaskarShiv** [comment]
Hello, can someone please help me on this issue.

**Comment by pitbulk** [comment]
Try execute a xmlsec validation directly with the xmlsec on the console command.
```xmlsec --verify --X509-skip-strict-checks --id-attr:ID Assertion --id-attr:ID Response  --trusted-pem cert.crt response.xml
```

**Comment by BhaskarShiv** [comment]
Upgrading the xmlsec1 and the dependent libraries (libxml2 and libcurl) with the latest versions compatible on red hat linux machine version 7, 64bit worked fine and i was able verify/validate xml digital signature validation.
