### ISSUE TITLE
Integrating python-saml with an ADFS IDP 

### ISSUE THREAD

**Issue by c0ntagi0us** [onelogin/python-saml#227]
On a previous post (https://github.com/onelogin/python-saml/issues/180) @pitbulk mentions 

> Remember to register SP's x509 certificate on the ADFS in order to let it validate the Signature of the AuthNRequest

I have added the SP's x509 certificate on the Trusted Root Certificate Authorities on the ADFS but the signature validation still fails when importing SP's metadata. (An error occurred during an attempt to read the federation metadata... Error ID6013) 

Online endpoint or offline xml file make no difference.

I am using self signed certs on the SP.

Other IDPs work without issues. (Onelogin, Azure etc)

("signMetadata": True)

Update: Using this tool to build metadata https://www.samltool.com/sp_metadata.php I don't get any errors.

Any tips/thoughts?

**Comment by pitbulk** [comment]
Try again with the latest release.

**Comment by c0ntagi0us** [comment]
It works! Thanks!
