### ISSUE TITLE
where can i get available smal2.0 idp servers

### ISSUE THREAD

**Issue by jesoonluo** [onelogin/python-saml#229]
some one can help me ? I'am try to use gluu or auth0, but does't understand those how to config.

**Comment by pitbulk** [comment]
And why don't use a free [OneLogin Developer Account](https://www.onelogin.com/developer-signup)?

After register at OneLogin, you can configure a [SAML Test Connector](https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector) and use it with your Service Provider.

Read more [here](https://developers.onelogin.com/saml/python).

**Comment by jesoonluo** [comment]
I have registered it but it only redirete to https://em.appatureinc.com/login?ReturnUrl=%2flogin-saml.ashx，and then I need that company account ? I don't konw how to control it in website. I have readed https://developers.onelogin.com/saml/python but don't understand too..

**Comment by jesoonluo** [comment]
I have run my-server with settings `{                                                                                                                                                 "strict": false,                                                                                                                              "debug": true,                                                                                                                                "sp": {                                                                                                                                           "entityId": "http://localhost:8000/metadata/",                                                                                                "assertionConsumerService": {                                                                                                                     "url": "http://localhost:8000/?acs"                                                                                                       },                                                                                                                                            "singleLogoutService": {                                                                                                                          "url": "http://localhost:8000/?sls"                                                                                                       },                                                                                                                                            "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"                                                                   },                                                                                                                                            "idp": {                                                                                                                                          "entityId": "https://app.onelogin.com/saml/metadata/780204",                                                                                  "singleSignOnService": {                                                                                                                          "url": "https://forceclouds-dev.onelogin.com/trust/saml2/http-post/sso/780204"                                                            },                                                                                                                                            "singleLogoutService": {                                                                                                                          "url": "https://forceclouds-dev.onelogin.com/trust/saml2/http-redirect/slo/780204"                                                        },                                                                                                                                            "x509cert": "MIICbDCCAdWgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBTMQswCQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTEVMBMGA1UECgwMT25lbG9naW4gSW5jM    }                                                                                                                                         }   `
but when i click login , it always redirect to this page  https://em.appatureinc.com/login?ReturnUrl=%2flogin-saml.ashx, and i don't konw what to do i needed to get attribute.

**Comment by pitbulk** [comment]
It should redirect you to OneLogin and then on the ACS URL configured on the connector 780204.
Can you use a browser debugger to see the flow? Can you review the settings of the connector? Can you verify that the settings you shared are really the one used by the toolkit?

**Comment by jesoonluo** [comment]
@pitbulk , i have get attribute success in my-server, I don't choose saml test connector in the second step for https://developers.onelogin.com/saml/python , that's why I didn't get the attribute. thanks so much , it helps me more!
