### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by namanrajbaid** [onelogin/python-saml#232]
Having issue with signature verification. I was able to verify response on https://www.samltool.com/validate_response.php. 

here is the setting.json
`{
    "strict": false,
    "debug": true,
    "sp": {
        "entityId": "https://10.5.126.60:9440",
        "assertionConsumerService": {
            "url": "https://10.5.126.60:9440/api/nutanix/v3/identity_providers/callback",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        "x509cert": "",
        "privateKey": ""
    },
    "idp": {
        "entityId": "http://www.okta.com/exke8xr05e34hTyEc0h7",
        "singleSignOnService": {
            "url": "https://dev-435978.oktapreview.com/app/nutanixdev435978_prism_1/exke8xr05e34hTyEc0h7/sso/saml",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "x509cert":"MIIDpDCCAoygAwIBAgIGAWIFBOW1MA0GCSqGSIb3DQEBCwUAMIGSMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxEzARBgNVBAMMCmRldi00MzU5NzgxHDAaBgkqhkiG9w0BCQEWDWluZm9Ab2t0YS5jb20wHhcNMTgwMzA4MDk0OTI5WhcNMjgwMzA4MDk1MDI5WjCBkjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDTALBgNVBAoMBE9rdGExFDASBgNVBAsMC1NTT1Byb3ZpZGVyMRMwEQYDVQQDDApkZXYtNDM1OTc4MRwwGgYJKoZIhvcNAQkBFg1pbmZvQG9rdGEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA30N09EBYwxwVQy4pZbyQwQtWTMCuow2YWWgy7qIt5eGIE+XXAXHf6tx/I8HF6YhHRAEEKA8DWADS+l3zh2K1unWHmaU9w0V1W4bkWFnGiU3id7hZO7P2tVNXpYaLiZBklZ9VQFrqjG30wCi356IhlMx5RxjZVTqCDMDYjWR7KfnpzSxncQXLTdtD4Mjjz/SoE3e4rQEadl0us+LWveHwkYDD9A+03V3Cevy1vxMqHXTLvwVoV6Nv7gJRnhMRdXVMlqKDEbmwENdBNHv0KGf9abbJO0o02TKIATu5vf4riJjFx4AELnM9pMz4yoZX9DqTkXAJieTiS7m4CvyuR0tXnwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAk1hhWmQSwnykUeBce2Nfuf7nJarCA6g7EBJCsID103hV8iqUl2OfJKIJmgMeW8/fxk29LUbVGE9xup0L0RaQi2ZW9YAzhodvMtna2GQx2CprHy/zlL1d8X3+iVDdGh6pEN4bRE2Rlz/sqcIE3aFp7AMubQ0Zk/n2g2kGMCDHZI8bVirHis/7vjxXeTOF178tKznFBHYnrIBxgXD/RlObTTGXCpFWnGvjXLFg6BasFHJpRI4yt33CVhFWgb7vbQgFxOKrg5OpoDFKMyjFYgOiPKeVOL5qEOq6Gkgi49SY382ifclyG5joET71hK3q2Rnvi3PFaJhd4WNAn+2JJTCjY"
    }
}`

Here is the response that i got
`PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly8xMC41LjEyNi42MDo5NDQwL2FwaS9udXRhbml4L3YzL2lkZW50aXR5X3Byb3ZpZGVycy9jYWxsYmFjayIgSUQ9ImlkNTkyNzc0MzUyMDQ5NjE4MjEwMTcxODkyNjMiIElzc3VlSW5zdGFudD0iMjAxOC0wNS0wOFQwNjo0NDo1OS4zMzBaIiBWZXJzaW9uPSIyLjAiPjxzYW1sMjpJc3N1ZXIgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij5odHRwOi8vd3d3Lm9rdGEuY29tL2V4a2U4eHIwNWUzNGhUeUVjMGg3PC9zYW1sMjpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxkczpSZWZlcmVuY2UgVVJJPSIjaWQ1OTI3NzQzNTIwNDk2MTgyMTAxNzE4OTI2MyI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8+PGRzOkRpZ2VzdFZhbHVlPm1Mdlo0WkNTT29PdWtpQkl4ME9aZk9ZeVdES28vNGU5U2FwZG9jbDZvdXM9PC9kczpEaWdlc3RWYWx1ZT48L2RzOlJlZmVyZW5jZT48L2RzOlNpZ25lZEluZm8+PGRzOlNpZ25hdHVyZVZhbHVlPnVQTzdlektuMzJDVUxXWWJrMjF4K3dRZUhENmlSa1ZldG92UWt2ei8rUlRTbzVKQno1RDhTd3Btb2FacUZNWlNrMktVdzBZMUxUc09RbG8zT2czTU52cW5qT3VDeUtIcC9SU3Q0dXJoTnIyZlZKSGhoV25GL21sRHBsMi95cms2TmZaNUNmU09KTVcvM2hxTlJMOStSOVZWeExvc01lZmNoampoeEdxQnFUOUJmVlF5V0VydDJtUnkySDVUY2ZaZ2NLOTJJMEUyQzZ4N282cHV0Zjg1ODNPS1RldWhpTG1GaTFETVlaVWdQTUd0S3YyZ0xvV1dFdGRJcWFzSHBMMUNlZXJDQnJpQWNmT1VMQXkyMDVBc09aUVBSd3JCa040SkZnbTZUajQ1YkhLQ3pnbmZWc2NGZmNWZmRpQy85L3NnV2FianNBMEd2YVE3VVQ3Skc4aDBDdz09PC9kczpTaWduYXR1cmVWYWx1ZT48ZHM6S2V5SW5mbz48ZHM6WDUwOURhdGE+PGRzOlg1MDlDZXJ0aWZpY2F0ZT5NSUlEcERDQ0FveWdBd0lCQWdJR0FXSUZCT1cxTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdTTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHCkExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUKTUJJR0ExVUVDd3dMVTFOUFVISnZkbWxrWlhJeEV6QVJCZ05WQkFNTUNtUmxkaTAwTXpVNU56Z3hIREFhQmdrcWhraUc5dzBCQ1FFVwpEV2x1Wm05QWIydDBZUzVqYjIwd0hoY05NVGd3TXpBNE1EazBPVEk1V2hjTk1qZ3dNekE0TURrMU1ESTVXakNCa2pFTE1Ba0dBMVVFCkJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG1iM0p1YVdFeEZqQVVCZ05WQkFjTURWTmhiaUJHY21GdVkybHpZMjh4RFRBTEJnTlYKQkFvTUJFOXJkR0V4RkRBU0JnTlZCQXNNQzFOVFQxQnliM1pwWkdWeU1STXdFUVlEVlFRRERBcGtaWFl0TkRNMU9UYzRNUnd3R2dZSgpLb1pJaHZjTkFRa0JGZzFwYm1adlFHOXJkR0V1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjMwTjA5RUJZd3h3VlF5NHBaYnlRd1F0V1RNQ3VvdzJZV1dneTdxSXQ1ZUdJRStYWEFYSGY2dHgvSThIRjZZaEhSQUVFS0E4RFdBRFMKK2wzemgySzF1bldIbWFVOXcwVjFXNGJrV0ZuR2lVM2lkN2haTzdQMnRWTlhwWWFMaVpCa2xaOVZRRnJxakczMHdDaTM1NklobE14NQpSeGpaVlRxQ0RNRFlqV1I3S2ZucHpTeG5jUVhMVGR0RDRNamp6L1NvRTNlNHJRRWFkbDB1cytMV3ZlSHdrWUREOUErMDNWM0NldnkxCnZ4TXFIWFRMdndWb1Y2TnY3Z0pSbmhNUmRYVk1scUtERWJtd0VOZEJOSHYwS0dmOWFiYkpPMG8wMlRLSUFUdTV2ZjRyaUpqRng0QUUKTG5NOXBNejR5b1pYOURxVGtYQUppZVRpUzdtNEN2eXVSMHRYbndJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFrMWhoVwptUVN3bnlrVWVCY2UyTmZ1ZjduSmFyQ0E2ZzdFQkpDc0lEMTAzaFY4aXFVbDJPZkpLSUptZ01lVzgvZnhrMjlMVWJWR0U5eHVwMEwwClJhUWkyWlc5WUF6aG9kdk10bmEyR1F4MkNwckh5L3psTDFkOFgzK2lWRGRHaDZwRU40YlJFMlJsei9zcWNJRTNhRnA3QU11YlEwWmsKL24yZzJrR01DREhaSThiVmlySGlzLzd2anhYZVRPRjE3OHRLem5GQkhZbnJJQnhnWEQvUmxPYlRUR1hDcEZXbkd2alhMRmc2QmFzRgpISnBSSTR5dDMzQ1ZoRldnYjd2YlFnRnhPS3JnNU9wb0RGS015akZZZ09pUEtlVk9MNXFFT3E2R2tnaTQ5U1kzODJpZmNseUc1am9FClQ3MWhLM3EyUm52aTNQRmFKaGQ0V05BbisySkpUQ2pZPC9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48L2RzOktleUluZm8+PC9kczpTaWduYXR1cmU+PHNhbWwycDpTdGF0dXMgeG1sbnM6c2FtbDJwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiPjxzYW1sMnA6U3RhdHVzQ29kZSBWYWx1ZT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnN0YXR1czpTdWNjZXNzIi8+PC9zYW1sMnA6U3RhdHVzPjxzYW1sMjpBc3NlcnRpb24geG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIElEPSJpZDU5Mjc3NDM1MjA1MzI4NDY3NzM1MTA5NjAiIElzc3VlSW5zdGFudD0iMjAxOC0wNS0wOFQwNjo0NDo1OS4zMzBaIiBWZXJzaW9uPSIyLjAiPjxzYW1sMjpJc3N1ZXIgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDplbnRpdHkiIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5odHRwOi8vd3d3Lm9rdGEuY29tL2V4a2U4eHIwNWUzNGhUeUVjMGg3PC9zYW1sMjpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxkczpSZWZlcmVuY2UgVVJJPSIjaWQ1OTI3NzQzNTIwNTMyODQ2NzczNTEwOTYwIj48ZHM6VHJhbnNmb3Jtcz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PC9kczpUcmFuc2Zvcm1zPjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNzaGEyNTYiLz48ZHM6RGlnZXN0VmFsdWU+NWVURHFuUjQ5OU03ZnRHd0ZNek4rSHptS1o1elZPUDdSdlJVZ1d4OUEwND08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlbmNlPjwvZHM6U2lnbmVkSW5mbz48ZHM6U2lnbmF0dXJlVmFsdWU+aGZPYW5yMkwrUFBhdUd3RCt3c2FST1hJTzNTQ0l4NWpYSnp2UmRkTENHYmFmWFVHaldZUFU0cjNxbVZuV29ZZWUzaW1OQ1UxZDI0L0tpM3dhZVpVR3J4QTZNUWpDSEVXN2g5VDN0NEV6UEJ5NjZlMHJFa090VFJNSGlhT3d4OVFlcFh6OUlObzNKWFRMK1FtaGJIVEtqLzl3b1hNdzRPK1NDdFd2SVNqZzBmaW1ySHBNN0RLTG1rRjhteklLdUo3dEQzdHFHa2phclFIaU9SYU91Nm5ESTJLUm10N0NIL1VuNFdVeWFKeGIwS2J6QnZ0MXZDQ2pjbUlnWTRHeEJFZFEzcm1CVDJyMFRPVEtCbVJsRml0NHQ0UWFnUXI0NGMzV1ZRSjRmQkdvbW9yL3hqQUd2YVdQRU82TTNaQ2hITkZpTW9tQ2tVdWdkbDIzSUFUUXBTZlVnPT08L2RzOlNpZ25hdHVyZVZhbHVlPjxkczpLZXlJbmZvPjxkczpYNTA5RGF0YT48ZHM6WDUwOUNlcnRpZmljYXRlPk1JSURwRENDQW95Z0F3SUJBZ0lHQVdJRkJPVzFNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1NNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcKQTFVRUNBd0tRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RU5NQXNHQTFVRUNnd0VUMnQwWVRFVQpNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RXpBUkJnTlZCQU1NQ21SbGRpMDBNelU1TnpneEhEQWFCZ2txaGtpRzl3MEJDUUVXCkRXbHVabTlBYjJ0MFlTNWpiMjB3SGhjTk1UZ3dNekE0TURrME9USTVXaGNOTWpnd016QTRNRGsxTURJNVdqQ0JrakVMTUFrR0ExVUUKQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNNRFZOaGJpQkdjbUZ1WTJselkyOHhEVEFMQmdOVgpCQW9NQkU5cmRHRXhGREFTQmdOVkJBc01DMU5UVDFCeWIzWnBaR1Z5TVJNd0VRWURWUVFEREFwa1pYWXRORE0xT1RjNE1Sd3dHZ1lKCktvWklodmNOQVFrQkZnMXBibVp2UUc5cmRHRXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKMzBOMDlFQll3eHdWUXk0cFpieVF3UXRXVE1DdW93MllXV2d5N3FJdDVlR0lFK1hYQVhIZjZ0eC9JOEhGNlloSFJBRUVLQThEV0FEUworbDN6aDJLMXVuV0htYVU5dzBWMVc0YmtXRm5HaVUzaWQ3aFpPN1AydFZOWHBZYUxpWkJrbFo5VlFGcnFqRzMwd0NpMzU2SWhsTXg1ClJ4alpWVHFDRE1EWWpXUjdLZm5welN4bmNRWExUZHRENE1qanovU29FM2U0clFFYWRsMHVzK0xXdmVId2tZREQ5QSswM1YzQ2V2eTEKdnhNcUhYVEx2d1ZvVjZOdjdnSlJuaE1SZFhWTWxxS0RFYm13RU5kQk5IdjBLR2Y5YWJiSk8wbzAyVEtJQVR1NXZmNHJpSmpGeDRBRQpMbk05cE16NHlvWlg5RHFUa1hBSmllVGlTN200Q3Z5dVIwdFhud0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWsxaGhXCm1RU3dueWtVZUJjZTJOZnVmN25KYXJDQTZnN0VCSkNzSUQxMDNoVjhpcVVsMk9mSktJSm1nTWVXOC9meGsyOUxVYlZHRTl4dXAwTDAKUmFRaTJaVzlZQXpob2R2TXRuYTJHUXgyQ3BySHkvemxMMWQ4WDMraVZEZEdoNnBFTjRiUkUyUmx6L3NxY0lFM2FGcDdBTXViUTBaawovbjJnMmtHTUNESFpJOGJWaXJIaXMvN3ZqeFhlVE9GMTc4dEt6bkZCSFlucklCeGdYRC9SbE9iVFRHWENwRlduR3ZqWExGZzZCYXNGCkhKcFJJNHl0MzNDVmhGV2diN3ZiUWdGeE9Lcmc1T3BvREZLTXlqRllnT2lQS2VWT0w1cUVPcTZHa2dpNDlTWTM4MmlmY2x5RzVqb0UKVDcxaEszcTJSbnZpM1BGYUpoZDRXTkFuKzJKSlRDalk8L2RzOlg1MDlDZXJ0aWZpY2F0ZT48L2RzOlg1MDlEYXRhPjwvZHM6S2V5SW5mbz48L2RzOlNpZ25hdHVyZT48c2FtbDI6U3ViamVjdCB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+PHNhbWwyOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1laWQtZm9ybWF0OnVuc3BlY2lmaWVkIj5hbm5pZS5waWxsYWlAbnV0YW5peC5jb208L3NhbWwyOk5hbWVJRD48c2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbiBNZXRob2Q9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpjbTpiZWFyZXIiPjxzYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uRGF0YSBOb3RPbk9yQWZ0ZXI9IjIwMTgtMDUtMDhUMDY6NDk6NTkuMzMwWiIgUmVjaXBpZW50PSJodHRwczovLzEwLjUuMTI2LjYwOjk0NDAvYXBpL251dGFuaXgvdjMvaWRlbnRpdHlfcHJvdmlkZXJzL2NhbGxiYWNrIi8+PC9zYW1sMjpTdWJqZWN0Q29uZmlybWF0aW9uPjwvc2FtbDI6U3ViamVjdD48c2FtbDI6Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMTgtMDUtMDhUMDY6Mzk6NTkuMzMwWiIgTm90T25PckFmdGVyPSIyMDE4LTA1LTA4VDA2OjQ5OjU5LjMzMFoiIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj48c2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48c2FtbDI6QXVkaWVuY2U+aHR0cHM6Ly8xMC41LjEyNi42MDo5NDQwPC9zYW1sMjpBdWRpZW5jZT48L3NhbWwyOkF1ZGllbmNlUmVzdHJpY3Rpb24+PC9zYW1sMjpDb25kaXRpb25zPjxzYW1sMjpBdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMTgtMDUtMDhUMDU6MDY6MzEuODYyWiIgU2Vzc2lvbkluZGV4PSJpZDE1MjU3NjE4OTkzMzAuMjA0NTg0ODcyNiIgeG1sbnM6c2FtbDI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPjxzYW1sMjpBdXRobkNvbnRleHQ+PHNhbWwyOkF1dGhuQ29udGV4dENsYXNzUmVmPnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0PC9zYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj48L3NhbWwyOkF1dGhuQ29udGV4dD48L3NhbWwyOkF1dGhuU3RhdGVtZW50Pjwvc2FtbDI6QXNzZXJ0aW9uPjwvc2FtbDJwOlJlc3BvbnNlPg==`

**Comment by namanrajbaid** [comment]
I check python-saml code and i found error in this part of code:-
`/onelogin/saml2/utils.py:`
`def validate_node_sign(signature_node, elem, cert=None, fingerprint=None, fingerprintalg='sha1', validatecert=False, debug=False):
....
        try:
            dsig_ctx.verify(signature_node)  # fails here
        except Exception as err:`
in mac xmlsec1 version is 1.2.25 (openssl) and its working fine. but in centos xmlsec version is xmlsec1 1.2.20 (openssl) and it's not working. It is giving me this error.
`Signature validation failed. SAML Response rejected`
Any fix for centos?
I can not see 1.2.25 (openssl) version for centos.

**Comment by pitbulk** [comment]
We delegate the signature validation to the dm.xmlsec.binding library, so that bug you experienced with specific openssl version is out of our control.

Have you tried to execute on the CentOS environment a signature verification in command line and check the result?
```
xmlsec1 --verify -id-attr:ID Assertion --id-attr:ID Response --trusted-pem cert.crt  response.xml
```

**Comment by namanrajbaid** [comment]
i tried above mentioned command and got this output.
`OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0`

**Comment by pitbulk** [comment]
So it seems an issue on [dm.xmlsec.binding](https://pypi.org/project/dm.xmlsec.binding/) or its dependencies...

Have you tried to run the tests and verify that you get also errors?
```
pip install -e ".[test]"
python setup.py test
```

**Comment by namanrajbaid** [comment]
got this error:-

running test
running egg_info
writing requirements to src/python_saml.egg-info/requires.txt
writing src/python_saml.egg-info/PKG-INFO
writing top-level names to src/python_saml.egg-info/top_level.txt
writing dependency_links to src/python_saml.egg-info/dependency_links.txt
reading manifest file 'src/python_saml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'src/python_saml.egg-info/SOURCES.txt'
running build_ext
Segmentation fault (core dumped)

**Comment by alexazevedo** [comment]
Depending on the operational system you will also need to install additional libraries.
In my case, I got the issue on a CentOS server, so I needed to install more 2 dependencies in addition to xmlsec1:

yum install libffi-devel xmlsec1 xmlsec1-openssl

This solved my problem.
You should also have a look on Okta's documentation. They have a guide on how to use PySAML2 to add support for Okta (via SAML) to applications written in Python.

https://developer.okta.com/code/python/pysaml2/
