### ISSUE TITLE
IDP Metadata

### ISSUE THREAD

**Issue by peppelinux** [onelogin/python-saml#233]
Is possibile to load IDP metadatas xml file instead of define its available resources as:

            "idp": {
                "entityId": IDP_METADATA_URL,
                "singleSignOnService": {
                    "url": '{}/login/process/'.format(IDP_URL),
                    "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                },
                "singleLogoutService": {
                    "url": '{}/ls/'.format(IDP_URL),
                    "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                },

It would be good if a scheduled metadata download could update every IDP definition without modify settings.json file

**Comment by pitbulk** [comment]
Check the [OneLogin_Saml2_IdPMetadataParser](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/idp_metadata_parser.py) class
