### ISSUE TITLE
"The response was received at http://django-service:8000/acs instead of https://localhost:8443/acs"

### ISSUE THREAD

**Issue by borninla** [onelogin/python-saml#236]
I am trying to get SSO working between my SP and the IdP (google). However, Gsuite requires an ACS url with the HTTPS protocol (for obvious reasons).

I am currently testing locally. The SP is set up through Django, and I have a Nginx layer in the front which is re-porting from HTTP to HTTPS. Everything works fine up until the point of receiving the error message in the title.

Is there a way to get around this and have it point explicitly to the HTTPS url? Or maybe there is an easier way straight through Django? I tried without using Nginx but it seems like I need an extra framework to handle the re-porting.

Thanks!

**Comment by pitbulk** [comment]
You need to play with the 
[prepare_django_request](https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L18) method.

So the parameters you set on that method must be aligned with the nginx server.

**Comment by borninla** [comment]
Thank you, was able to overwrite http_host and server_port parameters. Just getting a "signature validation failed" error but I think I might not have the right certs. Hopefully this helps someone in the future!
