### ISSUE TITLE
Error when running pip install python-saml

### ISSUE THREAD

**Issue by jafetmorales** [onelogin/python-saml#237]
This is the output when running <code>pip install python-saml</code>
```
Collecting python-saml
  Downloading https://files.pythonhosted.org/packages/2b/05/c709c6f23df8a939e324b3136042957256e779f3fb0492fb7b0bfff7d1b4/python-saml-2.4.1.tar.gz (72kB)
Collecting dm.xmlsec.binding==1.3.3 (from python-saml)
  Downloading https://files.pythonhosted.org/packages/02/ba/b534536eb50bc013cd8dc3116c46eee4bff5b9e57e2af23f81afc574a67a/dm.xmlsec.binding-1.3.3.tar.gz (120kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-ueuyv6lm\dm.xmlsec.binding\setup.py", line 72
        print "Warning : cflag %s skipped" % flag
                                         ^
    SyntaxError: Missing parentheses in call to print

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-ueuyv6lm\dm.xmlsec.binding\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by pitbulk** [comment]
It seems an issue with the installation of the dm.xmlsec.binding dependency.

There is a thread where devs share it experience installing it here:
https://github.com/onelogin/python-saml/issues/30


It seems there were releases on July of [dm.xmlsec.binding(https://pypi.org/project/dm.xmlsec.binding/#history).

I [updated](https://github.com/onelogin/python-saml/commit/d3dbe3e9788c312c79d78d4292b0d2792605a3c4) python-saml to use the latest, [1.3.7](https://pypi.org/project/dm.xmlsec.binding/1.3.7/)

**Comment by travisfraser** [comment]
Do you have plans for a new version of python-saml that has these changes?

**Comment by pitbulk** [comment]
with the latest version is working for you guys?

**Comment by travisfraser** [comment]
The last published version does not build since it still pulls in the old dm.xmlsec.binding version.

**Comment by pitbulk** [comment]
Released [2.4.2](https://pypi.org/project/python-saml/)

**Comment by pitbulk** [comment]
[2.4.2](url)

**Comment by pitbulk** [comment]
[2.4.2](url)

**Comment by pitbulk** [comment]
@jafetmorales and @travisfraser Please verify now it works as expected

**Comment by jafetmorales** [comment]
@pitbulk Unfortunately, I still get the error. The problem is that I am using Python 3, so the parentheses is needed when printing something. The dependency dm.xmlsec.binding is only available for Python 2, and python-saml is available only for Python 2 as well. So porting of python-saml to Python 3 so that it works for people like me would require porting dm.xmlse.binding to Python 3 as well. But the guy who makes dm.xmlse.binding apparently does not have a repository anywhere. So he would need to have a repository, or we would need to post an unofficial version of dm.xmlse.binding. Also, other issues might arise from other python-saml dependencies that we might need to solve to port it to Python 3.

**Comment by pitbulk** [comment]
If you use python3, then why are you not using python3-saml instead python-saml?

Code is compatible and it uses a different library.

**Comment by jafetmorales** [comment]
My bad, that's in the third sentence of the README. This issue is closed.

**Comment by travisfraser** [comment]
We ended up going the python3-saml route even though we are on python 2. This combination works well.
