### ISSUE TITLE
Typo in DSA_SHA1 constant's value?

### ISSUE THREAD

**Issue by chipx86** [onelogin/python-saml#238]
I'm just getting familiar with this package, but while browsing through the constants, I noticed this inconsistency:

https://github.com/onelogin/python-saml/blob/3814b0fe98d6ab78cf92b39c15e1785b1cab22bb/src/onelogin/saml2/constants.py#L106

Note the `/` in the value `http://www.w3.org/2000/09/xmld/sig#dsa-sha1`, which differs from every spec I can find, including information on the package's README. I imagine this should be `http://www.w3.org/2000/09/xmldsig#dsa-sha1`.

**Comment by pitbulk** [comment]
You are right, do you have a PR?

**Comment by chipx86** [comment]
I don't. I'm happy to put one together but I'm just about to take off for a vacation and wanted to check on this before I completely forget in a week :)
