### ISSUE TITLE
Tests missing on PyPI

### ISSUE THREAD

**Issue by jtojnar** [onelogin/python-saml#240]
I am trying to package python-saml for NixOS but cannot run tests because the PyPI package lacks them.

See also the Debian thread about the issue:
https://lists.debian.org/debian-python/2016/04/msg00074.html

Edit: meant to open it for [python3-saml](https://github.com/onelogin/python3-saml/issues/115), but it applies here as well.

**Comment by pitbulk** [comment]
See: https://github.com/onelogin/python3-saml/issues/115
