### ISSUE TITLE
Support more decimal places for seconds

### ISSUE THREAD

**Issue by jalan** [onelogin/python-saml#250]
`OneLogin_Saml2_Utils.parse_SAML_to_time` currently supports two formats:
 - `%Y-%m-%dT%H:%M:%SZ`
 - `%Y-%m-%dT%H:%M:%S.%fZ`

We're seeing Azure AD send timestamps like `2019-06-26T14:19:51.2123335Z` in its SAML responses, with seven decimal digits. This is odd, but some other SAML tools accept it.

**Comment by jalan** [comment]
My mistake, it wasn't Azure sending these odd timestamps, but some other unknown IDP.

**Comment by charleslavon** [comment]
@pitbulk what are your thoughts on this issue and [the corresponding PR](https://github.com/onelogin/python-saml/pull/251)?
