### ISSUE TITLE
Generic CAS client

### ISSUE THREAD

**Issue by pikkewyn** [onelogin/python-saml#256]
I would like to ask  if  this implementation is OneLogin specific or works with standard CAS schema https://apereo.github.io/cas/4.2.x/images/cas_flow_diagram.png. If not could you please recommend any Python CAS library that works with this schema?

**Comment by pitbulk** [comment]
CAS and SAML are different protocols.

I know that Apareo Server can act as a SAML Identity Provider. Check this documentation:
https://apereo.github.io/cas/5.2.x/installation/Configuring-SAML2-Authentication.html

So is possible to integrate it with the php-saml toolkit.
