### ISSUE TITLE
onelogin sso configuration with custom idp <shows invalid user response>

### ISSUE THREAD

**Issue by vinothkumar1097** [onelogin/python-saml#257]
Hi,

Im using my company login as idp. Its working fine with flask localhost http://127.0.0.1:5000
But when i replace local host url with my company url entity id(https://xxx.yyy.net/metadata) and acs url(https://xxx.yyy.net/saml/acs/), its not working. 

After successfull login, saml response is hitting acs url for saml validation. I got saml response and relaystate in my saml response.

But after that, instead of returning to my homepage url im getting **invalid user error(Not Authenticated).** 

Im using IIS to deploy my flask app with bindings as (Type: http | HostName : xxx.yyy.net | Port:80 | IP Address : All Unassigned) and (Type: http | HostName : xxx.yyy.net | Port:8080 | IP Address : server ip address)

Please help me guys to fix this ACS validation. 

**Flask code for ACS url:**
@app.route('/saml/acs/', methods=['GET', 'POST'])
def acs():
    request_id = None
    if 'AuthNRequestID' in session:
        request_id = session['AuthNRequestID']

    write_to_log(request.url)         #returns **http://xxx.yyy.net/saml/acs/**

    req = prepare_from_request(request)
    auth = init_saml_auth(req)
    errors = []
    auth.process_response(request_id=request_id)
    errors = auth.get_errors()
    if not auth.is_authenticated():
        return 'User Not Authenticated'
    else:
        if len(errors) == 0:
            session['samlUserdata'] = auth.get_attributes()
            self_url = OneLogin_Saml2_Utils.get_self_url(req)
            if 'RelayState' in request.form and self_url != request.form['RelayState']:
                return redirect(auth.redirect_to(request.form['RelayState']))

**Settings.json:**
    "strict": true,
    "debug": true,
    "sp": {
        "entityId": "https://xxx.yyy.net/metadata",
        "assertionConsumerService": {
            "url": "https://xxx.yyy.net/saml/acs/",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
            "url": "https://xxx.yyy.net/saml/sls/",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        "x509cert": "",
        "privateKey": ""
    }

**Advanced Settings.json**
"security": {
        "nameIdEncrypted": false,
        "authnRequestsSigned": false,
        "logoutRequestSigned": false,
        "logoutResponseSigned": false,
        "signMetadata": false,
        "wantMessagesSigned": false,
        "wantAssertionsSigned": false,
        "wantNameId" : true,
        "wantNameIdEncrypted": false,
        "wantAssertionsEncrypted": false,
        "signatureAlgorithm": "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
        "digestAlgorithm": "http://www.w3.org/2000/09/xmldsig#sha1"
    }

Within saml folder, i have certs folder which contains self-signed .crt and .key files

When SAML response is hitting acs url, im getting below Request and SAML Response
**Request**
Request URL: https://xxx.yyy.net/saml/acs/
Request Method: POST
Status Code: 200 OK

**SAML Response** 
<?xml 
version="1.0" 
encoding="UTF-8"?>
<saml2p:Response 
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" 
    Destination="https://xxx.yyy.net/saml/acs/" 
    ID="uuid-cdea1116-e3b2..." 
    InResponseTo="ONELOGIN_67..." 
    IssueInstant="2019-09-08T11:44:53.537Z" 
    Version="2.0">
    <saml2:Issuer 
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">@company idp url
    </saml2:Issuer>
    <ds:Signature 
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod 
                Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod 
                Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            <ds:Reference 
                URI="#uuid-cdea1116-e3b2-468a-93a5-68799b291e2c">
                <ds:Transforms>
                    <ds:Transform 
                        Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform 
                        Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod 
                    Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>+
                    TdNDWqlsMBI3tiOB0OC1Y44Lxk=
                </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
WXY7y3.....tQ==

        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>MI..5g==
                </ds:X509Certificate>
            </ds:X509Data>
            <ds:X509Data>
                <ds:X509Certificate>MIIFDjC.=
                </ds:X509Certificate>
            </ds:X509Data>
            <ds:X509Data>
                <ds:X509Certificate>MIIEP.........jg==
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:Status>
        <saml2p:StatusCode 
            Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/>
        <saml2p:StatusMessage>Error creating saml:Assertion</saml2p:StatusMessage>
    </saml2p:Status>
</saml2p:Response>

**Comment by pitbulk** [comment]
You get "User Not Authenticated" because you are returning this
```
if not auth.is_authenticated():
    return 'User Not Authenticated'
```

When authentication fails, is_authenticated will return True.

In order to know why the SAMLResponse was rejected, add a log or print the error cause.

```
if not auth.is_authenticated():
    msg = 'User Not Authenticated'
    if  errors and len(errors) > 0:
        return 'User Not Authenticated. %s' % auth.get_last_error_reason()
```
