### ISSUE TITLE
Is failOnAuthnContextMismatch properly interpreted?

### ISSUE THREAD

**Issue by PCManticore** [onelogin/python-saml#258]
Hey folks!

This is more of a question than an issue per se. I've looked into `failOnAuthnContextMismatch` and `requestedAuthnContext` and I believe it introduces a behaviour that's not proper according to the SAML spec.

The SAML spec mentions that the `<RequestedAuthnContext> element specifies the authentication context requirements of authentication statements returned in response to a request or query`. Then the `Comparison` option specifies that if the comparison is `set to "exact" or omitted, then the resulting authentication context in the authentication
statement MUST be the exact match of at least one of the authentication contexts specified.`

The same language goes for other `Comparison` such as `minimum` and `maximum`. What I interpret from this spec is that the attribute statement **should** have an `AuthnContext` that is one of the requested authentication contexts, but the interpretation for `failOnAuthnContextMismatch` is that **all** requested contexts should match with the results from `AuthnStatement`.

For context, in our organization we tried to enforce a list of requested authentication contexts that identity providers can use for logging in the users, but we were surprised to see `failOnAuthnContext` taking all `requestedAuthnContext` in account, which resulted in non-sensical behaviour as the identity providers were configured to return either `windows` or `PasswordProtectedTransport` responses.

Thanks for taking a look!

Spec: https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

**Comment by pitbulk** [comment]
The SP sends an AuthNRequest with a list of the valid Auth Context that the SP considers valid.

The IdP verifies that list taking also cares of the value of the "Comparison" field.

Then in the SAMLResponse send back info about what Auth Context was used (in case IdP can't satisfy the authentication, should return an error).

At the SP side, if failOnAuthnContextMismatch is on, we verify that the AuthContext returned in the SAMLResponse belong the list defined at the requestedAuthnContext setting

**Comment by PCManticore** [comment]
Thank you @pitbulk for getting back at me! Just to make sure I understand this part `we should verify that the AuthContext returned in the SAMLResponse belong to the list defined at the requestedAuthnContext setting`. Does that mean that you agree that we need to change https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L187 to be `authn_contexts.intersection(requested_authn_contexts)` or something along those lines?

**Comment by pitbulk** [comment]
Yes, working on fixing it
