### ISSUE TITLE
Possible misspelling of word: enough

### ISSUE THREAD

**Issue by serpulga** [onelogin/python-saml#261]
The error message `contact_not_enought_data` should be `contact_not_enough_data`.

I didn't open a PR because at this point I'm not sure if this has backward compatibility issues; as in people expecting a specific error string in their code.

### Places where this is used:
https://github.com/onelogin/python-saml/search?q=contact_not_enought_data&unscoped_q=contact_not_enought_data

**Comment by pitbulk** [comment]
Since its not a critical issue, I think we are ok fixing the typo. do you have a PR?
