### ISSUE TITLE
Rendering a “<class 'django.template.response.TemplateResponse'>” Object when using python saml.

### ISSUE THREAD

**Issue by muraliselva10** [onelogin/python-saml#265]
I have a requirement to incorporate my existing working openstack horizon with our SSO using python-saml.

Hence i referred to demo docs which is written here:

https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L113

So here as per the guide, I need to render the page as mentioned.

    return render(request, 'auth/login.html', {'errors': errors, 'not_auth_warn': not_auth_warn, 'success_slo': success_slo, 'paint_logout': paint_logout, 'SSO': True})

When I am trying the same I am not getting the expected result on page, to be exact, I am not getting the exact desired page with full details. here is the more detail on the same.

Expected page(This is screenshot of page working fine, before i am enabling saml):

[![correctop][1]][1]

Actual page now(Username and password text box not visible, Because login.html file is not enough to render it, because it need form to fully display, using django_auth_views response object "res" is created for the same):

[![wrongop][2]][2]

Code:

```python
def login(request, template_name=None, extra_context=None, **kwargs):
    """Logs a user in using the :class:`~openstack_auth.forms.Login` form."""

    if not request.is_ajax():.
        if (request.user.is_authenticated() and
                auth.REDIRECT_FIELD_NAME not in request.GET and
                auth.REDIRECT_FIELD_NAME not in request.POST):
            return shortcuts.redirect(settings.LOGIN_REDIRECT_URL)

    # Get our initial region for the form.
    initial = {}
    current_region = request.session.get('region_endpoint', None)
    requested_region = request.GET.get('region', None)
    regions = dict(getattr(settings, "AVAILABLE_REGIONS", []))
    if requested_region in regions and requested_region != current_region:
        initial.update({'region': requested_region})

    if request.method == "POST":
        if django.VERSION >= (1, 6):
            form = functional.curry(forms.Login)
        else:
            form = functional.curry(forms.Login, request)
    else:
        form = functional.curry(forms.Login, initial=initial)

    if extra_context is None:
        extra_context = {'redirect_field_name': auth.REDIRECT_FIELD_NAME}

    if not template_name:
        if request.is_ajax():
            template_name = 'auth/_login.html'
            extra_context['hide'] = True
        else:
            template_name = 'auth/login.html'

    res = django_auth_views.login(request,
                                  template_name=template_name,
                                  authentication_form=form,
                                  extra_context=extra_context,
                                  **kwargs)

    # Save the region in the cookie, this is used as the default
    # selected region next time the Login form loads.
    if request.method == "POST":
        utils.set_response_cookie(res, 'login_region',
                                  request.POST.get('region', ''))

    req = prepare_django_request(request)
    auth = init_saml_auth(req)
    errors = []
    not_auth_warn = False
    success_slo = False
    attributes = False
    paint_logout = False

    if 'sso' in req['get_data']:
        return HttpResponseRedirect(auth.login())

    elif 'slo' in req['get_data']:
        name_id = None
        session_index = None
        if 'samlNameId' in request.session:
            name_id = request.session['samlNameId']
        if 'samlSessionIndex' in request.session:
            session_index = request.session['samlSessionIndex']
        slo_built_url = auth.logout(name_id=name_id, session_index=session_index)
        request.session['LogoutRequestID'] = auth.get_last_request_id()
        print ('set logout id'+auth.get_last_request_id())
        return HttpResponseRedirect(slo_built_url)


    if 'samlUserdata' in request.session:
        paint_logout = True
        if len(request.session['samlUserdata']) > 0:
            attributes = request.session['samlUserdata'].items()

    return render(request, 'auth/login.html', {'errors': errors, 'not_auth_warn': not_auth_warn, 'success_slo': success_slo, 'paint_logout': paint_logout, 'SSO': True})


```

Would like to know what may be the problem here, What can be the fix to overcome this issue.

I have given try as below, tried returning the TemplateResponse object which was created in above mentioned code correct working code was just returning 'res' object from code. 

```
return res
```

hence I tried to return the object instead of html file. ie: 'res' instead of 'auth/login.html'.

```
return render(request, res, {'errors': errors, 'not_auth_warn': not_auth_warn, 'success_slo': success_slo, 'paint_logout': paint_logout, 'SSO': True})
```

It returns error as follow:

    Getting an error as follows:
    
        ContentNotRenderedError at /auth/login/
        The response content must be rendered before it can be accessed.

During analysis, I can see that template object(res), Which is of type: **class 'django.template.response.TemplateResponse'**

Someone please drop thoughts to figure out how we can resolve.

  [1]: https://i.stack.imgur.com/CYaeV.png
  [2]: https://i.stack.imgur.com/z9onJ.png

**Comment by pitbulk** [comment]
That seems a very specific Django question rather than a python-saml issue.

I think you may adapt:

- The render(request, 'auth/login.html', {'errors': errors, 'not_auth_warn': not_auth_warn, 'success_slo': success_slo, 'paint_logout': paint_logout, 'SSO': True}) maybe provising other args
- Your custom auth template and adapt it to the UX required by SAML.
