### ISSUE TITLE
WS-Federation Configuration Example?

### ISSUE THREAD

**Issue by earnolmartin** [onelogin/python-saml#266]
I've looked at https://github.com/onelogin/python-saml/issues/130 and https://github.com/onelogin/python-saml/issues/180, but is there an example somewhere showing us how to configure python-saml to use WS-Federation?  What settings are required for WS-Federation?  

When configuring an app to use WS-Federation in C#, we normally just provide three settings.  They are the settings mentioned in this node.js package:

https://github.com/auth0/passport-wsfed-saml2#configure-strategy-for-adfs-ws-fed

How does that translate for changing entries in the settings.json and advanced_settings.json files for python-saml?

Any help would be appreciated.

**Comment by pitbulk** [comment]
WS-Fed and SAML are different protocols.

This toolkit only support SAML, not WS-Fed.
