### ISSUE TITLE
DeprecationWarning: defusedxml.lxml

### ISSUE THREAD

**Issue by mel-mason** [onelogin/python-saml#267]
I just got a deprecation warning when checking my django project:

> DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release

It looks like it comes from this package - specifically the `from defusedxml.lxml import fromstring` imports in several files. (See https://github.com/onelogin/python-saml/search?q=defusedxml.lxml&unscoped_q=defusedxml.lxml)

Are there any plans to remove this dependency on defusedxml.lxml? I see it's been discussed in #221 , but that seems to be pre-deprecation.

Thanks for all your work on this project

**Comment by pitbulk** [comment]
No plans right now.

See https://github.com/onelogin/python3-saml/issues/159

**Comment by pitbulk** [comment]
cElementTree was removed in Python 3.9. See https://github.com/tiran/defusedxml/issues/50
