### ISSUE TITLE
Url Redirect with query parameters 

### ISSUE THREAD

**Issue by Raja3365** [onelogin/python-saml#270]
Hi

I am trying to construct a SAML  redirect URL with query parameters(name & email) . Below is the snippet.

url = settings.FRONTEND_SAML_REDIRECT_URL + 'saml/{}?{}={}&{}={}'.format(status, name,attrs['name'][0], email,attrs['email'][0])
return HttpResponseRedirect(url)

However i find that from the browser that it is constantly redirect back to origin -->saml url
saml url -->origin . How can i achieve passing query paramter to SAML url

**Comment by pitbulk** [comment]
Not sure what you were trying
