### ISSUE TITLE
cant download libxml2 for windows 10

### ISSUE THREAD

**Issue by ronica4** [onelogin/python-saml#271]
i know there are similar questions but i tried everything and nothing seems to work...
i cant download python3-saml without xmlsec, and cant download xmlsec without libxml2 
for example after donwloading the file manually (libxml2-2.9.4.tar) and pip installing it i get the error :
(venv) C:\Users\user\PycharmProjects\onelogintest>pip install libxml2-2.9.4.tar.gz
Processing c:\users\user\pycharmprojects\onelogintest\libxml2-2.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-veuc4n_9\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-req-build-veuc4n_9\

please help im really stuck

**Comment by pitbulk** [comment]
It should be available.
