### ISSUE TITLE
Add a namespace

### ISSUE THREAD

**Issue by davide-medina** [onelogin/python-saml#272]
I have to insert the namespace 'mdui' to specify information about the service provider.
I have tried to change the template in MD_ENTITY_DESCRIPTOR variable but the builder delete my new namespace.
So I want the tag md:EntityDescriptor from 
`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ...`
to
`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui" ...`

Is it possible?

**Comment by pitbulk** [comment]
you can edit the [metadata](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/metadata.py#L176) string and add it
