### ISSUE TITLE
Print Response in pretty XML 

### ISSUE THREAD

**Issue by dipalmabiagio** [onelogin/python-saml#274]
Hi there,

I can send correctly requests, but how can i print the complete response? I need to print to get it and store.

**Comment by pitbulk** [comment]
It depends on the xml proccesor library, for example with lxml

```
import lxml.etree as etree

x = etree.parse("filename")
print etree.tostring(x, pretty_print=True)
```

**Comment by dipalmabiagio** [comment]
Maybe my question is not clear: using python3-SAML i can't get the complete response object to print as a XML correctly. My question is not about "how to print pretty XML" but "how can i get the full response to print and save as xml?"

**Comment by pitbulk** [comment]
The base64encoded SAMLResponse should be available on the assertion consumer service endpoint as a POST parameter.
You can use the [decode_base64_and_inflate](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L102) method to get the XML version

**Comment by dipalmabiagio** [comment]
Thanks a lot! You can just fetch __request field of authentication used in auth.py and decode base 64 using the Utils class. Thank you :)
