### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by davidstrauss** [onelogin/python-saml#28]
It's just silly to have a modern library that only supports Python 2.7.

**Comment by pitbulk** [comment]
There is no ported version of m2crypto to python3. I found 2 approach:
* https://github.com/mcepl/m2crypto/tree/python3
* https://gitorious.org/chandler/m2crypto/source/31b07d2668d8132fec90fb94417d3c331521283b:
but both have errors on the x509 test, so we can't use it.
Also dm.xmlsec.binding keep supporting only python2.

I googled and found some libraries compatible with python3
* https://github.com/mehcode/python-saml  (Uses lxml and xmlsec library)
* https://github.com/rohe/pysaml2-3 (Uses pycrypto and its own xmldsig and xmlsec classes)

Feel free to use them meanwhile we support python3 (maybe we wait till m2crypto/dm.xmlsec.binding ported to python3, maybe we replace those libraries by others supported in python3).

**Comment by pitbulk** [comment]
There is a fork that support python3 and we plan to support it soon:
https://github.com/bgaifullin/python3-saml

**Comment by swartzrock** [comment]
Is this ready for use? Would love to use OneLogin SAML from a Python3 app.

**Comment by pitbulk** [comment]
We plan to publish it at OneLogin soon. Meanwhile clone and use https://github.com/pitbulk/python3-saml
