### ISSUE TITLE
Licensing issue with Stackoverflow's CC-BY-SA License

### ISSUE THREAD

**Issue by uptickmetachu** [onelogin/python-saml#285]
Hi, thank you for this library. 

We have recently been FOSS audited and this package was flagged with potential licensing issues. 

Code copied/distributed and/or adapted from [Stackoverflow requires](https://stackoverflow.com/help/licensing):
1. attribution and
2. **licensing under the same license as the original ([CC-BY-SA-3.0](https://creativecommons.org/licenses/by-sa/3.0/) or [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)).** 
This repositories MIT License is not compatible with CC-BY-SA.

The code that is causing issue:
https://github.com/onelogin/python-saml/blob/62a96394344c3188edc8aee540706f3255a59c06/src/onelogin/saml2/idp_metadata_parser.py#L257

I would suggest doing something like this: 
Removing the attribution and changing the code significantly but maintaining functionality.

```
def dict_deep_merge(a, b):
    merged_subpaths = {
        k: dict_deep_merge(a[k], b[k]) 
        for k in b 
        if (k in a and isinstance(a[k], dict) and isinstance(b[k], dict))
    }
    return {
        **a, **b, **merged_subpaths
    }
```

Thoughts?

**Comment by pitbulk** [comment]
Hi @uptickmetachu 

I found https://github.com/toumorokoshi/deepmerge which is licensed as MIT. 
I'm not adding a new dependency, but I guess we can extract the code from there:
https://github.com/toumorokoshi/deepmerge/blob/master/deepmerge/strategy/dict.py
