### ISSUE TITLE
Status of python-saml vs python3-saml?

### ISSUE THREAD

**Issue by akx** [onelogin/python-saml#287]
Considering `python3-saml` apparently has support for Python 2.7 too (for now, anyway?) – see the links below, what is the fate or status of this library?

https://github.com/onelogin/python3-saml/blob/174ecfaf6f69c0ac13087b8233c293072b271742/setup.py#L19

https://github.com/onelogin/python3-saml/blob/174ecfaf6f69c0ac13087b8233c293072b271742/.github/workflows/python-package.yml#L14

**Comment by pitbulk** [comment]
python3-saml is the recommended library.

**Comment by akx** [comment]
Should this repository then be e.g. archived, or a new version be released with a DeprecationWarning telling people to use the other version?

**Comment by pitbulk** [comment]
You already have this [warning](https://github.com/onelogin/python-saml#onelogins-saml-python-toolkit) at the top of the README of python-saml:

```
Python 2 was deprecated on January 1, 2020. We recommend to migrate your project
to Python 3 and use python3-saml
```
