### ISSUE TITLE
Change default signing algorithm to not use broken SHA-1 hashing algorithm

### ISSUE THREAD

**Issue by timabbott** [onelogin/python-saml#289]
@pitbulk I just wanted to follow up on #269; using a hashing algorithm that's been broken in an authentication library isn't a reasonable default, even for backwards-compatibility.  The right thing to do is to do a release that changes the default (and document that the SHA-1 algorithms are deprecated).

See https://duo.com/decipher/sha-1-fully-and-practically-broken-by-new-collision and https://duo.com/decipher/openssh-will-deprecate-sha-1 for background -- SHA-1 is deprecated and should not be used.

**Comment by pitbulk** [comment]
Ok, I will implement such change on next release of python-saml / python3-saml and on rest of toolkits.
I will also implement the "reject unsecure algorithms" by default enable

**Comment by pitbulk** [comment]
Done
