### ISSUE TITLE
self-signed cert on IdP causes signature validation errors?

### ISSUE THREAD

**Issue by xtfxme** [onelogin/python-saml#33]
i'm not entirely sure what is going on here, or if this is even a bug, but i cannot get the `sls` endpoint to verify the signature provided by the IdP, failing with:

`signatures.c:346(xmlSecOpenSSLEvpSignatureVerify) obj=rsa-sha1 subject=EVP_VerifyFinal msg=signature do not match errno=18`

searching seems to suggest the underlying xmlsec library does not trust the cert chain, which seems plausible, because the cert is self signed...

it should be noted that other endpoints (sso, acs, and slo) are functioning properly, but IIRC do not require signing (i only enabled this when i was told our domain requires it).

i was unable to find reference documents on how signing with `HTTP-Redirect` binding is suppose to work, but reading the code tells me the the `GET` query is used verbatim, **after** first removing `Signature=...`, at which point the remaining query string is validated using the provided `Signature` + IdP cert, is this correct?

if more information is needed i can provide the arguments being passed to `OneLogin_Saml2_Utils.validate_binary_sign` along with the IdP certificate, once i first verify that is safe to publish... if not, i can send via private channel.

**Comment by pitbulk** [comment]
@xtfxme, any news?

**Comment by xtfxme** [comment]
No, time constraints let me to implement a server-side expiry instead for
now. However I should be able to get you some additional details by the end
of the week.

**Comment by pitbulk** [comment]
@xtfxme any progress?

**Comment by xtfxme** [comment]
No :-( been too busy elsewhere and the project using this does well enough without.

if you'd like to leave it open I will return when possiblex men days of future past otherwise feel free to close and open a new one when the time comes

**Comment by pitbulk** [comment]
Ok

**Comment by JacobAtExp4531** [comment]
> I think you can provide the data since it is public (and no user data is provided in a SAML Logout).
> 
> Related to the SLO process, I'm using the same method to validate Signature on SAML Logout Request and SAML Logout Responses, the OneLogin_Saml2_Utils.validate_binary_sign method that you already discoevered. Maybe the problem is the algorithm used, the default is the RsaSha1.
> 
> Can you enable the debug and check what return the line: https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L952

**Comment by JacobAtExp4531** [comment]
Hi, I got similar issues but with different type :
"func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=368:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
(18, 'Signature is invalid.')"

I used "openssl req -new -x509 -days 3652 -nodes -out sp.crt -keyout sp.key" this command to create new sp x.509 cert and private key and provided in sp configuration.

Not sure what is happening. or what is the cause. My doubt is with this log "data do not match" . Do you have any idea on this.
