### ISSUE TITLE
Does this allow Shibboleth SSO without Apache/mod_shib/shibd?

### ISSUE THREAD

**Issue by ThiefMaster** [onelogin/python-saml#39]
I'm not very familiar with SAML and the related things. Does this package allow you to use Shibboleth SSO in a webapp without using Apache, mod_shibboleth and shibd?

**Comment by pitbulk** [comment]
Hi @ThiefMaster,

this python library allow you to build a SAML Service Provider for your python application (you have demo-test examples for the web frameworks django and flask).

A SAML Service Provider requires a SAML Identity Provider. Our customers connect the service provider to the [OneLogin SAAS IdP](http://onelogin.com).   Shibboleth has a software that let you deploy a [SAML IdP](https://shibboleth.net/products/identity-provider.html).    

shibd and mod_shibboleth are shibboleth components that allow you build [SAML Service Providers](https://shibboleth.net/products/service-provider.html)

**Comment by ThiefMaster** [comment]
I'd like to try python-saml using the SAML infrastructure at my workplace.

When registering a new application with the infrastructure I can choose between these methods:

> - SAML2 without metadata (mostly IIS7/Sharepoint sites)
- SAML2 with online metadata
- SAML2 for mod_auth_mellon with online metadata

Any ideas which method is the correct one for python-saml?

**Comment by pitbulk** [comment]
python-saml supports the SAML 2.0 standard, so you can use any SAML2 Identity Provider.
