### ISSUE TITLE
Django example not working

### ISSUE THREAD

**Issue by KristianOellegaard** [onelogin/python-saml#43]
Hi there,

Thanks for the great library - managed to get up and running with SAML and Onelogin pretty fast - however, the django example does not work.

I made a library which you can just add to requirements.txt and use straight in your code - no copy/pasting needed and no configuration files needed. You can find it here: https://github.com/KristianOellegaard/django-saml-service-provider as well as on PyPI.

Maybe it would make sense to either update the django example in the tutorial or link to this library?

Kind regards,
Kristian

**Comment by pitbulk** [comment]
@KristianOellegaard What problem have you experienced with the django-demo app? It works for me  (Django==1.6.5).

The point of include a demo-django folder is to teach python users how the python-saml toolkit works.
I'm agree with you that your approach is better to be used in django projects, but is not the goal.

I will review your django app and include it in the documentation of this project so users gonna be able to find it.

**Comment by pitbulk** [comment]
@KristianOellegaard can you say to us why the django-demo is not working for you?

**Comment by KristianOellegaard** [comment]
I tried with the newest Django, but it's been a while so I don't  recall the exact error.

**Comment by pitbulk** [comment]
I tested it with Django==1.7.5 and is working
