### ISSUE TITLE
SLO does not complete with Azure AD

### ISSUE THREAD

**Issue by eyalsusser** [onelogin/python-saml#44]
When performing SLO, the final redirection back to my site does not occur, so my app does not have a chance to invoke the end session callback at the end of the SLO process.

Azure will show an logout error page, with an unspecified error. Looking at Azure documentation, it seemed that the wrong nameId was being sent, as Azure expects the exact name provided during login, while the connector generated a nameId randomly.

When discussing with OneLogin support, their investigations yielded this:

------
It may have to do with the NameID not looking like this:

    <saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Format="http://schemas.xmlsoap.org/claims/UPN">user</saml:NameID>
--------

Thanks!

**Comment by pitbulk** [comment]
In this commit we introduced the support of adding NameID to the logout process:
https://github.com/onelogin/python-saml/commit/fef7b81efa68f4dc2c5c85e1456e85ee3d868981

The code of our demos not use it, but review the documentation:
https://github.com/onelogin/python-saml/blob/master/README.md#initiate-slo


and check this. Instead of:
```
auth = OneLogin_Saml2_Auth(req)
auth.logout()
```
use:
```
name_id = 'xxx'
session_index = 'yyy'
auth.logout(name_id=name_id, session_index=session_index)
```

You can retrieve the name_id and the session_index from the Saml Response when it is processed by the toolkit by the methods: get_nameid and get_session_index

**Comment by eyalsusser** [comment]
Is this fix available on PyPi, or should I build from source (sorry if this
is a boob question).

On Mon, Feb 2, 2015 at 3:16 PM, Sixto Martin <notifications@github.com>
wrote:

> In this commit we introduced the support of adding NameID to the logout
> process:
> fef7b81
> <https://github.com/onelogin/python-saml/commit/fef7b81efa68f4dc2c5c85e1456e85ee3d868981>
>
> The code of our demos not use it, but review the documentation:
> https://github.com/onelogin/python-saml/blob/master/README.md#initiate-slo
>
> and check this. Instead of:
>
> auth = OneLogin_Saml2_Auth(req)
> auth.logout()
>
> use:
>
> name_id = 'xxx'
> session_index = 'yyy'
> auth.logout(name_id=name_id, session_index=session_index)
>
> You can retrieve the name_id and the session_index from the Saml Response
> when it is processed by the toolkit by the methods: get_nameid and
> get_session_index
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onelogin/python-saml/issues/44#issuecomment-72529345>.
>



-- 
Eyal Susser
VP Development
https://gotomeet.me/eyals
Skype: eyal.susser

**Comment by pitbulk** [comment]
This change is available in the pypi version.

You can see that the [2.1.0 version of the toolkit](https://github.com/onelogin/python-saml/releases/tag/v2.1.0), that is available in [pypi](https://pypi.python.org/pypi/python-saml): 

has "Add nameID & sessionIndex support on Logout Request" in the changelog.

**Comment by eyalsusser** [comment]
Ah. Brilliant, thanks!

On Mon, Feb 2, 2015 at 3:28 PM, Sixto Martin <notifications@github.com>
wrote:

> This change is available in the pypi version.
>
> You can see that the 2.1.0 version of the toolkit
> <https://github.com/onelogin/python-saml/releases/tag/v2.1.0>, that is
> available in pypi <https://pypi.python.org/pypi/python-saml>:
>
> has "Add nameID & sessionIndex support on Logout Request" in the changelog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onelogin/python-saml/issues/44#issuecomment-72531241>.
>



-- 
Eyal Susser
VP Development
https://gotomeet.me/eyals
Skype: eyal.susser

**Comment by pitbulk** [comment]
I added the examples:
https://github.com/onelogin/python-saml/commit/4ca42012124dcc361911086bf39b00aeb6f83e61

Let me know if you need anything else.
