### ISSUE TITLE
flask-demo - question about configs for http vs https

### ISSUE THREAD

**Issue by Zoogie** [onelogin/python-saml#45]
Hiya,

Thanks for the awesome toolkit. I got the flask-demo app to work beautifully after figuring out how to config stuff on the app panel in my onelogin. 

I plugged onelogin into my app in a similar fashion, and it worked fine in my local environment. However when I deployed to staging I kept receiving an invalid_response error because the relaystate kept returning http://app-url.com instead of https://app-url.com. The only way I found to fix this is to hardcode the server_port field in the ini_saml_auth request to 443.

Is this how it's supposed to be done or am I doing something wrong?

Thanks!

**Comment by pitbulk** [comment]
We pass the port here:
https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L26

But I think that maybe you registered wrong the SP metadata in the IdP, or wrong settings:
https://github.com/onelogin/python-saml/blob/master/demo-flask/saml/settings.json#L5

**Comment by pitbulk** [comment]
Duplicated Issue, See #48

**Comment by vinothkumar1097** [comment]
> Hiya,
> 
> Thanks for the awesome toolkit. I got the flask-demo app to work beautifully after figuring out how to config stuff on the app panel in my onelogin.
> 
> I plugged onelogin into my app in a similar fashion, and it worked fine in my local environment. However when I deployed to staging I kept receiving an invalid_response error because the relaystate kept returning http://app-url.com instead of https://app-url.com. The only way I found to fix this is to hardcode the server_port field in the ini_saml_auth request to 443.
> 
> Is this how it's supposed to be done or am I doing something wrong?
> 
> Thanks!
