### ISSUE TITLE
Support for certificate chains

### ISSUE THREAD

**Issue by eyalsusser** [onelogin/python-saml#46]
Currently, a single IdP  SSL certificate can be set in the settings file. For example, the loop reading the cert for fingerprinting will terminate at the first "END CERTIFICATE".

This means that cert chains, where several certs are chained together, cannot be used.

Perhaps making the IdP x509cert field an array of strings instead of a single string could solve this?

**Comment by pitbulk** [comment]
Sorry, for now the toolkit only supports 1 IdP cert.

**Comment by goslackware** [comment]
Just curious, is only a single iDP cert (no internal root\CA chains) still the case with the latest release?
