### ISSUE TITLE
Problem with OneLogin response

### ISSUE THREAD

**Issue by shasha-chen** [onelogin/python-saml#48]
Hi there,

I deployed the demo-flask on an ec2 instance and also ran it on my localhost. And I encountered two problems with the OneLogin library.

First, when I tested the demo-project on ec2,  the server_port in the response received from OneLogin is by default None. Even I provide the port number in the setting.json and in the test connector config, it does not pick up the port number. As a result, it always throw an "The response was received at http://XXX.XXX.XXX: None instead of http://XXX.XXX.XXX" error and resulted in "Not authenticated". So if I hard code self.__request_data['server_port'] = 80 in auth.py, for def process_response(self, request_id=None), the problem will resolve.
However, the server_port is working fine with the demo-flask running on localhost.

Second, when the demo-flask on localhost issued a logout request, the response does not include a "RelayState" and it resulted in TypeError: argument of type 'NoneType' is not iterable. If I hard code self.__request_data['get_data']['RelayState'] = ''" in def process_slo(self, keep_local_session=False, request_id=None, delete_session_cb=None) in saml2/auth.py, it will resolve the problem. But this is working fine with demo-flask on ec2. 

Please kindly tell me how to fix the above problems. Thanks.

**Comment by pitbulk** [comment]
1) The server port should be configure in the [prepare_flask_request](https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L22) method of the index.py.

As you see, by default we try to read the port from the request.url but maybe this is server dependent, so you will need to adjust it under your requirements.

2) In the index.py you see a call to 
[url = auth.process_slo(delete_session_cb=dscb)](https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L70)

This method is defined [here](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L111) and you can see that we [add the RelayState if exists on the request data](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L150) as you already discovered.

The problem should be solved at the [prepare_flask_request](https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L22) method of the index.py
The request.args.copy() is not working for you.

Take a look on the Request Context of your server: http://flask.pocoo.org/docs/0.10/reqcontext/

**Comment by shasha-chen** [comment]
Thanks.

**Comment by shasha-chen** [comment]
I am not sure if I understand you correctly. 
So the problem is that request.args.copy() returns a dict without 'RelayState' as the return value of  prepare_flask_request(), and this return is eventually is passed to  __build_signature(self, saml_data, relay_state, saml_type) which expect a not None value of relay_state. See the track back below.

 Can you elaborate a bit more about the solution? 

File "/Users/shchen/git/tangogit/TAG/tagui/auth.py", line 128, in login
url = auth.process_slo(delete_session_cb=dscb)
File "/Users/shchen/git/tangogit/TAG/env/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 164, in process_slo
'RelayState', None))
File "/Users/shchen/git/tangogit/TAG/env/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 376, in build_response_signature
return self.__build_signature(saml_response, relay_state, 'SAMLResponse')
File "/Users/shchen/git/tangogit/TAG/env/lib/python2.7/site-packages/onelogin/saml2/auth.py", line 407, in __build_signature
relay_state_str = 'RelayState=%s' % quote_plus(relay_state)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1286, in quote_plus
if ' ' in s:

**Comment by pitbulk** [comment]
Sorry for the delay, but missed this ticket. 

SAMLResponse is sent using HTTP-POST binding, so for signing validation the GET parameters have nothing to do.

prepare_flask_request is a very important method where the developer must provide the data that the toolkit requires (python-saml must work with different python frameworks and each framework has its own Request object).

Also notice that there is differences between using Apache, Nginx or Tornado and also if the service is under a proxy or a load balancer.

RelayState is an important parameter in order to redirect the user to the correct endpoint and also is used in the HTTP-Binding validations (Signature validations of Logout Request and Logout Response)

**Comment by shasha-chen** [comment]
Hi Sixto,
Thanks for the reply.
But I am still a bit confused. Can 'RelayState' be None or not? In
saml2/auth.py line 164, in process_slo, RelayState is default to be None.
However, in saml2/auth.py", line 407, in __build_signature, relay_state_str
= 'RelayState=%s' % quote_plus(relay_state) will throw an error if
"RelayState' is None. Therefore, in order to avoid this error, I tried to
hard code the RelayState in the prepare_flask_request.
Best,
Shasha

**Comment by pitbulk** [comment]
I don't see any 407 Line on [saml2/auth.py](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py).

I will review all this stuff about the RelayState issue and execute some tests. Also I will test the HTTPs part and demo-flask.

**Comment by shasha-chen** [comment]
Sorry, it should be 
line 397 relay_state_str = 'RelayState=%s' % quote_plus(relay_state)
Please keep me updated with your test results. Thanks.

**Comment by pitbulk** [comment]
@shasha-chen, the RelayState parameter is a required parameter if you are using signature at the HTTP Redirect Binding.

```

        Relay State

RelayState data MAY be included with a SAML protocol message transmitted with this binding. The value MUST NOT exceed 80 bytes in length and SHOULD be integrity protected by the entity creating the message, either via a digital signature (see section 2.5) or by some independent means.

If a SAML request message is accompanied by RelayState data, then the SAML responder MUST return its SAML protocol response message using a binding that also supports a RelayState mechanism, and it MUST place the exact data it received with the request into the corresponding RelayState parameter in the response message.

If no such value is included with a SAML request message, or if the SAML response message is being generated without a corresponding request, then the SAML responder MAY include RelayState data to be interpreted by the recipient based on the use of a profile or prior agreement between the parties.
```

Reference:
http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-binding-simplesign-cd-04.html

**Comment by pitbulk** [comment]
Can you patch your code and add to the process_slo those lines before the build_response_signature:

```
parameters = {'SAMLResponse': logout_response}
                if 'RelayState' in self.__request_data['get_data']:
                    parameters['RelayState'] = self.__request_data['get_data']['RelayState']
                else:
                    parameters['RelayState'] = OneLogin_Saml2_Utils.get_self_url_no_query(self.__request_data)

```
(Add the else statement and say to me if that fixed your issue).

**Comment by shasha-chen** [comment]
Hi,
I added the patch and tested it on app running local and on ec2 without https, and both worked fine. The patch solved the RelayState problem. But when running the app on https, it still has the gateway timeout issue when logging in.

**Comment by pitbulk** [comment]
The patch was for the RelayState issue, the HTTPs must be a bug with the installation patch.

**Comment by shasha-chen** [comment]
Problem solved. The gateway timeout is caused by the mod_wsgi. When using mod_wsgi to run C modules, we need to add "WSGIApplicationGroup %{GLOBAL}" to the wsgi.conf. 
So it means that the script we used to install python-saml on centos is reliable.  And the https is working fine with python-saml on centos.

**Comment by tomalessi** [comment]
I am having the same problem as described by @shasha-chen in auth.py here:

https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L152

Your patch corrected my problem (setting RelayState if not present).

```python
parameters = {'SAMLResponse': logout_response}
    if 'RelayState' in self.__request_data['get_data']:
        parameters['RelayState'] = self.__request_data['get_data']['RelayState']
    else:
        parameters['RelayState'] = OneLogin_Saml2_Utils.get_self_url_no_query(self.__request_data)
```

Can you merge this change?

Thanks.

**Comment by pitbulk** [comment]
@shasha-chen , @tomalessi  Can you check if this solution works also for you?
```
parameters = {'SAMLResponse': logout_response}
if 'RelayState' in self.__request_data['get_data']:
    parameters['RelayState'] = self.__request_data['get_data']['RelayState']

security = self.__settings.get_security_data()
if 'logoutResponseSigned' in security and security['logoutResponseSigned']:
    if not 'RelayState' in parameters:
         parameters['RelayState'] = OneLogin_Saml2_Utils.get_self_url_no_query(self.__request_data)
    parameters['SigAlg'] = security['signatureAlgorithm']
    parameters['Signature'] = self.build_response_signature(logout_response, parameters['RelayState'], security['signatureAlgorithm'])
return self.redirect_to(self.get_slo_url(), parameters)        
```

I only want to add RelayState when using signature.

**Comment by tomalessi** [comment]
Thanks, understood.

The use case that triggers this error is:
* I am using OneLogin as the IDP
* I have two applications that are authenticating against the IDP
* I am logged into both applications from the same browser with the same OneLogin user account (two separate tabs)
* I perform a SLO logout (which should logout both applications) 

The last application to logout via /sls triggers the error because RelayState is not set.

Instead of subclassing OneLogin_Saml2_Auth and modifying the process_slo method, I added the following in my /sls view (before init_saml_auth).  Basically, if RelayState is not present in the request, add it using a known URL.  This is where the user's browser will end up after all logout events, which is fine because this only happens on the last application to logout via sls.

```python
if request.method == 'POST':
    if not 'RelayState' in request.POST:
        # Get QueryDict is immutable so copy/replace it
        request.POST = request.POST.copy()
        request.POST['RelayState'] = 'https://www.foo.com/bar'
elif request.method == 'GET':
    if not 'RelayState' in request.GET:
        # Get QueryDict is immutable so copy/replace it
        request.GET = request.GET.copy()
        request.GET['RelayState'] = 'https://www.foo.com/bar'
```

Note: This error does not trigger when I login/logout of only one of the applications.
