### ISSUE TITLE
Issue with session in demo-flask

### ISSUE THREAD

**Issue by cbronazc** [onelogin/python-saml#49]
I'm not positive, but I believe there are some typos here: https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L51
Lines 51-54, and 63,64 all say `request.session`, but they should just say `session`. 
I'm guessing the got copied from here: https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L56.
AFAIK request.session isn't a thing in flask, only in django.

**Comment by pitbulk** [comment]
You were right. Fixed. Thanks for reporting that.
