### ISSUE TITLE
OneLogin_Saml2_Logout_Request.get_id()

### ISSUE THREAD

**Issue by nickcoutsos** [onelogin/python-saml#50]
Is there a specific reason for making this method static? I'd like to use it to get the request ID while handling the SLO initiated by the idp, but this requires me to do work that I would expect from the class itself.

From `auth.py`:

```
logout_request = OneLogin_Saml2_Logout_Request(self.__settings, self.__request_data['get_data']['SAMLRequest'])
```

Then a few lines later in the same function:
```
in_response_to = OneLogin_Saml2_Logout_Request.get_id(OneLogin_Saml2_Utils.decode_base64_and_inflate(self.__request_data['get_data']['SAMLRequest']))
```

If the logout request class is already decoding and inflating the request, and storing the result, why do the same work?

Thanks for the library. This looks like a very clean way to integrate with a SAML idp and I'm hoping much easier to maintain than what we're working with now.

**Comment by pitbulk** [comment]
@nickcoutsos I will think about this issue, I want to keep this method static but maybe offer a id method to be available if you built the LogoutRequest since makes sense in order to check in_response_to.

**Comment by pitbulk** [comment]
Message me if this solution does not work for you.
