### ISSUE TITLE
multiple IdPs?

### ISSUE THREAD

**Issue by jiejiang** [onelogin/python-saml#52]
Dear team, is it possible to use multiple IdPs with this plugin? 
Cannot find any information from the instructions.
Sorry to put it here, it is really a question rather than an issue.

**Comment by pitbulk** [comment]
This is a toolkit that let you add SAML support to your python application. If you need to connect your your python app to multiple Idps you have several approachs. For example:
* Use OneLogin platform and use its IdP-Trusted functionality.
* Store the JSON IdPs metadata in a database, create different SAML endpoints (for each IdP) in your app.
