### ISSUE TITLE
Unable to logout from IdP (and support for rsa-sha256)

### ISSUE THREAD

**Issue by jacquesd** [onelogin/python-saml#53]
Hello,
I am trying to use python-saml to login with the SSO at my workplace.
But I encountered a few difficulties with doing so by using the `demo-flask` app.

I managed to perform the login, but I fail to logout and my IdP throws the following error:

```
The SAML Single Logout request does not correspond to the logged-in session participant.
Requestor: https:/<my_sp>/metadata/
Request name identifier: Format: urn:oasis:names:tc:SAML:2.0:nameid-format:transient, NameQualifier:  SPNameQualifier: https://<my_sp>/metadata/, SPProvidedId:
Logged-in session participants:
Count: 1, [Issuer: https://<my_sp>/metadata/, NameID: (Format: urn:oasis:names:tc:SAML:2.0:nameid-format:transient, NameQualifier:  SPNameQualifier: , SPProvidedId: )]

This request failed.
```

From what I understand, it seems python-saml is not sending (properly) the identifier which allows the IdP to match the user in the logout request to the use who is logged in.

I also had troubles with the algorithm to sign the requests.  I need to use `rsa-sha256` for signing the requests as the IdP does not support `rsa-sha1`.

I had a look and it appears that `rsa-sha1` is used as a  hard coded value in quite a few places. I replaced it with `rsa-sha256` and it worked fine until I hit the error above in the logout request.

Maybe the two are related, maybe I missed a spot where some of the data is signed using `rsa-sha1`. 

regarding `rsa-sha256` I will fix it properly and submit a PR as soon as possible. 
But I only have a limited knowledge of SAML so I am not sure how to solve the error mentioned above.

Here is my config, I hope it helps:
```json
"security": {
        "nameIdEncrypted": false,
        "authnRequestsSigned": true,
        "logoutRequestSigned": true,
        "logoutResponseSigned": true,
        "signMetadata": false,
        "wantMessagesSigned": true,
        "wantAssertionsSigned": true,
        "wantNameIdEncrypted": false
},
```
I checked all the certificates are correct and valid.
The IdP is based on Windows AD FS.

**Comment by jacquesd** [comment]
This might also help, here is the xml sent for the login and logout request respectively:

```xml
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="ONELOGIN_5aa0b30704b8170facc38385ebf95ff63cf2d1f1d318a1fe36a2a8110e5a4180"
    Version="2.0"
    ProviderName="{my_sp_fany_name}"
    IssueInstant="2015-03-19T16:17:58Z"
    Destination="https://{idp_sso_url}"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    AssertionConsumerServiceURL="https://{my_sp}/?acs">
    <saml:Issuer>https://{my_sp}/metadata/</saml:Issuer>
    <samlp:NameIDPolicy
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        AllowCreate="true" />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

```xml
<samlp:LogoutRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="ONELOGIN_cef2e43094bd19ac3722bf1adb88b1bbf7d8450b"
    Version="2.0"
    IssueInstant="2015-03-19T13:57:10Z"
    Destination="https://{idp_sls_url}">
    <saml:Issuer>https://{my_sp}/metadata/</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="https://{my_sp}/metadata/">{user.name@email.com}</saml:NameID>
    <samlp:SessionIndex>_ea1f2f90-4dc5-4d22-8fc9-09b07563eaac</samlp:SessionIndex>
</samlp:LogoutRequest>
```

**Comment by pitbulk** [comment]
Hi @jacquesd,

you are right, the Service Provider accepts any kind of encryption algorithm, but [itself uses RSA_SHA1](https://github.com/onelogin/python-saml/blob/ae9ff12a5e28ffe6b0da957516906d06367103c8/src/onelogin/saml2/auth.py#L398). 
We plan to make this configurable (is in the internal roadmap).

Related to the other issue 
```
"The SAML Single Logout request does not correspond to the logged-in session participant."
```

How are you building the SAML Logout Request?
Notice that you may provide the same nameID and session_index that the IdP returned to the SP in the SAML Response:
https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L58

Can you provide examples of the SAML Response, Logout Request and Logout Response flow?

**Comment by jacquesd** [comment]
Hi @pitbulk,

thanks for your prompt reply. 
Regarding the configurable encryption algorithm used by python-saml, this is great news for me and I would love to contribute if you need help implementing it.

Regarding the logout request, I am using the demo-flask app as is without any changes (besides replacing `rsa-sha1` by `rsa-sha256` within python-saml).

From what I could see the name_id and the session_index I get in the assertion match what I send in the logout request.
For example I get the following values in the assertion (https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L65-L66):
```python
name_id = "test.user@email.com"
session_index = "_bbddc23d-be41-498e-ad05-2809538552f5"
```
And I send the same values in the logout request (https://github.com/onelogin/python-saml/blob/master/demo-flask/index.py#L53-L56)
I also find them in the xml I send for the logout request:
```xml
<samlp:LogoutRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="ONELOGIN_0c3cb4a86ac1586e9643b743fe4b332410eb5b70eed5146ec7d8d709ff5c4add"
    Version="2.0"
    IssueInstant="2015-03-19T17:01:02Z"
    Destination="https://{idp_sls_url}">
    <saml:Issuer>https://{my_sp}/metadata/</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="https://{my_sp}/metadata/">test.user@email.com</saml:NameID>
    <samlp:SessionIndex>_bbddc23d-be41-498e-ad05-2809538552f5</samlp:SessionIndex>
</samlp:LogoutRequest>
```

I'll look into how I can catch that SAML response  and I'll post it as soon as possible.
I hope the above helps in the mean time.

**Comment by pitbulk** [comment]
Based on the error that you received, 

The following are possible causes:
* The logout request does not contain a name ID.    
* The user who sent the logout request has never logged in before.
* The logout request contains a name ID whose format or value is different from what was issued for this trust.
* The logout request contains a stored procedure (SP) name qualifier that does not match the security token service (STS) claim issuance rule.

Solution:  Verify that the claims provider trust or the relying party trust configuration is up to date. Use the AD FS 2.0 snap-in to make the format of the name ID rule for this partner and its SPNameQualifier value match the name ID that is present in the logout request.



[Reference](https://technet.microsoft.com/es-es/library/adfs2-troubleshooting-fedpassive-request-failures%28v=ws.10%29.aspx)

**Comment by jacquesd** [comment]
Apologies for the delay, here is the full workflow in order (Authn request , response, logout request and logout response):

```xml
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="ONELOGIN_fe9cf9e7da6140488387c6fcb04a6976b622208f0cce92e23d3f9f5eab3c82ca"
    Version="2.0"
    ProviderName="{my_sp_fancy_name}"
    IssueInstant="2015-03-20T13:09:55Z"
    Destination="https://{idp_sso_url}"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    AssertionConsumerServiceURL="https://{my_sp}/?acs">
    <saml:Issuer>https://{my_sp}/metadata/</saml:Issuer>
    <samlp:NameIDPolicy
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        AllowCreate="true" />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

```xml
<samlp:Response
    ID="_66df0eec-5efc-482b-9897-d4c9468c06c3"
    Version="2.0"
    IssueInstant="2015-03-20T13:11:09.014Z"
    Destination="https://{my_sp}/?acs"
    Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="ONELOGIN_fe9cf9e7da6140488387c6fcb04a6976b622208f0cce92e23d3f9f5eab3c82ca"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">{idp_entity_id}</Issuer>
    <samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></samlp:Status>
    <EncryptedAssertion
        xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <xenc:EncryptedData
            Type="http://www.w3.org/2001/04/xmlenc#Element"
            xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
            <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" />
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#">
                    <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
                        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    </e:EncryptionMethod>
                    <KeyInfo>
                        <ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                            <ds:X509IssuerSerial>
                                <ds:X509IssuerName>CN={my_certification_authority}, DC={ca_domain_comp1}, DC={ca_domain_comp2}</ds:X509IssuerName>
                                <ds:X509SerialNumber>502328419160010235379414</ds:X509SerialNumber>
                            </ds:X509IssuerSerial>
                        </ds:X509Data>
                    </KeyInfo>
                    <e:CipherData>
                        <e:CipherValue>{cipher_value}</e:CipherValue>
                    </e:CipherData>
                </e:EncryptedKey>
            </KeyInfo>
            <xenc:CipherData>
                <xenc:CipherValue>
                    {cipher_data}
                </xenc:CipherValue>
            </xenc:CipherData>
        </xenc:EncryptedData>
    </EncryptedAssertion>
</samlp:Response>
```

```python
decrypted_response = [
    '_66df0eec-5efc-482b-9897-d4c9468c06c3',
    '2.0',
    '2015-03-20T13:11:09.014Z',
    'https://{my_sp}/?acs',
    'urn:oasis:names:tc:SAML:2.0:consent:unspecified',
    'ONELOGIN_fe9cf9e7da6140488387c6fcb04a6976b622208f0cce92e23d3f9f5eab3c82ca'
]
```

```xml
<samlp:LogoutRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    ID="ONELOGIN_82101433af8b3820431d0e46994c9bfb87fa3eb35a41f19c718e3f14781f8b88"
    Version="2.0"
    IssueInstant="2015-03-20T13:14:56Z"
    Destination="https://{idp_sls_url}">
    <saml:Issuer>https://{my_sp}/metadata/</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="https://{my_sp}/metadata/">{test.user@email.com}</saml:NameID>
    <samlp:SessionIndex>_b539995b-ea40-4ac9-9e80-194964354f9a</samlp:SessionIndex>
</samlp:LogoutRequest>
```

```xml
<samlp:LogoutResponse
    ID="_5e11fe5b-86bd-408a-a3d7-21b634b69a86"
    Version="2.0"
    IssueInstant="2015-03-20T13:16:12.908Z"
    Destination="https://{my_sp}/?sls"
    Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
    InResponseTo="ONELOGIN_82101433af8b3820431d0e46994c9bfb87fa3eb35a41f19c718e3f14781f8b88"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">{idp_entity_id}</Issuer>
    <samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester" /></samlp:Status>
</samlp:LogoutResponse>
```

Regarding your last reply, I had a look with the person in charge of the IdP at my workplace and he pointed out that he was missing the `SPNameQualifier` in the token request at login and that might be the reason why the logout fails. He suggested removing the `SPNameQualifier` in the login request to try if it works.

I will try that and let you know what happens.

**Comment by jacquesd** [comment]
There is indeed something wrong with the `SPNameQualifier`. Removing it from the logout request, I obtain the following logout response:

```xml
<?xml version="1.0" ?>
<samlp:LogoutResponse Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" Destination="https://jdafflon.cern.ch:8443/?sls" ID="_7198b9ec-adf9-455f-af5a-d6c26c44349b" InResponseTo="ONELOGIN_c172d6b70881b28bb0589ab29d476b8db53054d21853f489d4ef1747bd9bee4e" IssueInstant="2015-03-23T10:56:28.050Z" Version="2.0" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://cern.ch/login</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </samlp:Status>
</samlp:LogoutResponse>
```

Which looks much more promising.
However, removing the `SPNameQualifier` from the logout request feels more like a work around. Something must be wrong in the login request, but I don't know why.

On the client (SP) side, I also still fail to verify the signature, even when using `rsa-sha256`. I get the following:
```bash
signatures.c:346(xmlSecOpenSSLEvpSignatureVerify) obj=rsa-sha256 subject=EVP_VerifyFinal msg=signature do not match errno=18
Signature validation failed. Logout Response rejected

```
I thought this was caused from the algorithm use or the bad logout request but apparently there is also something wrong somewhere else.

**Comment by pitbulk** [comment]
Can you try to validate the responses on this tool?  https://www.samltool.com/

**Comment by jacquesd** [comment]
Nice tool ;)
I did and indeed both the SAML Response and the Logout Response failed with:
`Signature validation failed. SAML Response rejected` and `Signature validation failed. Logout Response rejected` respectively.

Regarding the SAML response, I have my advanced settings set to accept unsigned messages (`"wantMessagesSigned": false`). Otherwise it fails with the following error: `The Message of the Response is not signed and the SP require it`. It might be possible that my IdP is unable to sign messages, (I will look into that with the people in charge of it) or it might also come from the signature validation failure. In any that must explain why the SAML response is not rejected.

I checked the IdP's x509 cert, as well as my certificate and private key.
I made the following script to sign and verify some data using `openssl` and it appears to works fine, returning me  `Verified OK`.

```bash
#!/bin/sh

echo "\n -- Clearing private key and certificate -- \n"
rm sp.key sp.crt

echo "\n -- PKCS12 Certificate details -- \n"
openssl pkcs12 -info -in host-certificate.p12

echo "\n -- Generating private key -- \n"
openssl pkcs12 -in host-certificate.p12 -out sp.key -nocerts -nodes
openssl rsa -in sp.key -check

echo "\n -- Generating certificate -- \n"
openssl pkcs12 -in host-certificate.p12 -out sp.crt -clcerts -nokeys
openssl x509 -in sp.crt -text -noout

echo "\n -- Generating data -- \n"
echo "Some data\nfor testing" > data.txt

echo "\n -- Generating signature -- \n"
openssl dgst -sha256 -binary -sign sp.key -out signature.sha256 data.txt
cat signature.sha256

echo "\n -- Generating public key -- \n"
openssl x509 -in sp.crt -pubkey -noout > sp.pub
cat sp.pub

echo "\n -- Verify signature -- \n"
openssl dgst -sha256 -verify sp.pub -signature signature.sha256 data.txt

echo "\n -- Cleaning up -- \n"
rm data.txt signature.sha256 sp.pub
```

Using the same key and certificate with the `demo-flask` app fails when trying to verify the signature of the Logout response.

**Comment by pitbulk** [comment]
Must be a signature validation issue.

I know that rsa-sha1 is supported and thought that rsa-sha256 was supported too, but maybe there is some issue with that.

I will review and do test myself and try to fix this issue,but will take time.

**Comment by jacquesd** [comment]
Thanks a lot for your help.

I am using Shibboleth right now to connect to my workplace's SSO and using your library instead is of great interest as it would allow me to get rid of Shibboleth and the Apache dependency.

But there is no urgency in fixing it. I can keep using Shibboleth in the mean time and switch to SAML2 once you manage to fix the issue.

Of course, let me know if there is anything I can do to help you find and fix the issue.

**Comment by pitbulk** [comment]
I will message you once I have a patch and you will able to test it.

Thanks for your patience. sha-2 support is something that I wanted to review in all the OneLogin's toolkits

**Comment by serpulga** [comment]
@pitbulk 
I wonder if there is a list of supported signing algorithms?

**Comment by pitbulk** [comment]
@serpulga, only RSA_SHA1 is supported on signatures for HTTP-Redirect.

I plan to support:
* RSA_SHA1
* RSA_SHA256
* RSA_SHA384
* RSA_SHA512

**Comment by serpulga** [comment]
@pitbulk 
Sorry, I mean incoming signed responses and assertions.

**Comment by pitbulk** [comment]
Now the SP is able to select the algorithm to be used on signatures:
DSA_SHA1, RSA_SHA1, RSA_SHA256, RSA_SHA384 and  RSA_SHA512 are now supported.

**Comment by pitbulk** [comment]
@jacquesd can you test if now the signature validation works?

**Comment by ThiefMaster** [comment]
He's currently away but I'm sure he can give it a try once he's back. Thanks for the improvement :)

**Comment by pitbulk** [comment]
is the same issue reported on the PHP SAML Toolkit. 

ADFS returns A Logout Response with:
```
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester" />
```
So the Logout Process failed.  If you read ADFS report:
```
The SAML Single Logout request does not correspond to the logged-in session participant.
```

is not a signature validation problem, instead: "The SAML Single Logout request does not correspond to the logged-in session participant."

I can't see what NameID was at the SAML Response sent by ADFS since the Assertion is encrypted, but seems that is different than the nameID provided by you on the Logout Request.
```
<saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" SPNameQualifier="https://{my_sp}/metadata/">{test.user@email.com}</saml:NameID>
```

**Comment by dbluestein** [comment]
Referencing #83, which will fix the signature verification issue, in case anyone else like me comes along looking for a solution.
