### ISSUE TITLE
Audience check is not working?

### ISSUE THREAD

**Issue by changjej** [onelogin/python-saml#54]
In strict mode, audience check is enabled however I think its implementation has problem.

```
# Checks audience
valid_audiences = self.get_audiences()
if valid_audiences and sp_entity_id not in valid_audiences:
    raise Exception('%s is not a valid audience for this Response' % sp_entity_id)
```
According to [the homepage's guide](https://onelogin.zendesk.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector),
> so for a consumer URL of google.com/SAML/consume, the audience URL would be google.com.
valid_audiences is 'example.com' and sp_entity_id is 'https://example.com/metadata/'. 

So, testing sp_entity_id in valid_audiences cannot be passed.

**Comment by pitbulk** [comment]
There is no problem with the implementation.
The description at the homepage maybe is confuse, I will ask to fix it.

```
the <AudienceRestriction> element specifies that the assertion is addressed to one or more specific audiences identified by <Audience> elements… The Audience URI MAY identify a document that describes the terms and conditions of audience membership. It MAY contain the unique identifier URI from a SAML name identifier that describes a system entity.” It also says that “the audience restriction condition evaluates to Valid if and only if the SAML relying party is a member of one or more of the audiences specified.
```

So the audience is the URI that identify the Service Provider, (the entity ID) and in the SAML Toolkit we recommend to use the url where the metadata is published, that is why you see https://example.com/metadata/

Google is a different service provider that uses other rules to build its Entity Id.

**Comment by changjej** [comment]
@pitbulk Thank you for your answer. 

Thre problem is solved!

**Comment by chipkellam** [comment]
@pitbulk I am having a similar problem, the Issuer is set as the callback URL, not as the SP entityId and so no match occurs (using 2.1.9).  Any ideas?

**Comment by pitbulk** [comment]
As Issuer you must set the EntityID (The value that identify the entity), not the ACS URL.

**Comment by chipkellam** [comment]
@pitbulk Sorry, that was a little confusingly worded.

I am not directly setting the Issuer, but it comes back in the response as the ACS URL. The entity ID is set using your metadata scheme, but since it doesn't match the ACS URL it is failing.

Basically, the values look like this:

**I set...**
...
'sp': {
    'entityId': sp_entity_id,
    ...
}

**I receive...**
<Audience> sp_acs_url </Audience>

**Comment by pitbulk** [comment]
But then, the Identity Provider setting is not correct.

**Comment by chipkellam** [comment]
@pitbulk Totally correct. Its apparently hardcoded, but that is the issue. Thanks for your help.
