### ISSUE TITLE
Don't build XML with format strings.

### ISSUE THREAD

**Issue by w0rp** [onelogin/python-saml#58]
I was reading the source for this library, and I spotted this here. https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/metadata.py

```
        str_organization = ''
        if len(organization) > 0:
            organization_info = []
            for (lang, info) in organization.items():
                org = """    <md:Organization>
        <md:OrganizationName xml:lang="%(lang)s">%(name)s</md:OrganizationName>
        <md:OrganizationDisplayName xml:lang="%(lang)s">%(display_name)s</md:OrganizationDisplayName>
        <md:OrganizationURL xml:lang="%(lang)s">%(url)s</md:OrganizationURL>
    </md:Organization>""" % \
                    {
                        'lang': lang,
                        'name': info['name'],
                        'display_name': info['displayname'],
                        'url': info['url'],
                    }
                organization_info.append(org)
            str_organization = '\n'.join(organization_info)
```

Has the author of the code ever stopped to consider that if any of the strings in that dictionary contain the right characters, the whole thing will blow up and you'll get invalid XML. The entire file is written this way. This is an obvious mistake. You should not create XML this way. Use `ElementTree` to build the XML instead.

Even if you hate adding a dependency for `lxml`, you don't have to. `ElementTree` is already available in both pure Python and CPython forms in the standard library.

**Comment by pitbulk** [comment]
Some XML are built with format strings willfully and is not an obvious mistake. It only requires that the Servicee Provider administrator take care of the settings parameter that he provide, and you have a validations  to check that the generated XML is correct.

 If you want SAML Messages built using ElementTree use [pysaml2](https://github.com/rohe/pysaml2) instead this library.
