### ISSUE TITLE
Permit settings check for sp only

### ISSUE THREAD

**Issue by toopy** [onelogin/python-saml#74]
I need to validate SP settings only to expose my metadata and IdP + SP if I work on ACS validation on IdP-Initiated POST:

- https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/settings.py#L306

What do you think about splitting the `check_settings` method in `OneLogin_Saml2_Settings` in two new ones `check_sp_settings` and `check_idp_settings` (called in the current one). Could you be interested for a PR in this way ?

**Comment by pitbulk** [comment]
I need to review implications, but PRs are always welcome.
