### ISSUE TITLE
auth.is_authenticated

### ISSUE THREAD

**Issue by tomalessi** [onelogin/python-saml#76]
Hi, I am writing a custom django decorator to decorate any views that will require SAML authentication.  Everything is working properly, however I am trying to find the best way to determine if a user has already successfully authenticated.

Using standard Django authentication we can use user.is_authenticated() but obviously that won't work here.  I see that with OneLogin's modules we can use auth.is_authenticated() function but that only seems to be working during acs, after process_response().  I can't figure out from this docs if this function can be used anytime you want to determine authentication status.

I've defaulted to this:
if not 'samlUserdata' in request.session:
   # start SAML auth

Can you let me know if auth.is_authenticated() is supposed to work on any view?

**Comment by pitbulk** [comment]
As you discovered, those functions only works at the ACS endpoint, when the SAML Response is present. This toolkit is session-less, that means that you may store any related info at the framework level.
When I do a SAML integration using OneLogin toolkits, I always set a ACS endpoint and after the validation process I execute the local login so the local session is created.

In your case you can have a saml_user object stored on session an initiated in the ACS process, so at an extended is_authenticated method you check if that object was or not initiated.

Review also this repository:
https://github.com/KristianOellegaard/

**Comment by tomalessi** [comment]
In my app, I won't actually be storing or referencing any users that are local to Django.  Users that are authenticated via SAML will be read-only so have no profile or settings that I need to reference.  As a result, I cannot do the local login:  e.g. login(request, user) on the /acs view.

Since these session variables are stored during SAML login with python-saml during acs:

request.session['samlUserdata'] = auth.get_attributes()
request.session['samlNameId'] = auth.get_nameid()
request.session['samlSessionIndex'] = auth.get_session_index()

Can't we just check for one of them to determine if the user is already logged in via SAML?  Since only DJango can add session variables (and not the user) this should be an appropriate way to check, right?  Not sure if I'm missing something here.

**Comment by tomalessi** [comment]
Also, I took a look at that repo you posted, but there's nothing there on SAML?

**Comment by pitbulk** [comment]
Yes, as I already said, you can store them on the session at the ACS endpoint, and check for them later. (Remember to clean then once you initiate a logout).

**Comment by pitbulk** [comment]
@tomalessi  is your doubt solved?

**Comment by anderleich** [comment]
Hi,

What about if the user logged out from another application using SSO (not our application) and we need to check if the user is logged in the SSO to use our application? We do not have that information, do we?

**Comment by pitbulk** [comment]
If there is Single Logout Service enable, when the user log off from the app, will initiate a Logout process on all the Apps where the session was initiated.

You can also send an AuthNrequest with isPassive = true to see if the IdP returns a SAMlResponse without the user providing again credentials.
But this is not supported by all IdPs.
