### ISSUE TITLE
server_port can be None

### ISSUE THREAD

**Issue by ganehag** [onelogin/python-saml#77]
In **demo-flask** the function *prepare_flask_request* returns a dict containing **server_port**. The *urlparse* function will return **None** for the key **port** when it is not defined in the parsed URL. Thus *server_port* will also be *None*.

In *onelogin/saml2/utils.py* the method *get_self_url_host* checks for the existence of **server_port** and appends it to the URL to be returnd from *get_self_url_host*. But it only checks if the key is in request_data.

Line 264 of **utils.py** should change from:

    if 'server_port' in request_data:

to

    if 'server_port' in request_data and request_data['server_port'] is not None:

The way the code works today is to cast **server_port** to str even if it is None.

This is probably related to issue #48.

    "The response was received at http://XXX.XXX.XXX: None instead of http://XXX.XXX.XXX" error and resulted in "Not authenticated"

Because **https://example.com:None/?acs** is the URL returned from *get_self_url_host*.

**Comment by pitbulk** [comment]
Fixed.
