### ISSUE TITLE
Dependency to M2Crypto

### ISSUE THREAD

**Issue by elbaschid** [onelogin/python-saml#79]
First of all, thanks for creating a very helpful package to integrate SAML logins. It's helped me a lot so far.

I'm working on a Flask app that is deployed to Heroku. As you might be aware, getting M2Crypto setup on Heroku can be very painful because it relies on `swig`. Looking through the code here, it seems that M2Crypto is a dependency of the package but isn't used directly in the code.

What's the reason for M2Crypto being a dependency for `python-saml`? What would the impact be if it was removed from the mandatory dependencies?

**Comment by pitbulk** [comment]
Hi @elbaschid,

have read http://starboard.flowtheory.net/2015/07/adventures-with-heroku-python-saml-libxmlsec1-and-swig/ ?

Have you tested https://github.com/pitbulk/python3-saml  (we plan to support/maintain it at the OneLogin repo). It's a python3 compatible and doesn't use M2Crypto.

Related to M2Crypto, to be honest I think that it is not required anymore. At the start of the project I used it to handle x509certs but I'm not longer using it. Let me do some research and If not necesary, I will remove it from the dependencies.

**Comment by elbaschid** [comment]
That's awesome @pitbulk, thanks for taking care of this so quickly :+1: This avoids having to worry about M2Crypto on Heroku :star2: I'll take a look at the article above though. 
And I'll keep an eye out for the `python3-saml` project. Is the long-term plan on your end to deprecate this repo in favour of `python3-saml`?

**Comment by pitbulk** [comment]
No, we will maintain both ;)

**Comment by pitbulk** [comment]
Now available at pypi:  https://pypi.python.org/pypi/python3-saml

**Comment by singingwolfboy** [comment]
I'm glad that you've gotten rid of the unused M2Crypto dependency from this project, but until a new version of this project is released on PyPI, it doesn't make much difference. Can you please make a new python-saml release on PyPI, so that M2Crypto doesn't get pulled in automatically?

**Comment by pitbulk** [comment]
Ok, I will release a new version next week :)

**Comment by singingwolfboy** [comment]
@pitbulk The latest version of `python-saml` on PyPI is still 2.1.4, which still declares a dependency on M2Crypto. Can you please release a new version of this project to PyPI?
