### ISSUE TITLE
destination checking in response.py is weird for app running behind a proxy

### ISSUE THREAD

**Issue by wfBeastie** [onelogin/python-saml#81]
Suppose I'm running a django app on localhost:8080 behind a proxy running on $(my ip address):443. My app is processing a SAML response which shows $(my ip address):443 as the "Destination", and the validation routine in response.py compares this with "current_address", which (in this example) is 127.0.0.0:8080 -- and thus throws an exception declaring the response invalid.

This seems like a fairly common situation, and AFAICT, there is no config-based remedy. Sure, you can just hack the request data that you use to construct the OneLogin_Saml2_Auth instance in the first place -- and a TODO in response.py seems to acknowledge as much -- but this feels dirty.

All of that to say, it would be cool if the expected 'destination' could be overridden in the settings file.

**Comment by pitbulk** [comment]
@wfBeastie I think that some changes on the 
[prepare_django_request](https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L18) method to set the proxy data should be enough for solve the destination issue.

**Comment by wfBeastie** [comment]
Yeah, that's a good point. I still think it would be kind of cool if a user could set a config value such as, "expected_destination" that would contain the fully formed destination URL, and in utils.py, this would, if present in the setting, override the inferred "current_url".

Otherwise, one is left reverse engineering the url-building process in utils.py in order to set the fields appropriately in prepare_django_request (and, at least in my case, also adding some logic into prepare_django_request to set the fields conditionally depending on the type of request).

Just a suggestion -- but I'm ok with using prepare_django_request if needed. Thanks for responding!.

**Comment by pitbulk** [comment]
I dislike the "expected_destination" parameter, kind like a trick.

**Comment by wfBeastie** [comment]
Fair enough, though I'm not sure I understand why it's any less of a "trick" to reverse engineer the "current_url" inference logic in utils.py and fiddle with the request object in prepare_django_request.
