### ISSUE TITLE
Supporting Responses that don't have AttributeStatements

### ISSUE THREAD

**Issue by mpaulweeks** [onelogin/python-saml#85]
I've been using your library with great success for the last couple months but have recently run into a weird situation. A new client is trying to send us Responses that don't contain any AttributeStatements. Rather than identify the user with one or more AttributeStatements, they instead use the NameID value in the Subject.

This would be fine and easy to work with, except that when verifying such a Response with `strict=True`, your library raises an Error if there are no AttributeStatements: https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L120

I have forked this library and done some tests locally, and removing that check doesn't seem to interfere with any functionality. Further, I have looked online and can't anything in the SAML2 spec that specifies that an AttributeStatement is necessary.

I would be happy to create a branch that either:
(1) Conditionally checks for AttributeStatements based on a bool configured in the settings (this would default to expecting them for backwards-compatibility).
(2) To remove the check entirely.
However, I want to contact you first and confirm that you would condone/merge such a change before I begin development.

Please let me know what you think!

**Comment by pitbulk** [comment]
This was already reported in other SAML toolkit and I'm thinking about the implication of make AttributeStatements optional.

**Comment by dbluestein** [comment]
I'm now finding myself in the same situation as @mpaulweeks with a client whose responses don't contain AttributeStatements.

+1 for @toopy's solution in #100.

**Comment by toopy** [comment]
I think we can close this one ?

**Comment by mpaulweeks** [comment]
Yep. Thanks @toopy!

**Comment by m6a-UdS** [comment]
@pitbulk What were your conclusions regarding the security implications of not forcing an AttributeStatement? Do you think it's against best-practices set this setting to false?
