### ISSUE TITLE
ImportError: No module named common.saml

### ISSUE THREAD

**Issue by arshpreetsingh** [onelogin/python-saml#87]
I have installed from Github, When I try to import it from standard Python console I got following Error:

 from common.saml import SamlManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named common.saml

**Comment by pitbulk** [comment]
There is no common.saml and no SamlManager
Are you sure is this repository?

**Comment by arshpreetsingh** [comment]
Yes I was using this repository But different tutorial, Apology for  Submitting wrong Issue, Closing it down.
