### ISSUE TITLE
SP initiated SLO does not work

### ISSUE THREAD

**Issue by helmus** [onelogin/python-saml#90]
When a user clicks logout in the SP application the issuer is the SP not the IDP, yet that scenario doesn't seem supported: 

https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/logout_request.py#L298

Is there an other way to handle an SP initiated logout ?
I am testing this against testshib.org IDP.

**Comment by pitbulk** [comment]
In a SP-initiated SLO the SP send the Logout Request and receive a Logout Response. 

Why you try to validate the Logout Request that the SP is creating? you only need to validate the Logout Response sent by the IdP.

In order to execute a SP-Initiated SLO you only need to call the logout method.
