### ISSUE TITLE
Needs a CHANGELOG

### ISSUE THREAD

**Issue by singingwolfboy** [onelogin/python-saml#91]
It's a lot easier to upgrade from one version of a Python module to another when you know what has changed between them. Can this project start keeping a CHANGELOG file, which would track major changes in functionality and backwards-incompatibilities from one version to the next?

**Comment by pitbulk** [comment]
Ok, I will create it, meanwhile review the comments of the different versions:
https://github.com/onelogin/python-saml/releases

**Comment by pitbulk** [comment]
Created: https://github.com/onelogin/python-saml/commit/ddaa132f27d13a57752bcf4598217235a188ece5
