### ISSUE TITLE
Need extensive documentation with different scenario

### ISSUE THREAD

**Issue by rskumar** [onelogin/python-saml#93]
Currently available single page README on github is not sufficient to learn about using library. I have to go through the code to understand at lot of places.
Please consider providing a extensive documentation.

**Comment by pitbulk** [comment]
@rskumar This toolkit provide a README documentation that describes all the settings and also details how the different demos (django, flask, ...) work.

What kind of extra documentation do you expect? can you provide any example?

**Comment by rskumar** [comment]
I agree with you. Documentation got clear to me, after few failures and successes. I think user still has to understand SAML flow and different options (Post/Redirect etc) before implementation. 
For example, with Okta, I had to set their settings "Request Compression" to True. I think this would be required for all redirect type requests with data in GET request. 
If such minimal information would be present as pointer, using this client would be much easier (not blaming the library but whole SAML ecosystem).

**Comment by pitbulk** [comment]
Agree with you that the SAML protocol is complex.

As you can understand, is out of the scope of this toolkit to explain the SAML protocol, instead explain how to manage the settings to get/process different kind of SAML Messages.

At this OneLogin site you can review some extra documentation related to SAML:
https://www.samltool.com/saml_documentation.php

In this toolkit we [deflate_and_base64_encode](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L77) HTTP-Redirect messages. and only [base64decode](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L42) the HTTP-POST messages as the protocol says.

In the [PHP toolkit](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/LogoutRequest.php#L97) we relaxed and accepted no compressed HTTP-Redirect binding messages, but I think that we should be stricts with the standard.


```
For example, with Okta, I had to set their settings "Request Compression" to True. I think this would be required for all redirect type requests with data in GET request. 
```
Notice that this toolkit belong OneLogin Inc, Okta is one of our competitor so don't expect us to fix "our competitor possible bugs" :)
