### ISSUE TITLE
Metadata parser

### ISSUE THREAD

**Issue by rskumar** [onelogin/python-saml#94]
Many Idp provides required info for client setup in metadata available at some URL. 
It would be great if a utility method is provided to parse metadata content (as string), access individual attrs and values in OneLogin_Saml2_Metadata class.

Example: 
```python
metadata = OneLogin_Saml2_Metadata.parse_metadata_from_url(url)
metadata.entity_id
....
# or/and
OneLogin_Saml2_Metadata.parse_metadata_content(str_content)
```

**Comment by pitbulk** [comment]
Our ruby-saml toolkit currently support a way to extract data from a IdP-metadata:
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb

We will consider to extend this functionality to the rest of our toolkits.

**Comment by helmus** [comment]
:+1:

**Comment by rskumar** [comment]
Thanks @pitbulk
