### ISSUE TITLE
Import error when restarting gunicorn under supervisor

### ISSUE THREAD

**Issue by gsvitak** [onelogin/python-saml#97]
Thanks for the great python-saml library.

We have a app that use gunicorn as an app server and celery for async task processing. We have our own framework that is similar to Flask. Both workers run under supervisor.  We have integrated the library into our webapp. Everything works great using the 2,1.5 version. 

However when I stop the gunicorn workers via supervisor and keep celery running, I cannot restart the gunicorn workers. Here is the following stack trace.

File "/home/rbadmin/.virtualenvs/trailhead/local/lib/python2.7/site-packages/onelogin/saml2/utils.py", line 32, in <module>
    from dm.xmlsec.binding.tmpl import EncData, Signature
ImportError: No module named tmpl

However if I stop both supervisor processes, everything restarts fine. 

Any suggestions?

Thanks,
G

**Comment by pitbulk** [comment]
I never experienced this issue.
The dm.xmlsec.binding library is a 3rd party library that python-saml use. I don't know why you are not able to load dm.xmlsec.binding.tmpl.

An alternative is to try [python3-saml](https://github.com/onelogin/python3-saml/)  that is not based on dm.xmlsec.binding.

**Comment by gsvitak** [comment]
Thanks for the suggestion.
