### ISSUE TITLE
Add logging to ease debugging

### ISSUE THREAD

**Issue by ralienpp** [onelogin/python-saml#98]
Please add some logging to the library, to facilitate troubleshooting applications built on top of it.

Unfortunately the documentation does not recommend a troubleshooting strategy, nor is there any logging in the library itself.

I was wondering if you have a guide that one could rely on in order to figure out what causes the failure, as I have inherited a system that uses the library, but does not function correctly.

My actions so far were based solely on common sense:
- ensure that the certificates are valid
- the signatures of the certificates are valid
- the issuer's CA is in the trusted roots of my environment
- there are no network connectivity issues

**Comment by pitbulk** [comment]
Sorry for the late reply.

I dislike the idea of tie this toolkit to a specific logger engine, also understand that is common that we use the toolkit inside a framework like django or flask and those frameworks have their own loggers.

If you enable at the setttings the 'debug' mode, then the (reasons) of the SAML errors will be displayed to the user.
As you can see in the [django-demo}(https://github.com/onelogin/python-saml/blob/master/demo-django/demo/views.py#L70) the [get_errors](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L230) method will store the error when processing a SAMLMessage.

And if you want to control that deeper, you can use the [get_last_error_reason](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L239), this method return the reason of the latest error stored.

**Comment by bradenmacdonald** [comment]
@pitbulk I just wanted to point out that django, flask, and almost all other python code already use the same logging framework, which is the standard `logging` module built into python. I think that this package would be much more pythonic if it used that for logging. Currently, it has fairly idiosyncratic error handling and logging, such as how `utils.py` will writing some messages to `stderr` when the debug flag is true - which is a much more non-standard approach than simply using the standard python logging module.

Like the original reporter here, I would also prefer to see logging added using the standard python approach.

`get_errors` and `get_last_error_reason` are helpful but they don't usually provide enough information to help debug tough issues. And debug mode cannot be used on production servers.
