### ISSUE TITLE
dm.xmlsec.bindings python package broken on windows

### ISSUE THREAD

**Issue by pradyumnak** [onelogin/python-saml#99]
I tried to install the python-saml package using the pip install command, however it failed to installed with following error:
==========================================================
Collecting dm.xmlsec.binding==1.3.2 (from python-saml)
  Using cached dm.xmlsec.binding-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Error : cannot get LibXML2 pre-processor and compiler flags; do you have the `libxml2` development package installed?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\pradym~1\appdata\local\temp\pip-build-njqt1i\dm.xmlsec.binding

=================================================================

Manual installation of the pre-built binaries also not working by copying them in python folders.

Can you please help me know if windows platform is being considered for python-saml package and if yes, then proper steps to configure the dm.xmlsec-bindings?

Since windows does not have concept of devel packages unlike linux, how to get the required files for configuration.

**Comment by spaceone** [comment]
The error message already tells you what you have to do: install the libxml2-dev package.

**Comment by pitbulk** [comment]
I have no experience installing it on Windows.

But I think you may review this old doc where libxml2 was successfully installed:
http://www.returnbooleantrue.com/2008/11/compiling-pyxmlsec-for-windows.html


Reference: https://www.zlatkovic.com/libxml.en.html

**Comment by pradyumnak** [comment]
We were following the reference link only initially, but that is not working with python version 2.7.X(using commands module of python which is deprecated from windows and hence compilation is failing with that source). 

Seems like python3-saml will not work for our need, since we are yet on python 2.7.9 version. Porting to python 3.x will take lot efforts.

Is there anything else we can try?

**Comment by pitbulk** [comment]
python3-saml works with Python 2 too.

**Comment by pradyumnak** [comment]
With python3-saml, we are running into the compilation issues. Following are the errors:

============================================
C:\Users\Pradymuna\Downloads\xmlsec-0.3.3\xmlsec-0.3.3>pip install python3-saml
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): python3-saml in c:\python27\lib\site-packages\python3_saml-1.0.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): isodate>=0.5.0 in c:\python27\lib\site-packages\isodate-0.5.0-py2.7.egg (from python3-saml)
Collecting xmlsec>=0.3.1 (from python3-saml)
  Using cached xmlsec-0.3.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0 in c:\python27\lib\site-packages (from xmlsec>=0.3.1->python3-saml)
Installing collected packages: xmlsec
  Running setup.py install for xmlsec
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\pradym~1\\appdata\\local\\temp\\pip-build-1hti31\\xmlsec
\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\pradym~1\appdata\local
\temp\pip-nwdwoj-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\xmlsec
    copying src\xmlsec\error.py -> build\lib.win-amd64-2.7\xmlsec
    copying src\xmlsec\meta.py -> build\lib.win-amd64-2.7\xmlsec
    copying src\xmlsec\__init__.py -> build\lib.win-amd64-2.7\xmlsec
    running build_ext
    cythoning src\xmlsec\constants.pyx to src\xmlsec\constants.c
    building 'xmlsec.constants' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\src\xmlsec
    C:\Users\Pradymuna\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\Python27
\lib\site-packages\lxml\includes -IC:\Python27\lib\site-packages\lxml -IC:\Python27\include -IC:\Python27\PC /Tcsrc\xmlsec\constants.c /Fobuild\temp.win-amd64-2.7\Re
lease\src\xmlsec\constants.obj -DXMLSEC_CRYPTO_OPENSSL=1
    constants.c
    src\xmlsec\constants.c(2311) : error C2065: 'xmlSecOpenSSLTransformAes128CbcId' : undeclared identifier
    src\xmlsec\constants.c(2311) : warning C4047: 'function' : 'xmlSecTransformId' differs in levels of indirection from 'int'
    src\xmlsec\constants.c(2311) : warning C4024: '__pyx_f_6xmlsec_9constants__mkti' : different types for formal and actual parameter 1
    src\xmlsec\constants.c(2323) : error C2065: 'xmlSecOpenSSLTransformAes192CbcId' : undeclared identifier
    src\xmlsec\constants.c(2323) : warning C4047: 'function' : 'xmlSecTransformId' differs in levels of indirection from 'int'
    src\xmlsec\constants.c(2323) : warning C4024: '__pyx_f_6xmlsec_9constants__mkti' : different types for formal and actual parameter 1
    src\xmlsec\constants.c(2335) : error C2065: 'xmlSecOpenSSLTransformAes256CbcId' : undeclared identifier
    src\xmlsec\constants.c(2335) : warning C4047: 'function' : 'xmlSecTransformId' differs in levels of indirection from 'int'
    src\xmlsec\constants.c(2335) : warning C4024: '__pyx_f_6xmlsec_9constants__mkti' : different types for formal and actual parameter 1
    src\xmlsec\constants.c(2347) : error C2065: 'xmlSecOpenSSLTransformKWAes128Id' : undeclared identifier
    src\xmlsec\constants.c(2347) : warning C4047: 'function' : 'xmlSecTransformId' differs in levels of indirection from 'int'
    src\xmlsec\constants.c(2347) : warning C4024: '__pyx_f_6xmlsec_9constants__mkti' : different types for formal and actual parameter 1
    src\xmlsec\constants.c(2359) : error C2065: 'xmlSecOpenSSLTransformKWAes192Id' : undeclared identifier
    src\xmlsec\constants.c(2359) : warning C4047: 'function' : 'xmlSecTransformId' differs in levels of indirection from 'int'
    src\xmlsec\constants.c(2359) : warning C4024: '__pyx_f_6xmlsec_9constants__mkti' : different types for formal and actual parameter 1
===========================================

Sorry for long logs..:(. Is there anything we are missing? I tried few tweaks with compilation as well.

**Comment by patrick91** [comment]
I'm experiencing the same issue unfortunately,

I opened an issue on both projects (dm.xmlsec.binding and python-xmlsec)

https://github.com/tachang/dm.xmlsec.binding/issues/1
https://github.com/mehcode/python-xmlsec/issues/15

I'm looking for another library that works on windows right now

**Comment by patrick91** [comment]
@pradyumnak we were able to make `python3-saml` work on windows, here I've added some details: https://github.com/mehcode/python-xmlsec/issues/15

Ping me if you need some help ;)

**Comment by pradyumnak** [comment]
Good to hear that!!!!! I just wanted to know if we tried to compile the code with VC++ for python or with minGW. Or any compiler should be fine. I am currently running into some issues, which probably are my environment issues. I will try to rectify those.

**Comment by patrick91** [comment]
@pradyumnak I used Visual Studio for Python, this one IIRC, https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by pradyumnak** [comment]
Thanks much. We are currently trying to build this package from basic and are stuck on libiconv.lib,

**Comment by patrick91** [comment]
@pradyumnak maybe it's better to move this conversation somewhere else, feel free to send me an email with all the errors you get (it is in my profile)

**Comment by bgaifullin** [comment]
I fixed build for windows in https://github.com/mehcode/python-xmlsec/releases/tag/1.3.1
python3-saml uses python-xmlsec and you can use it on windows.
